<?php

use Illuminate\Database\Seeder;

class CapitulosCodificacionProductosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        set_time_limit(0);

		$array_records = array (
			0 => array('naturaleza' => 'DP', 'cod' => 'DP', 'descripcion' => 'PELIGROSO', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			1 => array('naturaleza' => 'CP', 'cod' => '9', 'descripcion' => 'CLASE 9 - SUSTANCIAS Y OBJETOS PELIGROSOS VARIOS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			2 => array('naturaleza' => 'CP', 'cod' => '8', 'descripcion' => 'CLASE 8 - SUSTANCIAS CORROSIVAS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			3 => array('naturaleza' => 'CP', 'cod' => '7', 'descripcion' => 'CLASE 7 - MATERIAL RADIACTIVO', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			4 => array('naturaleza' => 'CP', 'cod' => '6', 'descripcion' => 'CLASE 6 - SUSTANCIAS TÓXICAS Y SUSTANCIAS INFECCIOSAS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			5 => array('naturaleza' => 'CP', 'cod' => '5', 'descripcion' => 'CLASE 5 - SUSTANCIAS COMBURENTES Y PERÓXIDOS ORGÁNICOS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			6 => array('naturaleza' => 'CP', 'cod' => '4', 'descripcion' => 'CLASE 4 - SÓLIDOS INFLAMABLES', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			7 => array('naturaleza' => 'CP', 'cod' => '3', 'descripcion' => 'CLASE 3 - LÍQUIDOS INFLAMABLES', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			8 => array('naturaleza' => 'CP', 'cod' => '2', 'descripcion' => 'CLASE 2 - GASES', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			9 => array('naturaleza' => 'CP', 'cod' => '1', 'descripcion' => 'CLASE 1 - EXPLOSIVOS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			10 => array('naturaleza' => '00', 'cod' => '99', 'descripcion' => 'VARIOS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			11 => array('naturaleza' => '00', 'cod' => '98', 'descripcion' => 'OTROS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			12 => array('naturaleza' => '00', 'cod' => '97', 'descripcion' => 'OBJETOS DE ARTE, DE COLECCIÓN O DE ANTIGÜEDAD', 'carga_extrapesada' => 'SI', 'carga_extradimensionada' => 'SI', 'ind_estado' => 1),
			13 => array('naturaleza' => '00', 'cod' => '96', 'descripcion' => 'MANUFACTURAS DIVERSAS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			14 => array('naturaleza' => '00', 'cod' => '95', 'descripcion' => 'JUGUETES; JUEGOS Y ARTÍCULOS PARA RECREO O PARA DEPORTE; SUS PARTES Y', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			15 => array('naturaleza' => '00', 'cod' => '94', 'descripcion' => 'MUEBLES; MOBILIARIO MEDICOQUIRÚRGICO; ARTÍCULOS DE CAMA Y SIMILARES', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			16 => array('naturaleza' => '00', 'cod' => '93', 'descripcion' => 'ARMAS Y MUNICIONES Y SUS PARTES Y ACCESORIOS', 'carga_extrapesada' => 'SI', 'carga_extradimensionada' => 'SI', 'ind_estado' => 1),
			17 => array('naturaleza' => '00', 'cod' => '92', 'descripcion' => 'INSTRUMENTOS DE MÚSICA; PARTES Y ACCESORIOS DE ESTOS INSTRUMENTOS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			18 => array('naturaleza' => '00', 'cod' => '91', 'descripcion' => 'RELOJERÍA', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			19 => array('naturaleza' => '00', 'cod' => '90', 'descripcion' => 'INSTRUMENTOS Y APARATOS DE ÓPTICA; FOTOGRAFÍA O CINEMATOGRAFÍA', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			20 => array('naturaleza' => '00', 'cod' => '89', 'descripcion' => 'NAVEGACIÓN MARÍTIMA O FLUVIAL', 'carga_extrapesada' => 'SI', 'carga_extradimensionada' => 'SI', 'ind_estado' => 1),
			21 => array('naturaleza' => '00', 'cod' => '88', 'descripcion' => 'NAVEGACIÓN AÉREA O ESPACIAL', 'carga_extrapesada' => 'SI', 'carga_extradimensionada' => 'SI', 'ind_estado' => 1),
			22 => array('naturaleza' => '00', 'cod' => '87', 'descripcion' => 'VEHÍCULOS AUTOMÓVILES; TRACTORES; CICLOS Y DEMÁS VEHÍCULOS TERRESTRES; SUS', 'carga_extrapesada' => 'SI', 'carga_extradimensionada' => 'SI', 'ind_estado' => 1),
			23 => array('naturaleza' => '00', 'cod' => '86', 'descripcion' => 'VEHÍCULOS Y MATERIAL PARA VÍAS FÉRREAS O SIMILARES Y SUS PARTES; APARATOS', 'carga_extrapesada' => 'SI', 'carga_extradimensionada' => 'SI', 'ind_estado' => 1),
			24 => array('naturaleza' => '00', 'cod' => '85', 'descripcion' => 'MÁQUINA; APARATOS Y MATERIAL ELÉCTRICO Y SUS PARTES; APARATOS DE', 'carga_extrapesada' => 'SI', 'carga_extradimensionada' => 'SI', 'ind_estado' => 1),
			25 => array('naturaleza' => '00', 'cod' => '84', 'descripcion' => 'REACTORES NUCLEARES; CALDERAS; MÁQUINAS; APARATOS Y ARTEFACTOS', 'carga_extrapesada' => 'SI', 'carga_extradimensionada' => 'SI', 'ind_estado' => 1),
			26 => array('naturaleza' => '00', 'cod' => '83', 'descripcion' => 'MANUFACTURAS DIVERSAS DE METALES COMUNES', 'carga_extrapesada' => 'SI', 'carga_extradimensionada' => 'SI', 'ind_estado' => 1),
			27 => array('naturaleza' => '00', 'cod' => '82', 'descripcion' => 'HERRAMIENTAS Y ÚTILES; ARTÍCULOS DE CUCHILLERÍA CUBIERTOS DE MESA; DE', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			28 => array('naturaleza' => '00', 'cod' => '81', 'descripcion' => 'LOS DEMÁS METALES COMUNES; <<CERMETS>>; MANUFACTURAS DE ESTAS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			29 => array('naturaleza' => '00', 'cod' => '80', 'descripcion' => 'ESTAÑO Y MANUFACTURAS DE ESTAÑO', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			30 => array('naturaleza' => '00', 'cod' => '79', 'descripcion' => 'CINC Y MANUFACTURAS DE CINC', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			31 => array('naturaleza' => '00', 'cod' => '78', 'descripcion' => 'PLOMO Y MANUFACTURAS DE PLOMO', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			32 => array('naturaleza' => '00', 'cod' => '76', 'descripcion' => 'ALUMINIO Y MANUFACTURAS DE ALUMINIO', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			33 => array('naturaleza' => '00', 'cod' => '75', 'descripcion' => 'NÍQUEL Y MANUFACTURAS DE NÍQUEL', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			34 => array('naturaleza' => '00', 'cod' => '74', 'descripcion' => 'COBRE Y MANUFACTURAS DE COBRE', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			35 => array('naturaleza' => '00', 'cod' => '73', 'descripcion' => 'MANUFACTURAS DE FUNDICIÓN DE HIERRO O DE ACERO', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			36 => array('naturaleza' => '00', 'cod' => '72', 'descripcion' => 'FUNDICIÓN; HIERRO Y ACERO', 'carga_extrapesada' => 'SI', 'carga_extradimensionada' => 'SI', 'ind_estado' => 1),
			37 => array('naturaleza' => '00', 'cod' => '71', 'descripcion' => 'PERLAS FINAS O CULTIVADAS; PIEDRAS PRECIOSAS Y SEMIPRECIOSAS O SIMILARES', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			38 => array('naturaleza' => '00', 'cod' => '70', 'descripcion' => 'VIDRIO Y MANUFACTURAS DE VIDRIO', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			39 => array('naturaleza' => '00', 'cod' => '69', 'descripcion' => 'PRODUCTOS CERÁMICOS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			40 => array('naturaleza' => '00', 'cod' => '68', 'descripcion' => 'MANUFACTURAS DE PIEDRA; YESO; CEMENTO; AMIANTO; MICA O MATERIAS', 'carga_extrapesada' => 'SI', 'carga_extradimensionada' => 'SI', 'ind_estado' => 1),
			41 => array('naturaleza' => '00', 'cod' => '67', 'descripcion' => 'PLUMAS Y PLUMÓN PREPARADOS Y ARTÍCULOS DE PLUMAS O PLUMÓN; FLORES', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			42 => array('naturaleza' => '00', 'cod' => '66', 'descripcion' => 'PARAGUAS; SOMBRILLAS; QUITASOLES; BASTONES; BASTONES ASIENTO; LÁTIGOS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			43 => array('naturaleza' => '00', 'cod' => '65', 'descripcion' => 'ARTÍCULOS DE SOMBRERERÍA Y SUS PARTES', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			44 => array('naturaleza' => '00', 'cod' => '64', 'descripcion' => 'CALZADO; POLAINAS; BOTINES Y ARTÍCULOS ANÁLOGOS; PARTES DE ESTOS ARTÍCULOS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			45 => array('naturaleza' => '00', 'cod' => '63', 'descripcion' => 'LOS DEMÁS ARTÍCULOS TEXTILES CONFECCIONADOS; CONJUNTOS O SURTIDOS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			46 => array('naturaleza' => '00', 'cod' => '62', 'descripcion' => 'PRENDAS Y COMPLEMENTOS DE VESTIR EXCEPTO LOS DE PUNTO', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			47 => array('naturaleza' => '00', 'cod' => '61', 'descripcion' => 'PRENDAS Y COMPLEMENTOS DE VESTIR, DE PUNTO', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			48 => array('naturaleza' => '00', 'cod' => '60', 'descripcion' => 'TEJIDOS DE PUNTO', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			49 => array('naturaleza' => '00', 'cod' => '59', 'descripcion' => 'TEJIDOS IMPREGNADOS; RECUBIERTOS; REVESTIDOS O ESTRATIFICADOS; ARTÍCULOS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			50 => array('naturaleza' => '00', 'cod' => '58', 'descripcion' => 'TEJIDOS ESPECIALES; SUPERFICIES TEXTILES CON PELO INSERTADO; ENCAJES', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			51 => array('naturaleza' => '00', 'cod' => '57', 'descripcion' => 'ALFOMBRAS Y DEMÁS REVESTIMIENTOS PARA EL SUELO, DE MATERIAS TEXTILES', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			52 => array('naturaleza' => '00', 'cod' => '56', 'descripcion' => 'GUATA; FIELTRO Y TELAS SIN TEJER; HILADOS ESPECIALES; CORDELES, CUERDAS Y', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			53 => array('naturaleza' => '00', 'cod' => '55', 'descripcion' => 'FIBRAS SINTÉTICAS O ARTIFICIALES DISCONTINUAS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			54 => array('naturaleza' => '00', 'cod' => '54', 'descripcion' => 'FILAMENTOS SINTÉTICOS O ARTIFICIALES', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			55 => array('naturaleza' => '00', 'cod' => '53', 'descripcion' => 'LAS DEMÁS FIBRAS TEXTILES VEGETALES; HILADOS DE PAPEL Y TEJIDOS DE HILADOS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			56 => array('naturaleza' => '00', 'cod' => '52', 'descripcion' => 'ALGODÓN', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			57 => array('naturaleza' => '00', 'cod' => '51', 'descripcion' => 'LANA Y PELO FINO U ORDINARIO; HILADOS Y TEJIDOS DE CRIN', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			58 => array('naturaleza' => '00', 'cod' => '50', 'descripcion' => 'SEDA', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			59 => array('naturaleza' => '00', 'cod' => '49', 'descripcion' => 'PRODUCTOS EDITORIALES; DE LA PRENSA O DE OTRAS INDUSTRIAS GRÁFICAS; TEXTOS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			60 => array('naturaleza' => '00', 'cod' => '48', 'descripcion' => 'PAPEL Y CARTÓN; MANUFACTURAS DE PASTA DE CELULOSA; DE PAPEL O DE CARTÓN', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			61 => array('naturaleza' => '00', 'cod' => '47', 'descripcion' => 'PASTA DE MADERA O DE OTRAS MATERIAS FIBROSAS CELULÓSICAS; DESPERDICIOS Y', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			62 => array('naturaleza' => '00', 'cod' => '46', 'descripcion' => 'MANUFACTURAS DE ESPARTERÍA O DE CESTERÍA', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			63 => array('naturaleza' => '00', 'cod' => '45', 'descripcion' => 'CORCHO Y SUS MANUFACTURAS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			64 => array('naturaleza' => '00', 'cod' => '44', 'descripcion' => 'MADERA, CARBÓN VEGETAL Y MANUFACTURAS DE MADERA', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			65 => array('naturaleza' => '00', 'cod' => '43', 'descripcion' => 'PELETERÍA Y CONFECCIONES DE PELETERÍA; PELETERÍA ARTIFICIAL O FICTICIA', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			66 => array('naturaleza' => '00', 'cod' => '42', 'descripcion' => 'MANUFACTURAS DE CUERO; ARTÍCULOS DE GUARNICIONERÍA O DE TALABARTERÍA', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			67 => array('naturaleza' => '00', 'cod' => '41', 'descripcion' => 'PIELES (EXCEPTO LA PELETERÍA) Y CUEROS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			68 => array('naturaleza' => '00', 'cod' => '40', 'descripcion' => 'CAUCHO Y MANUFACTURAS DE CAUCHO', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			69 => array('naturaleza' => '00', 'cod' => '39', 'descripcion' => 'MATERIAS PLÁSTICAS Y MANUFACTURAS DE ESTAS MATERIAS', 'carga_extrapesada' => 'SI', 'carga_extradimensionada' => 'SI', 'ind_estado' => 1),
			70 => array('naturaleza' => '00', 'cod' => '38', 'descripcion' => 'PRODUCTOS DIVERSOS DE LAS INDUSTRIAS QUÍMICAS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			71 => array('naturaleza' => '00', 'cod' => '37', 'descripcion' => 'PRODUCTOS FOTOGRÁFICOS O CINEMATOGRÁFICOS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			72 => array('naturaleza' => '00', 'cod' => '36', 'descripcion' => 'PÓLVORAS Y EXPLOSIVOS; ARTÍCULOS DE PIROTECNIA; FÓSFOROS (CERILLAS)', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			73 => array('naturaleza' => '00', 'cod' => '35', 'descripcion' => 'MATERIAS ALBUMINOIDEAS; PRODUCTOS A BASE DE ALMIDÓN O DE FÉCULA', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			74 => array('naturaleza' => '00', 'cod' => '34', 'descripcion' => 'JABONES, AGENTES DE SUPERFICIE ORGÁNICOS, PREPARACIONES PARA LAVAR', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			75 => array('naturaleza' => '00', 'cod' => '33', 'descripcion' => 'ACEITES ESENCIALES Y RESINOIDES; PRODUCTOS PREPARADOS Y PREPARACIONES', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			76 => array('naturaleza' => '00', 'cod' => '32', 'descripcion' => 'EXTRACTOS CURTIENTES O TINTÓREOS; TANINOS Y SUS DERIVADOS; PIGMENTOS Y', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			77 => array('naturaleza' => '00', 'cod' => '31', 'descripcion' => 'ABONOS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			78 => array('naturaleza' => '00', 'cod' => '30', 'descripcion' => 'PRODUCTOS FARMACÉUTICOS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			79 => array('naturaleza' => '00', 'cod' => '29', 'descripcion' => 'PRODUCTOS QUÍMICOS ORGÁNICOS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			80 => array('naturaleza' => '00', 'cod' => '28', 'descripcion' => 'PRODUCTOS QUÍMICOS INORGÁNICOS; COMPUESTOS INORGÁNICOS U ORGÁNICOS DE', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			81 => array('naturaleza' => '00', 'cod' => '27', 'descripcion' => 'COMBUSTIBLES MINERALES; ACEITES MINERALES Y PRODUCTOS DE SU DESTILACIÓN', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			82 => array('naturaleza' => '00', 'cod' => '26', 'descripcion' => 'MINERALES; ESCORIAS Y CENIZAS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			83 => array('naturaleza' => '00', 'cod' => '25', 'descripcion' => 'SAL; AZUFRE; TIERRAS Y PIEDRAS; YESOS, CALES Y CEMENTOS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			84 => array('naturaleza' => '00', 'cod' => '24', 'descripcion' => 'TABACO Y SUCEDÁNEOS DEL TABACO ELABORADOS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			85 => array('naturaleza' => '00', 'cod' => '23', 'descripcion' => 'RESIDUOS Y DESPERDICIOS DE LAS INDUSTRIAS ALIMENTARIAS; ALIMENTOS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			86 => array('naturaleza' => '00', 'cod' => '22', 'descripcion' => 'BEBIDAS; LÍQUIDOS ALCOHÓLICOS Y VINAGRE', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			87 => array('naturaleza' => '00', 'cod' => '21', 'descripcion' => 'PREPARACIONES ALIMENTICIAS DIVERSAS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			88 => array('naturaleza' => '00', 'cod' => '20', 'descripcion' => 'PREPARACIONES DE LEGUMBRES U HORTALIZAS; DE FRUTOS O DE OTRAS PARTES DE', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			89 => array('naturaleza' => '00', 'cod' => '19', 'descripcion' => 'PREPARACIONES A BASE DE CEREALES; HARINA; ALMIDÓN; FÉCULA O LECHE', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			90 => array('naturaleza' => '00', 'cod' => '18', 'descripcion' => 'CACAO Y SUS PREPARACIONES', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			91 => array('naturaleza' => '00', 'cod' => '17', 'descripcion' => 'AZÚCARES Y ARTÍCULOS DE CONFITERÍA', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			92 => array('naturaleza' => '00', 'cod' => '16', 'descripcion' => 'PREPARACIONES DE CARNE, DE PESCADO O DE CRUSTÁCEOS, DE MOLUSCOS O DE', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			93 => array('naturaleza' => '00', 'cod' => '15', 'descripcion' => 'GRASAS Y ACEITES ANIMALES O VEGETALES; PRODUCTOS DE SU DESDOBLAMIENTO', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			94 => array('naturaleza' => '00', 'cod' => '14', 'descripcion' => 'MATERIAS TRENZABLES Y DEMÁS PRODUCTOS DE ORIGEN VEGETAL, NO EXPRESADOS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			95 => array('naturaleza' => '00', 'cod' => '13', 'descripcion' => 'GOMAS; RESINAS Y DEMÁS JUGOS Y EXTRACTOS VEGETALES', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			96 => array('naturaleza' => '00', 'cod' => '12', 'descripcion' => 'SEMILLAS Y FRUTOS OLEAGINOSOS; SEMILLAS Y FRUTOS DIVERSOS; PLANTAS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			97 => array('naturaleza' => '00', 'cod' => '11', 'descripcion' => 'PRODUCTOS DE MOLINERÍA; MALTA; ALMIDÓN Y FÉCULA; INULINA; GLUTEN DE TRIGO', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			98 => array('naturaleza' => '00', 'cod' => '10', 'descripcion' => 'CEREALES', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			99 => array('naturaleza' => '00', 'cod' => '09', 'descripcion' => 'CAFÉ, TÉ, YERBA MATE Y ESPECIAS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			100 => array('naturaleza' => '00', 'cod' => '08', 'descripcion' => 'FRUTOS COMESTIBLES; CORTEZAS DE AGRIOS O DE MELONES', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			101 => array('naturaleza' => '00', 'cod' => '07', 'descripcion' => 'LEGUMBRES Y HORTALIZAS, PLANTAS, RAÍCES Y TUBÉRCULOS ALIMENTICIOS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			102 => array('naturaleza' => '00', 'cod' => '06', 'descripcion' => 'PLANTAS VIVAS Y PRODUCTOS DE LA FLORICULTURA', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			103 => array('naturaleza' => '00', 'cod' => '05', 'descripcion' => 'LOS DEMÁS PRODUCTOS DE ORIGEN ANIMAL NO EXPRESADOS NI COMPRENDIDOS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			104 => array('naturaleza' => '00', 'cod' => '04', 'descripcion' => 'LECHE Y PRODUCTOS LÁCTEOS; HUEVOS DE AVE; MIEL NATURAL; PRODUCTOS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			105 => array('naturaleza' => '00', 'cod' => '03', 'descripcion' => 'PESCADOS Y CRUSTÁCEOS; MOLUSCOS Y OTROS INVERTEBRADOS ACUÁTICOS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			106 => array('naturaleza' => '00', 'cod' => '02', 'descripcion' => 'CARNES Y DESPOJOS COMESTIBLES', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),
			107 => array('naturaleza' => '00', 'cod' => '01', 'descripcion' => 'ANIMALES VIVOS', 'carga_extrapesada' => 'NO', 'carga_extradimensionada' => 'NO', 'ind_estado' => 1),

		);

		foreach (array_chunk($array_records, 1000) as $records) {
			\DB::table('capitulos_codificacion_productos')->insert($records);
		}
    }
}
