<?php

use Illuminate\Database\Seeder;

class MarcasSemiRemolquesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	\DB::table('marcas_semiremolques')->insert(array (
			0 => array('cod_semir' => 1047, 'desc_semir' => 'EMI', 'ind_estado' => 1),
			1 => array('cod_semir' => 1069, 'desc_semir' => 'H QUINTERO', 'ind_estado' => 1),
			2 => array('cod_semir' => 1219, 'desc_semir' => 'TRAMO', 'ind_estado' => 1),
			3 => array('cod_semir' => 1202, 'desc_semir' => 'ADRIANOS TRAILERS Y CARROCERIAS', 'ind_estado' => 1),
			4 => array('cod_semir' => 1311, 'desc_semir' => 'TYR DAKOTA', 'ind_estado' => 1),
			5 => array('cod_semir' => 1435, 'desc_semir' => 'NABORDS', 'ind_estado' => 1),
			6 => array('cod_semir' => 1182, 'desc_semir' => 'TRAILERS DEL CARIBE', 'ind_estado' => 1),
			7 => array('cod_semir' => 1457, 'desc_semir' => 'TRACTO PESADOS Y MONTAJES', 'ind_estado' => 1),
			8 => array('cod_semir' => 1402, 'desc_semir' => 'TRACTOPESADOS', 'ind_estado' => 1),
			9 => array('cod_semir' => 1014, 'desc_semir' => 'CARPIMOTORES', 'ind_estado' => 1),
			10 => array('cod_semir' => 1085, 'desc_semir' => 'INDUSTRIA CARROCERA DE TANQUES YARA', 'ind_estado' => 1),
			11 => array('cod_semir' => 1088, 'desc_semir' => 'INDUSTRIAS METALICAS EL OLIVO', 'ind_estado' => 1),
			12 => array('cod_semir' => 991, 'desc_semir' => 'CARROCERIAS ADONAI', 'ind_estado' => 1),
			13 => array('cod_semir' => 990, 'desc_semir' => 'TRAITANQUES J.J. S.A.S', 'ind_estado' => 1),
			14 => array('cod_semir' => 989, 'desc_semir' => 'CENTRAL DE REP. EL TRANSP', 'ind_estado' => 1),
			15 => array('cod_semir' => 988, 'desc_semir' => 'IND. JVC LOS COSTEÑOS', 'ind_estado' => 1),
			16 => array('cod_semir' => 987, 'desc_semir' => 'LEON Y TORRES', 'ind_estado' => 1),
			17 => array('cod_semir' => 986, 'desc_semir' => 'O.R.G. INGENIERIA LTDA.', 'ind_estado' => 1),
			18 => array('cod_semir' => 977, 'desc_semir' => 'SILVER FOX EQUIPOS Y TRAI', 'ind_estado' => 1),
			19 => array('cod_semir' => 976, 'desc_semir' => 'STEELBRO', 'ind_estado' => 1),
			20 => array('cod_semir' => 975, 'desc_semir' => 'TRANSCRAFT', 'ind_estado' => 1),
			21 => array('cod_semir' => 974, 'desc_semir' => 'SG INGENIERÍA  LTDA', 'ind_estado' => 1),
			22 => array('cod_semir' => 973, 'desc_semir' => 'TODO TRAILER DE STDER', 'ind_estado' => 1),
			23 => array('cod_semir' => 972, 'desc_semir' => 'SINERMIND', 'ind_estado' => 1),
			24 => array('cod_semir' => 971, 'desc_semir' => 'CONTRAIL BY TOWMASTER', 'ind_estado' => 1),
			25 => array('cod_semir' => 970, 'desc_semir' => 'MONTAJES INDUSTRIALES', 'ind_estado' => 1),
			26 => array('cod_semir' => 969, 'desc_semir' => 'R & F', 'ind_estado' => 1),
			27 => array('cod_semir' => 967, 'desc_semir' => 'INSERTEC LTDA  ', 'ind_estado' => 1),
			28 => array('cod_semir' => 966, 'desc_semir' => 'SEMASA', 'ind_estado' => 1),
			29 => array('cod_semir' => 965, 'desc_semir' => 'DOWNINGTOWN', 'ind_estado' => 1),
			30 => array('cod_semir' => 964, 'desc_semir' => 'TRAILERS LA CAROLINA ', 'ind_estado' => 1),
			31 => array('cod_semir' => 961, 'desc_semir' => 'TALLER TANQUES DAZA', 'ind_estado' => 1),
			32 => array('cod_semir' => 959, 'desc_semir' => 'JAYCO', 'ind_estado' => 1),
			33 => array('cod_semir' => 958, 'desc_semir' => 'ROYAL NOOTEBOOM TRAILERS', 'ind_estado' => 1),
			34 => array('cod_semir' => 956, 'desc_semir' => 'INDUDIAZ', 'ind_estado' => 1),
			35 => array('cod_semir' => 954, 'desc_semir' => 'MINCIVIL SA ', 'ind_estado' => 1),
			36 => array('cod_semir' => 953, 'desc_semir' => 'IND. BULLDOG TRUKCS', 'ind_estado' => 1),
			37 => array('cod_semir' => 952, 'desc_semir' => 'TRAILER BAYONA', 'ind_estado' => 1),
			38 => array('cod_semir' => 951, 'desc_semir' => 'SERVIPEÑA', 'ind_estado' => 1),
			39 => array('cod_semir' => 949, 'desc_semir' => 'WALKERS', 'ind_estado' => 1),
			40 => array('cod_semir' => 948, 'desc_semir' => 'IND. BERNAVILLA  S.A.S', 'ind_estado' => 1),
			41 => array('cod_semir' => 947, 'desc_semir' => 'COSMO', 'ind_estado' => 1),
			42 => array('cod_semir' => 944, 'desc_semir' => 'SERVINTSA COLOMBIA SAS.', 'ind_estado' => 1),
			43 => array('cod_semir' => 943, 'desc_semir' => 'ISA', 'ind_estado' => 1),
			44 => array('cod_semir' => 941, 'desc_semir' => 'FRACMA', 'ind_estado' => 1),
			45 => array('cod_semir' => 940, 'desc_semir' => 'TRACKMAN', 'ind_estado' => 1),
			46 => array('cod_semir' => 939, 'desc_semir' => 'INCOLTANQUES S A S ', 'ind_estado' => 1),
			47 => array('cod_semir' => 938, 'desc_semir' => 'TRANSM DE COL DEL PACIF. ', 'ind_estado' => 1),
			48 => array('cod_semir' => 936, 'desc_semir' => 'TRANSMINEROS DE COLOMBIA ', 'ind_estado' => 1),
			49 => array('cod_semir' => 934, 'desc_semir' => 'TOTAL ENERGY GROUP', 'ind_estado' => 1),
			50 => array('cod_semir' => 933, 'desc_semir' => 'TRAILERS OP LTDA', 'ind_estado' => 1),
			51 => array('cod_semir' => 927, 'desc_semir' => 'AIR TOW', 'ind_estado' => 1),
			52 => array('cod_semir' => 926, 'desc_semir' => 'INVERSIONES INTEGRALES MH', 'ind_estado' => 1),
			53 => array('cod_semir' => 925, 'desc_semir' => 'PROY DE ING.METAL.ROJAS  ', 'ind_estado' => 1),
			54 => array('cod_semir' => 924, 'desc_semir' => 'TALLERES Y TRANS PACHO LT', 'ind_estado' => 1),
			55 => array('cod_semir' => 923, 'desc_semir' => 'MULTRACK S.A.S. ', 'ind_estado' => 1),
			56 => array('cod_semir' => 921, 'desc_semir' => 'MASTER TRUCK DE COLOMBIA ', 'ind_estado' => 1),
			57 => array('cod_semir' => 920, 'desc_semir' => 'ELIS & WATTS ', 'ind_estado' => 1),
			58 => array('cod_semir' => 919, 'desc_semir' => 'MANAC', 'ind_estado' => 1),
			59 => array('cod_semir' => 918, 'desc_semir' => 'TECNIBERNAL S.A.S.', 'ind_estado' => 1),
			60 => array('cod_semir' => 917, 'desc_semir' => 'SPOOLER TRAILER', 'ind_estado' => 1),
			61 => array('cod_semir' => 916, 'desc_semir' => 'TRAILERS KNEPPER S.A.S. ', 'ind_estado' => 1),
			62 => array('cod_semir' => 914, 'desc_semir' => 'CARROCERIAS MORA', 'ind_estado' => 1),
			63 => array('cod_semir' => 913, 'desc_semir' => 'PROPAR', 'ind_estado' => 1),
			64 => array('cod_semir' => 912, 'desc_semir' => 'PETROGLOBAL', 'ind_estado' => 1),
			65 => array('cod_semir' => 911, 'desc_semir' => 'ZABALA', 'ind_estado' => 1),
			66 => array('cod_semir' => 910, 'desc_semir' => 'INDUMETALICA MARTINEZ DEL', 'ind_estado' => 1),
			67 => array('cod_semir' => 908, 'desc_semir' => 'RTQUINDIO', 'ind_estado' => 1),
			68 => array('cod_semir' => 907, 'desc_semir' => 'SICA', 'ind_estado' => 1),
			69 => array('cod_semir' => 906, 'desc_semir' => 'NOOTEBOOM', 'ind_estado' => 1),
			70 => array('cod_semir' => 905, 'desc_semir' => 'AMERICAN AUGERS', 'ind_estado' => 1),
			71 => array('cod_semir' => 904, 'desc_semir' => 'SOLUCIONES EN ACERO S.A.S', 'ind_estado' => 1),
			72 => array('cod_semir' => 903, 'desc_semir' => 'TANQUES YARA', 'ind_estado' => 1),
			73 => array('cod_semir' => 902, 'desc_semir' => 'WILCO', 'ind_estado' => 1),
			74 => array('cod_semir' => 901, 'desc_semir' => 'INDUSTRIAS RICAURTE', 'ind_estado' => 1),
			75 => array('cod_semir' => 900, 'desc_semir' => 'INDUSTRIAS WJC S.A.S. ', 'ind_estado' => 1),
			76 => array('cod_semir' => 899, 'desc_semir' => 'TALLER DE SOLDADURA EL RE', 'ind_estado' => 1),
			77 => array('cod_semir' => 898, 'desc_semir' => 'ADVANCE ENGINNER PRODUCTS', 'ind_estado' => 1),
			78 => array('cod_semir' => 897, 'desc_semir' => 'GEIT SAS', 'ind_estado' => 1),
			79 => array('cod_semir' => 896, 'desc_semir' => 'SERVA GROUP  ', 'ind_estado' => 1),
			80 => array('cod_semir' => 894, 'desc_semir' => 'ASOMINERALES CABUYARO SAS', 'ind_estado' => 1),
			81 => array('cod_semir' => 891, 'desc_semir' => 'EXA-INDUSTRIAL', 'ind_estado' => 1),
			82 => array('cod_semir' => 890, 'desc_semir' => 'ECOLINE', 'ind_estado' => 1),
			83 => array('cod_semir' => 889, 'desc_semir' => 'TRANSLADAMOS SAS', 'ind_estado' => 1),
			84 => array('cod_semir' => 887, 'desc_semir' => 'NARIZON', 'ind_estado' => 1),
			85 => array('cod_semir' => 886, 'desc_semir' => 'DE LA GARZA  ', 'ind_estado' => 1),
			86 => array('cod_semir' => 885, 'desc_semir' => 'METALMECO S.A', 'ind_estado' => 1),
			87 => array('cod_semir' => 884, 'desc_semir' => 'IND DE HIERROS Y ACEROS ', 'ind_estado' => 1),
			88 => array('cod_semir' => 882, 'desc_semir' => 'STAGE LINE', 'ind_estado' => 1),
			89 => array('cod_semir' => 881, 'desc_semir' => 'SMART TRAILERS', 'ind_estado' => 1),
			90 => array('cod_semir' => 880, 'desc_semir' => 'TECNIFORMAS', 'ind_estado' => 1),
			91 => array('cod_semir' => 879, 'desc_semir' => 'JINDO', 'ind_estado' => 1),
			92 => array('cod_semir' => 878, 'desc_semir' => 'T y T TRAILERS & TANQUES', 'ind_estado' => 1),
			93 => array('cod_semir' => 877, 'desc_semir' => 'AMERICAN TRAILERS', 'ind_estado' => 1),
			94 => array('cod_semir' => 876, 'desc_semir' => 'SUPERANDES', 'ind_estado' => 1),
			95 => array('cod_semir' => 875, 'desc_semir' => 'FHARMAVICOLA', 'ind_estado' => 1),
			96 => array('cod_semir' => 874, 'desc_semir' => 'GRUPO GLM', 'ind_estado' => 1),
			97 => array('cod_semir' => 870, 'desc_semir' => 'INDUSTRIAS TRB SAS', 'ind_estado' => 1),
			98 => array('cod_semir' => 868, 'desc_semir' => 'MTI LTDA', 'ind_estado' => 1),
			99 => array('cod_semir' => 867, 'desc_semir' => 'INGPETROL LTDA', 'ind_estado' => 1),
			100 => array('cod_semir' => 866, 'desc_semir' => 'SOLUMEK S.A', 'ind_estado' => 1),
			101 => array('cod_semir' => 865, 'desc_semir' => 'GRUPO DIMASIM LTDA', 'ind_estado' => 1),
			102 => array('cod_semir' => 864, 'desc_semir' => 'CEM SAS', 'ind_estado' => 1),
			103 => array('cod_semir' => 863, 'desc_semir' => 'INDUSTRIAS J A R H S A S', 'ind_estado' => 1),
			104 => array('cod_semir' => 862, 'desc_semir' => 'TRAILER ANDINO S.A.S', 'ind_estado' => 1),
			105 => array('cod_semir' => 861, 'desc_semir' => 'FEGOMO SAS', 'ind_estado' => 1),
			106 => array('cod_semir' => 860, 'desc_semir' => 'INTACA S.A.S.', 'ind_estado' => 1),
			107 => array('cod_semir' => 859, 'desc_semir' => 'DE LUCIO', 'ind_estado' => 1),
			108 => array('cod_semir' => 858, 'desc_semir' => 'STECO', 'ind_estado' => 1),
			109 => array('cod_semir' => 856, 'desc_semir' => 'MUNDO INOX S.A.S', 'ind_estado' => 1),
			110 => array('cod_semir' => 854, 'desc_semir' => 'CARROC. Y FURG DEL CARIBE', 'ind_estado' => 1),
			111 => array('cod_semir' => 853, 'desc_semir' => 'BRENNER', 'ind_estado' => 1),
			112 => array('cod_semir' => 852, 'desc_semir' => 'DEMARESCSI', 'ind_estado' => 1),
			113 => array('cod_semir' => 851, 'desc_semir' => 'S & S INDUSTRIALES LTDA', 'ind_estado' => 1),
			114 => array('cod_semir' => 850, 'desc_semir' => 'TRASAM', 'ind_estado' => 1),
			115 => array('cod_semir' => 849, 'desc_semir' => 'MONTAJES SAS', 'ind_estado' => 1),
			116 => array('cod_semir' => 848, 'desc_semir' => 'INDEPENDENCE', 'ind_estado' => 1),
			117 => array('cod_semir' => 847, 'desc_semir' => 'GENERAL MOTORS', 'ind_estado' => 1),
			118 => array('cod_semir' => 846, 'desc_semir' => 'TANQUES Y REMOLQUES DAKOT', 'ind_estado' => 1),
			119 => array('cod_semir' => 845, 'desc_semir' => 'FADIPETROL SAS', 'ind_estado' => 1),
			120 => array('cod_semir' => 844, 'desc_semir' => 'TUBYSOLD MONTAJES LTDA', 'ind_estado' => 1),
			121 => array('cod_semir' => 843, 'desc_semir' => 'TALLER LA 27', 'ind_estado' => 1),
			122 => array('cod_semir' => 842, 'desc_semir' => 'CARROCERIAS A.F.Z.', 'ind_estado' => 1),
			123 => array('cod_semir' => 841, 'desc_semir' => 'INDU VAN LTDA.', 'ind_estado' => 1),
			124 => array('cod_semir' => 840, 'desc_semir' => 'PH CONSTRUCTORES S.A.', 'ind_estado' => 1),
			125 => array('cod_semir' => 839, 'desc_semir' => 'SERPROMCOL S.A.S', 'ind_estado' => 1),
			126 => array('cod_semir' => 838, 'desc_semir' => 'ESTOR TRAILER S.A.S', 'ind_estado' => 1),
			127 => array('cod_semir' => 836, 'desc_semir' => 'D\'METAL SAS', 'ind_estado' => 1),
			128 => array('cod_semir' => 835, 'desc_semir' => 'INDUSTRIAS NOVALUX LTDA.', 'ind_estado' => 1),
			129 => array('cod_semir' => 833, 'desc_semir' => 'COTTRELL', 'ind_estado' => 1),
			130 => array('cod_semir' => 832, 'desc_semir' => 'ENCE LTDA', 'ind_estado' => 1),
			131 => array('cod_semir' => 831, 'desc_semir' => 'INDUTANQUES ALFA S.A.S.', 'ind_estado' => 1),
			132 => array('cod_semir' => 830, 'desc_semir' => 'FDM TANQUES', 'ind_estado' => 1),
			133 => array('cod_semir' => 829, 'desc_semir' => 'TECNITANQUES & FORJAS', 'ind_estado' => 1),
			134 => array('cod_semir' => 828, 'desc_semir' => 'QMC', 'ind_estado' => 1),
			135 => array('cod_semir' => 827, 'desc_semir' => 'BULLDOG', 'ind_estado' => 1),
			136 => array('cod_semir' => 826, 'desc_semir' => 'TRAYCO', 'ind_estado' => 1),
			137 => array('cod_semir' => 825, 'desc_semir' => 'INDUSTRIAS CARC CAMACHO', 'ind_estado' => 1),
			138 => array('cod_semir' => 824, 'desc_semir' => 'INDUSTRIAS VITRAILER', 'ind_estado' => 1),
			139 => array('cod_semir' => 823, 'desc_semir' => 'ISERPRO', 'ind_estado' => 1),
			140 => array('cod_semir' => 822, 'desc_semir' => 'RHINOX', 'ind_estado' => 1),
			141 => array('cod_semir' => 821, 'desc_semir' => 'A & M SERVICES', 'ind_estado' => 1),
			142 => array('cod_semir' => 820, 'desc_semir' => 'FEGAM', 'ind_estado' => 1),
			143 => array('cod_semir' => 819, 'desc_semir' => 'JEREH', 'ind_estado' => 1),
			144 => array('cod_semir' => 818, 'desc_semir' => 'INDUBRI S A S ', 'ind_estado' => 1),
			145 => array('cod_semir' => 817, 'desc_semir' => 'INDUSTRIAS FELES', 'ind_estado' => 1),
			146 => array('cod_semir' => 816, 'desc_semir' => 'AUTOMAR', 'ind_estado' => 1),
			147 => array('cod_semir' => 815, 'desc_semir' => 'FABRIPETROL SAS', 'ind_estado' => 1),
			148 => array('cod_semir' => 814, 'desc_semir' => 'FABRITANQUES Y MONTAJES L', 'ind_estado' => 1),
			149 => array('cod_semir' => 813, 'desc_semir' => 'TALLERES EL REFUERZO', 'ind_estado' => 1),
			150 => array('cod_semir' => 812, 'desc_semir' => 'CAMACHO YAÑEZ', 'ind_estado' => 1),
			151 => array('cod_semir' => 811, 'desc_semir' => 'TRACTO-RAFER', 'ind_estado' => 1),
			152 => array('cod_semir' => 809, 'desc_semir' => 'TRAILER´S Y MAS', 'ind_estado' => 1),
			153 => array('cod_semir' => 808, 'desc_semir' => 'INVOLTRAC', 'ind_estado' => 1),
			154 => array('cod_semir' => 807, 'desc_semir' => 'COVEREDWAGON TRAILERS', 'ind_estado' => 1),
			155 => array('cod_semir' => 806, 'desc_semir' => 'FERNANDO GONZALEZ', 'ind_estado' => 1),
			156 => array('cod_semir' => 805, 'desc_semir' => 'INDUMECANICOS S.A.S.', 'ind_estado' => 1),
			157 => array('cod_semir' => 804, 'desc_semir' => 'INDUSTRIAS PATIÑO S.A.S.', 'ind_estado' => 1),
			158 => array('cod_semir' => 801, 'desc_semir' => 'GLOBE TRAILERS', 'ind_estado' => 1),
			159 => array('cod_semir' => 798, 'desc_semir' => 'CORFIBRAS', 'ind_estado' => 1),
			160 => array('cod_semir' => 796, 'desc_semir' => 'MUNDO TANQUES COLOMBIA S.', 'ind_estado' => 1),
			161 => array('cod_semir' => 795, 'desc_semir' => 'GONELLA', 'ind_estado' => 1),
			162 => array('cod_semir' => 794, 'desc_semir' => 'JINCOL', 'ind_estado' => 1),
			163 => array('cod_semir' => 793, 'desc_semir' => 'IND. ZABALA', 'ind_estado' => 1),
			164 => array('cod_semir' => 792, 'desc_semir' => 'IMCOLTRANS LTDA', 'ind_estado' => 1),
			165 => array('cod_semir' => 791, 'desc_semir' => 'CONSTRUTANQUES', 'ind_estado' => 1),
			166 => array('cod_semir' => 790, 'desc_semir' => 'TECNI TRAILER JP ', 'ind_estado' => 1),
			167 => array('cod_semir' => 789, 'desc_semir' => 'SANTAND. DE TANQ Y REMOLQ', 'ind_estado' => 1),
			168 => array('cod_semir' => 788, 'desc_semir' => 'EST. DE SERVICIO PINASACO', 'ind_estado' => 1),
			169 => array('cod_semir' => 787, 'desc_semir' => 'TALBERT', 'ind_estado' => 1),
			170 => array('cod_semir' => 783, 'desc_semir' => 'METALCOLME S.A. ', 'ind_estado' => 1),
			171 => array('cod_semir' => 780, 'desc_semir' => 'CIDET S.A.S', 'ind_estado' => 1),
			172 => array('cod_semir' => 779, 'desc_semir' => 'AGROINDUSTRIALES DIAL', 'ind_estado' => 1),
			173 => array('cod_semir' => 778, 'desc_semir' => 'CARROCERIAS ANDINA S.A.S', 'ind_estado' => 1),
			174 => array('cod_semir' => 777, 'desc_semir' => 'ECOEQUIPOS', 'ind_estado' => 1),
			175 => array('cod_semir' => 776, 'desc_semir' => 'TANQS. Y TRAILS.ECOMMERCE', 'ind_estado' => 1),
			176 => array('cod_semir' => 775, 'desc_semir' => 'METALCOMESA S.A.', 'ind_estado' => 1),
			177 => array('cod_semir' => 774, 'desc_semir' => 'KENWORTH DE LA MONTAÑA', 'ind_estado' => 1),
			178 => array('cod_semir' => 773, 'desc_semir' => 'ATLAS REMOLQUES S.A.S', 'ind_estado' => 1),
			179 => array('cod_semir' => 772, 'desc_semir' => 'GAMI', 'ind_estado' => 1),
			180 => array('cod_semir' => 771, 'desc_semir' => 'TEC METALMECAN DEL CARIBE', 'ind_estado' => 1),
			181 => array('cod_semir' => 770, 'desc_semir' => 'C& N. C. Metalúrgicas S.A', 'ind_estado' => 1),
			182 => array('cod_semir' => 769, 'desc_semir' => 'INSEP', 'ind_estado' => 1),
			183 => array('cod_semir' => 768, 'desc_semir' => 'IND. TECNITANQUES R.G. S.', 'ind_estado' => 1),
			184 => array('cod_semir' => 767, 'desc_semir' => 'SKY GAB', 'ind_estado' => 1),
			185 => array('cod_semir' => 766, 'desc_semir' => 'SERVITHOMAS', 'ind_estado' => 1),
			186 => array('cod_semir' => 763, 'desc_semir' => 'CHEETAH', 'ind_estado' => 1),
			187 => array('cod_semir' => 762, 'desc_semir' => 'INDUQUIR', 'ind_estado' => 1),
			188 => array('cod_semir' => 761, 'desc_semir' => 'AUTOBUSES DELTA LTDA ', 'ind_estado' => 1),
			189 => array('cod_semir' => 760, 'desc_semir' => 'REMEC LTDA', 'ind_estado' => 1),
			190 => array('cod_semir' => 759, 'desc_semir' => 'CARMEX', 'ind_estado' => 1),
			191 => array('cod_semir' => 758, 'desc_semir' => 'MAGNUM EQUIPOS S.A.S', 'ind_estado' => 1),
			192 => array('cod_semir' => 757, 'desc_semir' => 'TALLER ANGARITA', 'ind_estado' => 1),
			193 => array('cod_semir' => 754, 'desc_semir' => 'GALLEGOS', 'ind_estado' => 1),
			194 => array('cod_semir' => 753, 'desc_semir' => 'SL AUTOMOTRIZ', 'ind_estado' => 1),
			195 => array('cod_semir' => 752, 'desc_semir' => 'PRISMA', 'ind_estado' => 1),
			196 => array('cod_semir' => 750, 'desc_semir' => 'GRAYCO', 'ind_estado' => 1),
			197 => array('cod_semir' => 749, 'desc_semir' => 'NOVA', 'ind_estado' => 1),
			198 => array('cod_semir' => 748, 'desc_semir' => 'INDUSTRIAS V M SAS', 'ind_estado' => 1),
			199 => array('cod_semir' => 747, 'desc_semir' => 'INTERCOL S.A.', 'ind_estado' => 1),
			200 => array('cod_semir' => 745, 'desc_semir' => 'ROCKWELL', 'ind_estado' => 1),
			201 => array('cod_semir' => 744, 'desc_semir' => 'METALMECANICA MENDEZ ', 'ind_estado' => 1),
			202 => array('cod_semir' => 743, 'desc_semir' => 'IND. BULLDOG TRUCKS S.A. ', 'ind_estado' => 1),
			203 => array('cod_semir' => 742, 'desc_semir' => 'NELSON MANUFACTURING CO', 'ind_estado' => 1),
			204 => array('cod_semir' => 741, 'desc_semir' => 'C.E. SOTO CARROCERIAS', 'ind_estado' => 1),
			205 => array('cod_semir' => 740, 'desc_semir' => 'L&L LOGISTICA Y TRANS SAS', 'ind_estado' => 1),
			206 => array('cod_semir' => 739, 'desc_semir' => 'INVERSIONES CAMACHO ÑAÑEZ', 'ind_estado' => 1),
			207 => array('cod_semir' => 738, 'desc_semir' => 'ORIENTAL DE CHASIS', 'ind_estado' => 1),
			208 => array('cod_semir' => 737, 'desc_semir' => 'PRO-FORMANCE', 'ind_estado' => 1),
			209 => array('cod_semir' => 736, 'desc_semir' => 'LOW BOYS', 'ind_estado' => 1),
			210 => array('cod_semir' => 735, 'desc_semir' => 'CYTSA', 'ind_estado' => 1),
			211 => array('cod_semir' => 731, 'desc_semir' => 'CARROMACHOS Y MONTAJES TG', 'ind_estado' => 1),
			212 => array('cod_semir' => 730, 'desc_semir' => 'TALLERES E Y R', 'ind_estado' => 1),
			213 => array('cod_semir' => 729, 'desc_semir' => 'TALLER PERIYARA S.A.S', 'ind_estado' => 1),
			214 => array('cod_semir' => 728, 'desc_semir' => 'CILINDRAULICOS', 'ind_estado' => 1),
			215 => array('cod_semir' => 727, 'desc_semir' => 'TRAILERS Y CARR. ADRIANO', 'ind_estado' => 1),
			216 => array('cod_semir' => 726, 'desc_semir' => 'COE INGENIERIA S.A.S', 'ind_estado' => 1),
			217 => array('cod_semir' => 725, 'desc_semir' => 'C.H.E. INC. ', 'ind_estado' => 1),
			218 => array('cod_semir' => 724, 'desc_semir' => 'GREMCAR LTDA', 'ind_estado' => 1),
			219 => array('cod_semir' => 723, 'desc_semir' => 'CARROCERIAS ANDINA LTDA', 'ind_estado' => 1),
			220 => array('cod_semir' => 721, 'desc_semir' => 'REMOLQUES LEAL', 'ind_estado' => 1),
			221 => array('cod_semir' => 720, 'desc_semir' => 'CARROCERIAS SUPER LTDA.', 'ind_estado' => 1),
			222 => array('cod_semir' => 719, 'desc_semir' => 'TATSA', 'ind_estado' => 1),
			223 => array('cod_semir' => 718, 'desc_semir' => 'FCN', 'ind_estado' => 1),
			224 => array('cod_semir' => 717, 'desc_semir' => 'HYUNDAI', 'ind_estado' => 1),
			225 => array('cod_semir' => 715, 'desc_semir' => 'ING Y TRANS BOGOTA S.A.S.', 'ind_estado' => 1),
			226 => array('cod_semir' => 714, 'desc_semir' => 'SERVIMACH', 'ind_estado' => 1),
			227 => array('cod_semir' => 713, 'desc_semir' => 'SUPER TANQUES LTDA', 'ind_estado' => 1),
			228 => array('cod_semir' => 712, 'desc_semir' => 'INDUSTRIAS CARPIMOTORES ', 'ind_estado' => 1),
			229 => array('cod_semir' => 710, 'desc_semir' => 'CACIQUE', 'ind_estado' => 1),
			230 => array('cod_semir' => 706, 'desc_semir' => 'TRAILERS VALENCIA', 'ind_estado' => 1),
			231 => array('cod_semir' => 705, 'desc_semir' => 'AUTO BUSES DEL SUR IBAGUE', 'ind_estado' => 1),
			232 => array('cod_semir' => 704, 'desc_semir' => 'MUNDIAL TANQUES Y TRAILER', 'ind_estado' => 1),
			233 => array('cod_semir' => 703, 'desc_semir' => 'DITESA S.A.S', 'ind_estado' => 1),
			234 => array('cod_semir' => 702, 'desc_semir' => 'CPTDC', 'ind_estado' => 1),
			235 => array('cod_semir' => 700, 'desc_semir' => 'VERMEER', 'ind_estado' => 1),
			236 => array('cod_semir' => 699, 'desc_semir' => 'AUTOCHASIS-TRACK', 'ind_estado' => 1),
			237 => array('cod_semir' => 698, 'desc_semir' => 'EXA', 'ind_estado' => 1),
			238 => array('cod_semir' => 697, 'desc_semir' => 'TABECOL', 'ind_estado' => 1),
			239 => array('cod_semir' => 696, 'desc_semir' => 'PRATT', 'ind_estado' => 1),
			240 => array('cod_semir' => 691, 'desc_semir' => 'C&C ', 'ind_estado' => 1),
			241 => array('cod_semir' => 688, 'desc_semir' => 'CON-E-CO', 'ind_estado' => 1),
			242 => array('cod_semir' => 687, 'desc_semir' => 'BETONMAC', 'ind_estado' => 1),
			243 => array('cod_semir' => 686, 'desc_semir' => 'STIMCAR', 'ind_estado' => 1),
			244 => array('cod_semir' => 684, 'desc_semir' => 'HSENGINEERS & URBAN TOOLS', 'ind_estado' => 1),
			245 => array('cod_semir' => 683, 'desc_semir' => 'TRAYTEC', 'ind_estado' => 1),
			246 => array('cod_semir' => 682, 'desc_semir' => 'TALBERT REX', 'ind_estado' => 1),
			247 => array('cod_semir' => 681, 'desc_semir' => 'TRANSPORTES CTL ', 'ind_estado' => 1),
			248 => array('cod_semir' => 680, 'desc_semir' => 'WILHENEL', 'ind_estado' => 1),
			249 => array('cod_semir' => 679, 'desc_semir' => 'IND. MANCHESTER', 'ind_estado' => 1),
			250 => array('cod_semir' => 678, 'desc_semir' => 'CIMC', 'ind_estado' => 1),
			251 => array('cod_semir' => 677, 'desc_semir' => 'JUPITER', 'ind_estado' => 1),
			252 => array('cod_semir' => 674, 'desc_semir' => 'C.Y V.VENEZUELA', 'ind_estado' => 1),
			253 => array('cod_semir' => 673, 'desc_semir' => 'BENFOR', 'ind_estado' => 1),
			254 => array('cod_semir' => 672, 'desc_semir' => 'ING 2010 EU', 'ind_estado' => 1),
			255 => array('cod_semir' => 671, 'desc_semir' => 'TALLER COMESA', 'ind_estado' => 1),
			256 => array('cod_semir' => 670, 'desc_semir' => 'GUIVANE', 'ind_estado' => 1),
			257 => array('cod_semir' => 669, 'desc_semir' => 'HANDAN', 'ind_estado' => 1),
			258 => array('cod_semir' => 665, 'desc_semir' => 'FABRICACION NACIONAL', 'ind_estado' => 1),
			259 => array('cod_semir' => 664, 'desc_semir' => 'TRAILERS TANQUES Y VOLCOS', 'ind_estado' => 1),
			260 => array('cod_semir' => 663, 'desc_semir' => 'AUTOGRUA CONDOR LTDA', 'ind_estado' => 1),
			261 => array('cod_semir' => 662, 'desc_semir' => 'MONTAJES INDUSTRIALES LTD', 'ind_estado' => 1),
			262 => array('cod_semir' => 661, 'desc_semir' => 'EUROPESADOS', 'ind_estado' => 1),
			263 => array('cod_semir' => 660, 'desc_semir' => 'CIMMA INGENIEROS SAS', 'ind_estado' => 1),
			264 => array('cod_semir' => 659, 'desc_semir' => 'PENFA', 'ind_estado' => 1),
			265 => array('cod_semir' => 657, 'desc_semir' => 'NIETO', 'ind_estado' => 1),
			266 => array('cod_semir' => 655, 'desc_semir' => 'ROLLIGON', 'ind_estado' => 1),
			267 => array('cod_semir' => 653, 'desc_semir' => 'INNALTRACK', 'ind_estado' => 1),
			268 => array('cod_semir' => 652, 'desc_semir' => 'BUTLER REF. BT', 'ind_estado' => 1),
			269 => array('cod_semir' => 651, 'desc_semir' => 'FEELING REF. FS', 'ind_estado' => 1),
			270 => array('cod_semir' => 650, 'desc_semir' => 'CARRESAN', 'ind_estado' => 1),
			271 => array('cod_semir' => 649, 'desc_semir' => 'INDUCISTERNAS ', 'ind_estado' => 1),
			272 => array('cod_semir' => 648, 'desc_semir' => 'MER LTDA', 'ind_estado' => 1),
			273 => array('cod_semir' => 647, 'desc_semir' => 'INDUSTRIAS HERCAM CIA LTD', 'ind_estado' => 1),
			274 => array('cod_semir' => 646, 'desc_semir' => 'KAUFMAN TRAILERS', 'ind_estado' => 1),
			275 => array('cod_semir' => 645, 'desc_semir' => 'RAJA', 'ind_estado' => 1),
			276 => array('cod_semir' => 644, 'desc_semir' => 'INDUSTRIAS CHASSIS TRUCK', 'ind_estado' => 1),
			277 => array('cod_semir' => 643, 'desc_semir' => 'SCHEUERLE INTERCOMFI', 'ind_estado' => 1),
			278 => array('cod_semir' => 640, 'desc_semir' => 'COMETTO', 'ind_estado' => 1),
			279 => array('cod_semir' => 639, 'desc_semir' => 'TRAYMON', 'ind_estado' => 1),
			280 => array('cod_semir' => 637, 'desc_semir' => 'SCHLUMBERGER', 'ind_estado' => 1),
			281 => array('cod_semir' => 636, 'desc_semir' => 'LEAN', 'ind_estado' => 1),
			282 => array('cod_semir' => 631, 'desc_semir' => 'BBC INGENIEROS LIMITADA', 'ind_estado' => 1),
			283 => array('cod_semir' => 630, 'desc_semir' => 'AJAX', 'ind_estado' => 1),
			284 => array('cod_semir' => 625, 'desc_semir' => 'METALICAS DE LEBRIJA', 'ind_estado' => 1),
			285 => array('cod_semir' => 624, 'desc_semir' => 'D&H EQUIPMENT LTDA.', 'ind_estado' => 1),
			286 => array('cod_semir' => 623, 'desc_semir' => 'BRAE', 'ind_estado' => 1),
			287 => array('cod_semir' => 621, 'desc_semir' => 'IND. MAHERCA LTDA.', 'ind_estado' => 1),
			288 => array('cod_semir' => 620, 'desc_semir' => 'EAST', 'ind_estado' => 1),
			289 => array('cod_semir' => 619, 'desc_semir' => 'MANUFAC. CARR. ARIAS LTD ', 'ind_estado' => 1),
			290 => array('cod_semir' => 617, 'desc_semir' => 'FAYMONVILLE', 'ind_estado' => 1),
			291 => array('cod_semir' => 616, 'desc_semir' => 'L & R INGENIERIA', 'ind_estado' => 1),
			292 => array('cod_semir' => 615, 'desc_semir' => 'REINKE', 'ind_estado' => 1),
			293 => array('cod_semir' => 613, 'desc_semir' => 'EAGER BEAVER', 'ind_estado' => 1),
			294 => array('cod_semir' => 612, 'desc_semir' => 'INVERSIONES SETEMA LTDA', 'ind_estado' => 1),
			295 => array('cod_semir' => 611, 'desc_semir' => 'CINSA', 'ind_estado' => 1),
			296 => array('cod_semir' => 610, 'desc_semir' => 'WITZCO TRAILERS INC', 'ind_estado' => 1),
			297 => array('cod_semir' => 609, 'desc_semir' => 'FRONTINO', 'ind_estado' => 1),
			298 => array('cod_semir' => 608, 'desc_semir' => 'HERRERIA & CARROCERIAS', 'ind_estado' => 1),
			299 => array('cod_semir' => 607, 'desc_semir' => 'INTRAVAL', 'ind_estado' => 1),
			300 => array('cod_semir' => 606, 'desc_semir' => 'METALICAS CAMARGO CIA. LT', 'ind_estado' => 1),
			301 => array('cod_semir' => 604, 'desc_semir' => 'CENTRAL', 'ind_estado' => 1),
			302 => array('cod_semir' => 603, 'desc_semir' => 'UNIDOS', 'ind_estado' => 1),
			303 => array('cod_semir' => 602, 'desc_semir' => 'INDUANDINAS', 'ind_estado' => 1),
			304 => array('cod_semir' => 601, 'desc_semir' => 'INANCOL', 'ind_estado' => 1),
			305 => array('cod_semir' => 599, 'desc_semir' => 'IFM S.A.', 'ind_estado' => 1),
			306 => array('cod_semir' => 598, 'desc_semir' => 'CARR. GOMEZ GUERRERO LTDA', 'ind_estado' => 1),
			307 => array('cod_semir' => 597, 'desc_semir' => 'ICONCRET', 'ind_estado' => 1),
			308 => array('cod_semir' => 596, 'desc_semir' => 'INMETALPLAC', 'ind_estado' => 1),
			309 => array('cod_semir' => 595, 'desc_semir' => 'TALLERES INDUSTRIALES', 'ind_estado' => 1),
			310 => array('cod_semir' => 594, 'desc_semir' => 'TRAIL KING', 'ind_estado' => 1),
			311 => array('cod_semir' => 593, 'desc_semir' => 'GALILEO', 'ind_estado' => 1),
			312 => array('cod_semir' => 592, 'desc_semir' => 'ABL INTERNACIONAL', 'ind_estado' => 1),
			313 => array('cod_semir' => 591, 'desc_semir' => 'TYTAL', 'ind_estado' => 1),
			314 => array('cod_semir' => 590, 'desc_semir' => 'CONSIBE', 'ind_estado' => 1),
			315 => array('cod_semir' => 589, 'desc_semir' => 'ETM', 'ind_estado' => 1),
			316 => array('cod_semir' => 588, 'desc_semir' => 'POLAR TANKTRAILER,LLC', 'ind_estado' => 1),
			317 => array('cod_semir' => 587, 'desc_semir' => 'MARIA ESTELLA QUINTERO ES', 'ind_estado' => 1),
			318 => array('cod_semir' => 584, 'desc_semir' => 'QM EQUIPMENT', 'ind_estado' => 1),
			319 => array('cod_semir' => 581, 'desc_semir' => 'MONTEBRAS', 'ind_estado' => 1),
			320 => array('cod_semir' => 580, 'desc_semir' => 'FAB. NAL. DE REMOLQ. LTDA', 'ind_estado' => 1),
			321 => array('cod_semir' => 579, 'desc_semir' => 'PATAQUIVA ACHURY RUBEN D.', 'ind_estado' => 1),
			322 => array('cod_semir' => 578, 'desc_semir' => 'INDUSTRIAS LA 25 RG', 'ind_estado' => 1),
			323 => array('cod_semir' => 577, 'desc_semir' => 'TRIM', 'ind_estado' => 1),
			324 => array('cod_semir' => 576, 'desc_semir' => 'INARC', 'ind_estado' => 1),
			325 => array('cod_semir' => 575, 'desc_semir' => 'INDS. Y CARROCERIAS MAC  ', 'ind_estado' => 1),
			326 => array('cod_semir' => 574, 'desc_semir' => 'THOR', 'ind_estado' => 1),
			327 => array('cod_semir' => 573, 'desc_semir' => 'AGRO. SERV. RIOS', 'ind_estado' => 1),
			328 => array('cod_semir' => 572, 'desc_semir' => 'TECNITRAC', 'ind_estado' => 1),
			329 => array('cod_semir' => 571, 'desc_semir' => 'TALLERES BISSON LTDA', 'ind_estado' => 1),
			330 => array('cod_semir' => 570, 'desc_semir' => 'VULCAN TRAILER', 'ind_estado' => 1),
			331 => array('cod_semir' => 569, 'desc_semir' => 'TRAILERES Y TANQUES', 'ind_estado' => 1),
			332 => array('cod_semir' => 567, 'desc_semir' => 'TRAILKING INDUSTRIES', 'ind_estado' => 1),
			333 => array('cod_semir' => 566, 'desc_semir' => 'SICVE', 'ind_estado' => 1),
			334 => array('cod_semir' => 565, 'desc_semir' => 'QUINCAD', 'ind_estado' => 1),
			335 => array('cod_semir' => 564, 'desc_semir' => 'ARVARCAR', 'ind_estado' => 1),
			336 => array('cod_semir' => 563, 'desc_semir' => 'MONON', 'ind_estado' => 1),
			337 => array('cod_semir' => 562, 'desc_semir' => 'DOWNS', 'ind_estado' => 1),
			338 => array('cod_semir' => 561, 'desc_semir' => 'TRYMON', 'ind_estado' => 1),
			339 => array('cod_semir' => 560, 'desc_semir' => 'WUHAN', 'ind_estado' => 1),
			340 => array('cod_semir' => 559, 'desc_semir' => 'REPRESENT. Y MAQUINARIA', 'ind_estado' => 1),
			341 => array('cod_semir' => 558, 'desc_semir' => 'CUSTOM TRAYLER', 'ind_estado' => 1),
			342 => array('cod_semir' => 557, 'desc_semir' => 'SIDE DUMP', 'ind_estado' => 1),
			343 => array('cod_semir' => 556, 'desc_semir' => 'D.F.M.  E.U.', 'ind_estado' => 1),
			344 => array('cod_semir' => 555, 'desc_semir' => 'STOUGHTON', 'ind_estado' => 1),
			345 => array('cod_semir' => 554, 'desc_semir' => 'REMVEL LTDA.', 'ind_estado' => 1),
			346 => array('cod_semir' => 552, 'desc_semir' => 'ELEMENTOS METALICOS S.A.', 'ind_estado' => 1),
			347 => array('cod_semir' => 551, 'desc_semir' => 'PARCISA', 'ind_estado' => 1),
			348 => array('cod_semir' => 550, 'desc_semir' => 'IMPA', 'ind_estado' => 1),
			349 => array('cod_semir' => 549, 'desc_semir' => 'TRAILER CUCUTA LTDA', 'ind_estado' => 1),
			350 => array('cod_semir' => 548, 'desc_semir' => 'TRAILERS DE SANTANDER', 'ind_estado' => 1),
			351 => array('cod_semir' => 547, 'desc_semir' => 'PLASSTELLA', 'ind_estado' => 1),
			352 => array('cod_semir' => 546, 'desc_semir' => 'CARRESOTO', 'ind_estado' => 1),
			353 => array('cod_semir' => 545, 'desc_semir' => 'CAM ARIAS LTDA', 'ind_estado' => 1),
			354 => array('cod_semir' => 544, 'desc_semir' => 'CHART INC', 'ind_estado' => 1),
			355 => array('cod_semir' => 543, 'desc_semir' => 'FURGONES Y TRAILERS JB', 'ind_estado' => 1),
			356 => array('cod_semir' => 541, 'desc_semir' => 'VOLKAR LTDA', 'ind_estado' => 1),
			357 => array('cod_semir' => 540, 'desc_semir' => 'SERVI HIDRAULICAS', 'ind_estado' => 1),
			358 => array('cod_semir' => 539, 'desc_semir' => 'FERROGRUAS', 'ind_estado' => 1),
			359 => array('cod_semir' => 538, 'desc_semir' => 'INCASUR LTDA', 'ind_estado' => 1),
			360 => array('cod_semir' => 537, 'desc_semir' => 'IND. VAC E.U.', 'ind_estado' => 1),
			361 => array('cod_semir' => 536, 'desc_semir' => 'IND. METALICAS PATAQUIVA', 'ind_estado' => 1),
			362 => array('cod_semir' => 535, 'desc_semir' => 'EQUITANQ', 'ind_estado' => 1),
			363 => array('cod_semir' => 533, 'desc_semir' => 'LINDE CRYO AB', 'ind_estado' => 1),
			364 => array('cod_semir' => 532, 'desc_semir' => 'GESMET LTDA.', 'ind_estado' => 1),
			365 => array('cod_semir' => 531, 'desc_semir' => 'BULL TRAILER', 'ind_estado' => 1),
			366 => array('cod_semir' => 530, 'desc_semir' => 'VIKING', 'ind_estado' => 1),
			367 => array('cod_semir' => 529, 'desc_semir' => 'HEIL', 'ind_estado' => 1),
			368 => array('cod_semir' => 528, 'desc_semir' => 'TRAILERS MADRID', 'ind_estado' => 1),
			369 => array('cod_semir' => 527, 'desc_semir' => 'IND. NACIONAL S.A.', 'ind_estado' => 1),
			370 => array('cod_semir' => 526, 'desc_semir' => 'ANTRAILERS', 'ind_estado' => 1),
			371 => array('cod_semir' => 525, 'desc_semir' => 'HANKSUGI-TRAILERS', 'ind_estado' => 1),
			372 => array('cod_semir' => 524, 'desc_semir' => 'MAX-ATLAS', 'ind_estado' => 1),
			373 => array('cod_semir' => 523, 'desc_semir' => 'INTRAVA LTDA', 'ind_estado' => 1),
			374 => array('cod_semir' => 522, 'desc_semir' => 'AGRO-CARRETAS DEL FONCE', 'ind_estado' => 1),
			375 => array('cod_semir' => 521, 'desc_semir' => 'METRANSA LTDA.', 'ind_estado' => 1),
			376 => array('cod_semir' => 520, 'desc_semir' => 'PRODIMETAL', 'ind_estado' => 1),
			377 => array('cod_semir' => 519, 'desc_semir' => 'DOTERO LTDA', 'ind_estado' => 1),
			378 => array('cod_semir' => 518, 'desc_semir' => 'KM-0', 'ind_estado' => 1),
			379 => array('cod_semir' => 517, 'desc_semir' => 'IND. METALICAS PEÑA', 'ind_estado' => 1),
			380 => array('cod_semir' => 515, 'desc_semir' => 'TALLERES T. TANQUES', 'ind_estado' => 1),
			381 => array('cod_semir' => 514, 'desc_semir' => 'IND. NACIONAL', 'ind_estado' => 1),
			382 => array('cod_semir' => 513, 'desc_semir' => 'COONCREQUIPOS', 'ind_estado' => 1),
			383 => array('cod_semir' => 512, 'desc_semir' => 'LBM TRAILER EU.', 'ind_estado' => 1),
			384 => array('cod_semir' => 511, 'desc_semir' => 'METALICA', 'ind_estado' => 1),
			385 => array('cod_semir' => 510, 'desc_semir' => 'CONS VICMAHER', 'ind_estado' => 1),
			386 => array('cod_semir' => 509, 'desc_semir' => 'RUBICOM ', 'ind_estado' => 1),
			387 => array('cod_semir' => 508, 'desc_semir' => 'ANDERSON', 'ind_estado' => 1),
			388 => array('cod_semir' => 507, 'desc_semir' => 'MERTZ', 'ind_estado' => 1),
			389 => array('cod_semir' => 506, 'desc_semir' => 'F&M TRAILERS', 'ind_estado' => 1),
			390 => array('cod_semir' => 505, 'desc_semir' => 'BUFALO', 'ind_estado' => 1),
			391 => array('cod_semir' => 504, 'desc_semir' => 'AUTOMILENIO', 'ind_estado' => 1),
			392 => array('cod_semir' => 503, 'desc_semir' => 'ING. TECNICA NACIONAL', 'ind_estado' => 1),
			393 => array('cod_semir' => 502, 'desc_semir' => 'ALL WELD ENGINEERING', 'ind_estado' => 1),
			394 => array('cod_semir' => 500, 'desc_semir' => 'CAR TRAILERS TULUA CIA. L', 'ind_estado' => 1),
			395 => array('cod_semir' => 499, 'desc_semir' => 'VOLCOS UFF LTDA.', 'ind_estado' => 1),
			396 => array('cod_semir' => 498, 'desc_semir' => 'T. I. CHINO BERNA', 'ind_estado' => 1),
			397 => array('cod_semir' => 497, 'desc_semir' => 'INDOX', 'ind_estado' => 1),
			398 => array('cod_semir' => 496, 'desc_semir' => 'BJ SERVICES COMPANY S.A.', 'ind_estado' => 1),
			399 => array('cod_semir' => 495, 'desc_semir' => 'TALLERES AUTOGARROF', 'ind_estado' => 1),
			400 => array('cod_semir' => 494, 'desc_semir' => 'INTRAVAN LTDA', 'ind_estado' => 1),
			401 => array('cod_semir' => 493, 'desc_semir' => 'INDUESAN COLOMBIA LTDA', 'ind_estado' => 1),
			402 => array('cod_semir' => 492, 'desc_semir' => 'MULTINACIONAL TRANSPORTAD', 'ind_estado' => 1),
			403 => array('cod_semir' => 491, 'desc_semir' => 'CONALCAR', 'ind_estado' => 1),
			404 => array('cod_semir' => 490, 'desc_semir' => 'FPC Inc.', 'ind_estado' => 1),
			405 => array('cod_semir' => 489, 'desc_semir' => 'GUERRERO\'S TRAILERS LTDA', 'ind_estado' => 1),
			406 => array('cod_semir' => 488, 'desc_semir' => 'UTILITY', 'ind_estado' => 1),
			407 => array('cod_semir' => 487, 'desc_semir' => 'INTERTRAYLER LTDA', 'ind_estado' => 1),
			408 => array('cod_semir' => 486, 'desc_semir' => 'TRANSGAR LTDA', 'ind_estado' => 1),
			409 => array('cod_semir' => 485, 'desc_semir' => 'TRANSP. CHAMO', 'ind_estado' => 1),
			410 => array('cod_semir' => 484, 'desc_semir' => 'INDUWEST TRAILER', 'ind_estado' => 1),
			411 => array('cod_semir' => 483, 'desc_semir' => 'ITALMAQ LTDA', 'ind_estado' => 1),
			412 => array('cod_semir' => 482, 'desc_semir' => 'KALYN', 'ind_estado' => 1),
			413 => array('cod_semir' => 481, 'desc_semir' => 'VOLCOS Y REMOL DEL CARVAJ', 'ind_estado' => 1),
			414 => array('cod_semir' => 479, 'desc_semir' => 'TRAYLERS Y VOLCOS DE SURA', 'ind_estado' => 1),
			415 => array('cod_semir' => 478, 'desc_semir' => 'CARROCERIAS  JAMIOY', 'ind_estado' => 1),
			416 => array('cod_semir' => 477, 'desc_semir' => 'SERVITRUCK', 'ind_estado' => 1),
			417 => array('cod_semir' => 476, 'desc_semir' => 'TALLERES MILTON QUINTERO', 'ind_estado' => 1),
			418 => array('cod_semir' => 475, 'desc_semir' => 'INDUVOLCOS ', 'ind_estado' => 1),
			419 => array('cod_semir' => 474, 'desc_semir' => 'TRAILERS DE ANTIOQUIA', 'ind_estado' => 1),
			420 => array('cod_semir' => 473, 'desc_semir' => 'TFM', 'ind_estado' => 1),
			421 => array('cod_semir' => 471, 'desc_semir' => 'INTLL-TORRES', 'ind_estado' => 1),
			422 => array('cod_semir' => 470, 'desc_semir' => 'COLOMCARGA S.A.', 'ind_estado' => 1),
			423 => array('cod_semir' => 469, 'desc_semir' => 'EL ABARCO', 'ind_estado' => 1),
			424 => array('cod_semir' => 468, 'desc_semir' => 'MUMA', 'ind_estado' => 1),
			425 => array('cod_semir' => 467, 'desc_semir' => 'CARROCERIAS CANAFI', 'ind_estado' => 1),
			426 => array('cod_semir' => 466, 'desc_semir' => 'MARTINMACHIN', 'ind_estado' => 1),
			427 => array('cod_semir' => 465, 'desc_semir' => 'TALLER CARTRAILER', 'ind_estado' => 1),
			428 => array('cod_semir' => 464, 'desc_semir' => 'MONTERREY', 'ind_estado' => 1),
			429 => array('cod_semir' => 463, 'desc_semir' => 'FABRICA CGC', 'ind_estado' => 1),
			430 => array('cod_semir' => 462, 'desc_semir' => 'TECNITRAC\'S', 'ind_estado' => 1),
			431 => array('cod_semir' => 461, 'desc_semir' => 'TRACTO CAR REMOLQUES', 'ind_estado' => 1),
			432 => array('cod_semir' => 460, 'desc_semir' => 'FERRELAMINAS MOSQUERA LTD', 'ind_estado' => 1),
			433 => array('cod_semir' => 459, 'desc_semir' => 'JAGUER', 'ind_estado' => 1),
			434 => array('cod_semir' => 458, 'desc_semir' => 'CANACOL LTDA. ', 'ind_estado' => 1),
			435 => array('cod_semir' => 457, 'desc_semir' => 'TRANSAP S.A.', 'ind_estado' => 1),
			436 => array('cod_semir' => 456, 'desc_semir' => 'K.Y.INGENIERIA', 'ind_estado' => 1),
			437 => array('cod_semir' => 455, 'desc_semir' => 'ARTICULADOS DE COLOMBIA', 'ind_estado' => 1),
			438 => array('cod_semir' => 454, 'desc_semir' => 'INCOLT.SAMACA', 'ind_estado' => 1),
			439 => array('cod_semir' => 453, 'desc_semir' => 'TRANS. TRIANA ISAZA LTDA', 'ind_estado' => 1),
			440 => array('cod_semir' => 452, 'desc_semir' => 'RETESA', 'ind_estado' => 1),
			441 => array('cod_semir' => 451, 'desc_semir' => 'CRYOGENIC VESSEL ALTERNAT', 'ind_estado' => 1),
			442 => array('cod_semir' => 450, 'desc_semir' => 'TRAILERS HERCULES', 'ind_estado' => 1),
			443 => array('cod_semir' => 449, 'desc_semir' => 'ICR LTDA', 'ind_estado' => 1),
			444 => array('cod_semir' => 448, 'desc_semir' => 'CIDIT LTDA', 'ind_estado' => 1),
			445 => array('cod_semir' => 447, 'desc_semir' => 'AFC TRAILERS', 'ind_estado' => 1),
			446 => array('cod_semir' => 446, 'desc_semir' => 'ALEGRIA ACTIVITY', 'ind_estado' => 1),
			447 => array('cod_semir' => 445, 'desc_semir' => 'ORION', 'ind_estado' => 1),
			448 => array('cod_semir' => 444, 'desc_semir' => 'TALLERES GUERRERO ', 'ind_estado' => 1),
			449 => array('cod_semir' => 443, 'desc_semir' => 'INDUCARIBE', 'ind_estado' => 1),
			450 => array('cod_semir' => 442, 'desc_semir' => 'LAFE SECURITY', 'ind_estado' => 1),
			451 => array('cod_semir' => 441, 'desc_semir' => 'CARROCERIAS JAGUER', 'ind_estado' => 1),
			452 => array('cod_semir' => 440, 'desc_semir' => 'METALMECANO S.A.', 'ind_estado' => 1),
			453 => array('cod_semir' => 439, 'desc_semir' => 'AMERICAN TRAYLER', 'ind_estado' => 1),
			454 => array('cod_semir' => 438, 'desc_semir' => 'COLREMOLQUES CALI', 'ind_estado' => 1),
			455 => array('cod_semir' => 437, 'desc_semir' => 'GES. INTE. MANTE.', 'ind_estado' => 1),
			456 => array('cod_semir' => 436, 'desc_semir' => 'ASPRO', 'ind_estado' => 1),
			457 => array('cod_semir' => 435, 'desc_semir' => 'IND. METALICAS SIGMA LTDA', 'ind_estado' => 1),
			458 => array('cod_semir' => 434, 'desc_semir' => 'CARROCERIAS AMAGA', 'ind_estado' => 1),
			459 => array('cod_semir' => 433, 'desc_semir' => 'ITANREM', 'ind_estado' => 1),
			460 => array('cod_semir' => 432, 'desc_semir' => 'INCALLES COLOMBIA', 'ind_estado' => 1),
			461 => array('cod_semir' => 431, 'desc_semir' => 'MCN EXPORTS', 'ind_estado' => 1),
			462 => array('cod_semir' => 430, 'desc_semir' => 'INDUSTRIAS OXEN', 'ind_estado' => 1),
			463 => array('cod_semir' => 429, 'desc_semir' => 'INTERTRAILERS', 'ind_estado' => 1),
			464 => array('cod_semir' => 428, 'desc_semir' => 'INDUSTRIAS ACEVEDO Y COMP', 'ind_estado' => 1),
			465 => array('cod_semir' => 427, 'desc_semir' => 'INDUSTRIAS TECNIMAR MORAL', 'ind_estado' => 1),
			466 => array('cod_semir' => 426, 'desc_semir' => 'VALORCON S.A.', 'ind_estado' => 1),
			467 => array('cod_semir' => 425, 'desc_semir' => 'MANETRA S.A.', 'ind_estado' => 1),
			468 => array('cod_semir' => 424, 'desc_semir' => 'TRANS-AUTOS VIRT', 'ind_estado' => 1),
			469 => array('cod_semir' => 423, 'desc_semir' => 'CARROCERIA JAMIOY', 'ind_estado' => 1),
			470 => array('cod_semir' => 422, 'desc_semir' => 'IND MET CEPEDA', 'ind_estado' => 1),
			471 => array('cod_semir' => 421, 'desc_semir' => 'INCOLTRAILERS LTDA', 'ind_estado' => 1),
			472 => array('cod_semir' => 420, 'desc_semir' => 'MUNDIAL DE MANUFACTURAS', 'ind_estado' => 1),
			473 => array('cod_semir' => 419, 'desc_semir' => 'INOXMEC', 'ind_estado' => 1),
			474 => array('cod_semir' => 418, 'desc_semir' => 'REMOLQUES INTRAHILLERS ', 'ind_estado' => 1),
			475 => array('cod_semir' => 417, 'desc_semir' => 'INDUSTRIAS BOYACA', 'ind_estado' => 1),
			476 => array('cod_semir' => 416, 'desc_semir' => 'APONCAR ', 'ind_estado' => 1),
			477 => array('cod_semir' => 415, 'desc_semir' => 'EAGLE TRUCK TRAILERS LTDA', 'ind_estado' => 1),
			478 => array('cod_semir' => 414, 'desc_semir' => 'TALLER TFS', 'ind_estado' => 1),
			479 => array('cod_semir' => 412, 'desc_semir' => 'ALQUISER', 'ind_estado' => 1),
			480 => array('cod_semir' => 411, 'desc_semir' => 'TRAILER\'S BOHORQUEZ', 'ind_estado' => 1),
			481 => array('cod_semir' => 410, 'desc_semir' => 'RHINO', 'ind_estado' => 1),
			482 => array('cod_semir' => 409, 'desc_semir' => 'TALLER HERNANDEZ NICOLAS', 'ind_estado' => 1),
			483 => array('cod_semir' => 408, 'desc_semir' => 'DICOL LTDA', 'ind_estado' => 1),
			484 => array('cod_semir' => 407, 'desc_semir' => 'MZCIA LTDA.', 'ind_estado' => 1),
			485 => array('cod_semir' => 406, 'desc_semir' => 'TALLER EL TRAILERO', 'ind_estado' => 1),
			486 => array('cod_semir' => 405, 'desc_semir' => 'S.G INGENIERIA', 'ind_estado' => 1),
			487 => array('cod_semir' => 404, 'desc_semir' => 'INDUCAM J.C.', 'ind_estado' => 1),
			488 => array('cod_semir' => 403, 'desc_semir' => 'AGROINDU.', 'ind_estado' => 1),
			489 => array('cod_semir' => 402, 'desc_semir' => 'TRAILERS\'MR', 'ind_estado' => 1),
			490 => array('cod_semir' => 401, 'desc_semir' => 'LA PLAYA', 'ind_estado' => 1),
			491 => array('cod_semir' => 400, 'desc_semir' => 'CARROCERIAS ALCAR', 'ind_estado' => 1),
			492 => array('cod_semir' => 398, 'desc_semir' => 'THEURER', 'ind_estado' => 1),
			493 => array('cod_semir' => 397, 'desc_semir' => 'ALLIED', 'ind_estado' => 1),
			494 => array('cod_semir' => 396, 'desc_semir' => 'GINDY', 'ind_estado' => 1),
			495 => array('cod_semir' => 395, 'desc_semir' => 'BERTOLINI', 'ind_estado' => 1),
			496 => array('cod_semir' => 394, 'desc_semir' => 'REPRESENTAC INDUST. ORION', 'ind_estado' => 1),
			497 => array('cod_semir' => 393, 'desc_semir' => 'BISON TRUCKS', 'ind_estado' => 1),
			498 => array('cod_semir' => 392, 'desc_semir' => 'WELLER', 'ind_estado' => 1),
			499 => array('cod_semir' => 391, 'desc_semir' => 'INDUSTRIAS INTRACAR', 'ind_estado' => 1),
			500 => array('cod_semir' => 390, 'desc_semir' => 'CLINICA HIDRAULICA LTDA', 'ind_estado' => 1),
			501 => array('cod_semir' => 389, 'desc_semir' => 'CARROCERIAS MORENO', 'ind_estado' => 1),
			502 => array('cod_semir' => 388, 'desc_semir' => 'HECHIZA', 'ind_estado' => 1),
			503 => array('cod_semir' => 387, 'desc_semir' => 'GUERCAR', 'ind_estado' => 1),
			504 => array('cod_semir' => 386, 'desc_semir' => 'FRANCOCOLOMBIANA', 'ind_estado' => 1),
			505 => array('cod_semir' => 385, 'desc_semir' => 'GREAT TRUCK', 'ind_estado' => 1),
			506 => array('cod_semir' => 384, 'desc_semir' => 'TRAILERS SILVER', 'ind_estado' => 1),
			507 => array('cod_semir' => 383, 'desc_semir' => 'FAVECZA', 'ind_estado' => 1),
			508 => array('cod_semir' => 382, 'desc_semir' => 'POTRAIL', 'ind_estado' => 1),
			509 => array('cod_semir' => 381, 'desc_semir' => 'WEATHERFORD', 'ind_estado' => 1),
			510 => array('cod_semir' => 380, 'desc_semir' => 'ELIACERO S.A.S', 'ind_estado' => 1),
			511 => array('cod_semir' => 379, 'desc_semir' => 'TALLER PEDRO URREGO ', 'ind_estado' => 1),
			512 => array('cod_semir' => 378, 'desc_semir' => 'MAREN FOX', 'ind_estado' => 1),
			513 => array('cod_semir' => 377, 'desc_semir' => 'INDUSTRIAS MAHERCA', 'ind_estado' => 1),
			514 => array('cod_semir' => 376, 'desc_semir' => 'INTRAILER LTDA', 'ind_estado' => 1),
			515 => array('cod_semir' => 375, 'desc_semir' => 'TRAYVOCOL', 'ind_estado' => 1),
			516 => array('cod_semir' => 373, 'desc_semir' => 'REMOLCABIM', 'ind_estado' => 1),
			517 => array('cod_semir' => 372, 'desc_semir' => 'WITZCO CHALLENGER RG50 ', 'ind_estado' => 1),
			518 => array('cod_semir' => 371, 'desc_semir' => 'VERING INGENIEROS ASOCIAD', 'ind_estado' => 1),
			519 => array('cod_semir' => 370, 'desc_semir' => 'FMI', 'ind_estado' => 1),
			520 => array('cod_semir' => 369, 'desc_semir' => 'MORA', 'ind_estado' => 1),
			521 => array('cod_semir' => 368, 'desc_semir' => 'ISMACHA', 'ind_estado' => 1),
			522 => array('cod_semir' => 367, 'desc_semir' => 'FELO', 'ind_estado' => 1),
			523 => array('cod_semir' => 366, 'desc_semir' => 'NATIONAL PRIETO', 'ind_estado' => 1),
			524 => array('cod_semir' => 365, 'desc_semir' => 'CARROCERIAS PRISMA', 'ind_estado' => 1),
			525 => array('cod_semir' => 364, 'desc_semir' => 'T&T', 'ind_estado' => 1),
			526 => array('cod_semir' => 363, 'desc_semir' => 'LOHR', 'ind_estado' => 1),
			527 => array('cod_semir' => 362, 'desc_semir' => 'BELTRAILERS', 'ind_estado' => 1),
			528 => array('cod_semir' => 361, 'desc_semir' => 'TALLERES PACHON', 'ind_estado' => 1),
			529 => array('cod_semir' => 360, 'desc_semir' => 'INDUCAPI', 'ind_estado' => 1),
			530 => array('cod_semir' => 358, 'desc_semir' => 'SIERRA INTL', 'ind_estado' => 1),
			531 => array('cod_semir' => 357, 'desc_semir' => 'ECOIL SERVICES LTDA.', 'ind_estado' => 1),
			532 => array('cod_semir' => 356, 'desc_semir' => 'IND.METALMEC.MORENO S.A.S', 'ind_estado' => 1),
			533 => array('cod_semir' => 355, 'desc_semir' => 'TRAILERS FEGAM', 'ind_estado' => 1),
			534 => array('cod_semir' => 354, 'desc_semir' => 'E.F.A.', 'ind_estado' => 1),
			535 => array('cod_semir' => 353, 'desc_semir' => 'TALLERES TRACKMAN', 'ind_estado' => 1),
			536 => array('cod_semir' => 352, 'desc_semir' => 'ANALYTYCA', 'ind_estado' => 1),
			537 => array('cod_semir' => 351, 'desc_semir' => 'CIBER', 'ind_estado' => 1),
			538 => array('cod_semir' => 350, 'desc_semir' => 'FULL TRAILER', 'ind_estado' => 1),
			539 => array('cod_semir' => 349, 'desc_semir' => 'GERMAR GMG', 'ind_estado' => 1),
			540 => array('cod_semir' => 348, 'desc_semir' => 'ISBACAR', 'ind_estado' => 1),
			541 => array('cod_semir' => 347, 'desc_semir' => 'TODO TRAILERS', 'ind_estado' => 1),
			542 => array('cod_semir' => 346, 'desc_semir' => 'TALLER OVEL', 'ind_estado' => 1),
			543 => array('cod_semir' => 345, 'desc_semir' => 'TRAILERSANDER', 'ind_estado' => 1),
			544 => array('cod_semir' => 344, 'desc_semir' => 'IC&M LTDA', 'ind_estado' => 1),
			545 => array('cod_semir' => 343, 'desc_semir' => 'GRAN ANDINO', 'ind_estado' => 1),
			546 => array('cod_semir' => 342, 'desc_semir' => 'MERRITT', 'ind_estado' => 1),
			547 => array('cod_semir' => 341, 'desc_semir' => 'TRAYCOL E.U.', 'ind_estado' => 1),
			548 => array('cod_semir' => 340, 'desc_semir' => 'CONSTRUTRAILER', 'ind_estado' => 1),
			549 => array('cod_semir' => 339, 'desc_semir' => 'ISOLDA', 'ind_estado' => 1),
			550 => array('cod_semir' => 338, 'desc_semir' => 'TALLERES CESPEDES', 'ind_estado' => 1),
			551 => array('cod_semir' => 337, 'desc_semir' => 'HYSTER', 'ind_estado' => 1),
			552 => array('cod_semir' => 336, 'desc_semir' => 'TALLER BELPER', 'ind_estado' => 1),
			553 => array('cod_semir' => 335, 'desc_semir' => 'INCOLTT JC', 'ind_estado' => 1),
			554 => array('cod_semir' => 334, 'desc_semir' => 'REMOLDANNY', 'ind_estado' => 1),
			555 => array('cod_semir' => 333, 'desc_semir' => 'SURAMERICANA', 'ind_estado' => 1),
			556 => array('cod_semir' => 332, 'desc_semir' => 'INCAS', 'ind_estado' => 1),
			557 => array('cod_semir' => 331, 'desc_semir' => 'INMETALCAR', 'ind_estado' => 1),
			558 => array('cod_semir' => 330, 'desc_semir' => 'GEMUZA', 'ind_estado' => 1),
			559 => array('cod_semir' => 329, 'desc_semir' => 'TECNOTRAILERS', 'ind_estado' => 1),
			560 => array('cod_semir' => 328, 'desc_semir' => 'STEEL TRAILERS', 'ind_estado' => 1),
			561 => array('cod_semir' => 327, 'desc_semir' => 'SERVITRACK', 'ind_estado' => 1),
			562 => array('cod_semir' => 326, 'desc_semir' => 'TECNI-SANDER', 'ind_estado' => 1),
			563 => array('cod_semir' => 325, 'desc_semir' => 'I. G. S. A.', 'ind_estado' => 1),
			564 => array('cod_semir' => 324, 'desc_semir' => 'EQUITRAILER', 'ind_estado' => 1),
			565 => array('cod_semir' => 323, 'desc_semir' => 'TINKEN', 'ind_estado' => 1),
			566 => array('cod_semir' => 322, 'desc_semir' => 'GRWR - PRONT', 'ind_estado' => 1),
			567 => array('cod_semir' => 321, 'desc_semir' => 'FACCHINI', 'ind_estado' => 1),
			568 => array('cod_semir' => 320, 'desc_semir' => 'PASCUAL', 'ind_estado' => 1),
			569 => array('cod_semir' => 319, 'desc_semir' => 'KING', 'ind_estado' => 1),
			570 => array('cod_semir' => 318, 'desc_semir' => 'SILAR', 'ind_estado' => 1),
			571 => array('cod_semir' => 317, 'desc_semir' => 'ARASANZ', 'ind_estado' => 1),
			572 => array('cod_semir' => 316, 'desc_semir' => 'TRAVOR', 'ind_estado' => 1),
			573 => array('cod_semir' => 315, 'desc_semir' => 'KIDRON', 'ind_estado' => 1),
			574 => array('cod_semir' => 314, 'desc_semir' => 'CAR CAMACHO', 'ind_estado' => 1),
			575 => array('cod_semir' => 313, 'desc_semir' => 'DYSON', 'ind_estado' => 1),
			576 => array('cod_semir' => 312, 'desc_semir' => 'AZTEC', 'ind_estado' => 1),
			577 => array('cod_semir' => 311, 'desc_semir' => 'IND EL BARCO', 'ind_estado' => 1),
			578 => array('cod_semir' => 310, 'desc_semir' => 'A & R TANQUES INGENIER', 'ind_estado' => 1),
			579 => array('cod_semir' => 309, 'desc_semir' => 'WIZTICO CHALLENGER TRAILE', 'ind_estado' => 1),
			580 => array('cod_semir' => 308, 'desc_semir' => 'TESCARGA', 'ind_estado' => 1),
			581 => array('cod_semir' => 307, 'desc_semir' => 'FORERO', 'ind_estado' => 1),
			582 => array('cod_semir' => 306, 'desc_semir' => 'THERMOKING', 'ind_estado' => 1),
			583 => array('cod_semir' => 305, 'desc_semir' => 'FONCAR', 'ind_estado' => 1),
			584 => array('cod_semir' => 304, 'desc_semir' => 'CHOICE TRAILERS', 'ind_estado' => 1),
			585 => array('cod_semir' => 302, 'desc_semir' => 'UNLIMITED', 'ind_estado' => 1),
			586 => array('cod_semir' => 300, 'desc_semir' => 'TALMER', 'ind_estado' => 1),
			587 => array('cod_semir' => 299, 'desc_semir' => 'TAMER', 'ind_estado' => 1),
			588 => array('cod_semir' => 297, 'desc_semir' => 'TALLERES BUCARAMANGA', 'ind_estado' => 1),
			589 => array('cod_semir' => 295, 'desc_semir' => 'REPAC', 'ind_estado' => 1),
			590 => array('cod_semir' => 294, 'desc_semir' => 'REMOLQUES PJH', 'ind_estado' => 1),
			591 => array('cod_semir' => 292, 'desc_semir' => 'NECARTE', 'ind_estado' => 1),
			592 => array('cod_semir' => 291, 'desc_semir' => 'METALFURGONES', 'ind_estado' => 1),
			593 => array('cod_semir' => 290, 'desc_semir' => 'METALAGRO', 'ind_estado' => 1),
			594 => array('cod_semir' => 289, 'desc_semir' => 'MANAURE', 'ind_estado' => 1),
			595 => array('cod_semir' => 287, 'desc_semir' => 'LEOPOLDINO', 'ind_estado' => 1),
			596 => array('cod_semir' => 286, 'desc_semir' => 'INTERCONSUL', 'ind_estado' => 1),
			597 => array('cod_semir' => 285, 'desc_semir' => 'INGELMET', 'ind_estado' => 1),
			598 => array('cod_semir' => 284, 'desc_semir' => 'IND METALMECANICAS RUEDA', 'ind_estado' => 1),
			599 => array('cod_semir' => 283, 'desc_semir' => 'IND JULCAR', 'ind_estado' => 1),
			600 => array('cod_semir' => 281, 'desc_semir' => 'FIGLAS', 'ind_estado' => 1),
			601 => array('cod_semir' => 280, 'desc_semir' => 'FATECOLCAR', 'ind_estado' => 1),
			602 => array('cod_semir' => 279, 'desc_semir' => 'FABRIMOTEC', 'ind_estado' => 1),
			603 => array('cod_semir' => 278, 'desc_semir' => 'ESTRUMETAL', 'ind_estado' => 1),
			604 => array('cod_semir' => 277, 'desc_semir' => 'DORSEY', 'ind_estado' => 1),
			605 => array('cod_semir' => 276, 'desc_semir' => 'DOTERO TRILER', 'ind_estado' => 1),
			606 => array('cod_semir' => 275, 'desc_semir' => 'DIDEL', 'ind_estado' => 1),
			607 => array('cod_semir' => 274, 'desc_semir' => 'COOPELLAND', 'ind_estado' => 1),
			608 => array('cod_semir' => 273, 'desc_semir' => 'COMETAL', 'ind_estado' => 1),
			609 => array('cod_semir' => 272, 'desc_semir' => 'CARDI', 'ind_estado' => 1),
			610 => array('cod_semir' => 270, 'desc_semir' => 'BAUJAHN', 'ind_estado' => 1),
			611 => array('cod_semir' => 269, 'desc_semir' => '4 STAR', 'ind_estado' => 1),
			612 => array('cod_semir' => 268, 'desc_semir' => 'TRAILER\'S SANTANDER', 'ind_estado' => 1),
			613 => array('cod_semir' => 267, 'desc_semir' => 'ICEBERG', 'ind_estado' => 1),
			614 => array('cod_semir' => 266, 'desc_semir' => 'H.B.', 'ind_estado' => 1),
			615 => array('cod_semir' => 265, 'desc_semir' => 'STRICK', 'ind_estado' => 1),
			616 => array('cod_semir' => 264, 'desc_semir' => 'ROGERS', 'ind_estado' => 1),
			617 => array('cod_semir' => 263, 'desc_semir' => 'MACKOS', 'ind_estado' => 1),
			618 => array('cod_semir' => 262, 'desc_semir' => 'INCOLS', 'ind_estado' => 1),
			619 => array('cod_semir' => 261, 'desc_semir' => 'TECNITRAILERS', 'ind_estado' => 1),
			620 => array('cod_semir' => 260, 'desc_semir' => 'TALLERES PERILLA', 'ind_estado' => 1),
			621 => array('cod_semir' => 259, 'desc_semir' => 'TALLER INDU. PANAMERICANO', 'ind_estado' => 1),
			622 => array('cod_semir' => 258, 'desc_semir' => 'TALLERES INDU. DIAZ', 'ind_estado' => 1),
			623 => array('cod_semir' => 257, 'desc_semir' => 'SOCIEDAD TRACTEC', 'ind_estado' => 1),
			624 => array('cod_semir' => 256, 'desc_semir' => 'SERINCO', 'ind_estado' => 1),
			625 => array('cod_semir' => 255, 'desc_semir' => 'SANTANDEREANA DE CARROC', 'ind_estado' => 1),
			626 => array('cod_semir' => 254, 'desc_semir' => 'REPARTRAILERSVAN', 'ind_estado' => 1),
			627 => array('cod_semir' => 253, 'desc_semir' => 'RAUL CASTRO B.', 'ind_estado' => 1),
			628 => array('cod_semir' => 252, 'desc_semir' => 'RA NESTOR GENTIL CASTRO', 'ind_estado' => 1),
			629 => array('cod_semir' => 249, 'desc_semir' => 'LIDDELL', 'ind_estado' => 1),
			630 => array('cod_semir' => 248, 'desc_semir' => 'IVICO', 'ind_estado' => 1),
			631 => array('cod_semir' => 247, 'desc_semir' => 'ITC', 'ind_estado' => 1),
			632 => array('cod_semir' => 246, 'desc_semir' => 'INDUTRAYLER', 'ind_estado' => 1),
			633 => array('cod_semir' => 244, 'desc_semir' => 'IMPORSAN', 'ind_estado' => 1),
			634 => array('cod_semir' => 242, 'desc_semir' => 'HERCULES', 'ind_estado' => 1),
			635 => array('cod_semir' => 238, 'desc_semir' => 'GERPLAP', 'ind_estado' => 1),
			636 => array('cod_semir' => 235, 'desc_semir' => 'FALCON', 'ind_estado' => 1),
			637 => array('cod_semir' => 234, 'desc_semir' => 'KPI-JCI', 'ind_estado' => 1),
			638 => array('cod_semir' => 233, 'desc_semir' => 'DUNHAM', 'ind_estado' => 1),
			639 => array('cod_semir' => 232, 'desc_semir' => 'CRYOGAS BARBOSA', 'ind_estado' => 1),
			640 => array('cod_semir' => 230, 'desc_semir' => 'COMERCIAL DE CARROCERIAS', 'ind_estado' => 1),
			641 => array('cod_semir' => 228, 'desc_semir' => 'CHAMA', 'ind_estado' => 1),
			642 => array('cod_semir' => 226, 'desc_semir' => 'CARROCERIAS ANTIOQUIA', 'ind_estado' => 1),
			643 => array('cod_semir' => 225, 'desc_semir' => 'BPMH OLIMPIX', 'ind_estado' => 1),
			644 => array('cod_semir' => 224, 'desc_semir' => 'ALCON', 'ind_estado' => 1),
			645 => array('cod_semir' => 223, 'desc_semir' => 'ADVANCES SYSTEMAS', 'ind_estado' => 1),
			646 => array('cod_semir' => 222, 'desc_semir' => 'TRAILECOL', 'ind_estado' => 1),
			647 => array('cod_semir' => 221, 'desc_semir' => 'SIETE AMIGOS', 'ind_estado' => 1),
			648 => array('cod_semir' => 220, 'desc_semir' => 'RAFAEL ESCOBAR CONTRERAS', 'ind_estado' => 1),
			649 => array('cod_semir' => 219, 'desc_semir' => 'TALLER RAUL CASTRO', 'ind_estado' => 1),
			650 => array('cod_semir' => 218, 'desc_semir' => 'INDUTER AGRICOLA', 'ind_estado' => 1),
			651 => array('cod_semir' => 217, 'desc_semir' => 'CARGO VAN', 'ind_estado' => 1),
			652 => array('cod_semir' => 216, 'desc_semir' => 'WELLS CARGO', 'ind_estado' => 1),
			653 => array('cod_semir' => 215, 'desc_semir' => 'HAMMAR', 'ind_estado' => 1),
			654 => array('cod_semir' => 214, 'desc_semir' => 'DISMET', 'ind_estado' => 1),
			655 => array('cod_semir' => 213, 'desc_semir' => 'METALMECANICAS P.B.A.', 'ind_estado' => 1),
			656 => array('cod_semir' => 212, 'desc_semir' => 'TROPICAL', 'ind_estado' => 1),
			657 => array('cod_semir' => 211, 'desc_semir' => 'CARROCERIAS MODERNA', 'ind_estado' => 1),
			658 => array('cod_semir' => 210, 'desc_semir' => 'SCHLUMBERGER DOWELL', 'ind_estado' => 1),
			659 => array('cod_semir' => 209, 'desc_semir' => 'TELVAL', 'ind_estado' => 1),
			660 => array('cod_semir' => 208, 'desc_semir' => 'RANDON', 'ind_estado' => 1),
			661 => array('cod_semir' => 207, 'desc_semir' => 'GREPER', 'ind_estado' => 1),
			662 => array('cod_semir' => 206, 'desc_semir' => 'ORLTRAILER', 'ind_estado' => 1),
			663 => array('cod_semir' => 205, 'desc_semir' => 'NORTRAILERS', 'ind_estado' => 1),
			664 => array('cod_semir' => 204, 'desc_semir' => 'TRANSTRAILER', 'ind_estado' => 1),
			665 => array('cod_semir' => 203, 'desc_semir' => 'IND. TMQ', 'ind_estado' => 1),
			666 => array('cod_semir' => 202, 'desc_semir' => 'FABRIMEC', 'ind_estado' => 1),
			667 => array('cod_semir' => 201, 'desc_semir' => 'PANAMERICANA', 'ind_estado' => 1),
			668 => array('cod_semir' => 200, 'desc_semir' => 'RODRIREMOLQUES', 'ind_estado' => 1),
			669 => array('cod_semir' => 199, 'desc_semir' => 'TANCOLSA', 'ind_estado' => 1),
			670 => array('cod_semir' => 198, 'desc_semir' => 'TALLERES ESPINEL', 'ind_estado' => 1),
			671 => array('cod_semir' => 197, 'desc_semir' => 'INMETALACS', 'ind_estado' => 1),
			672 => array('cod_semir' => 196, 'desc_semir' => 'MACTRAILERS', 'ind_estado' => 1),
			673 => array('cod_semir' => 195, 'desc_semir' => 'TECNITANQUES', 'ind_estado' => 1),
			674 => array('cod_semir' => 193, 'desc_semir' => 'HI', 'ind_estado' => 1),
			675 => array('cod_semir' => 191, 'desc_semir' => 'EDASA INFRA', 'ind_estado' => 1),
			676 => array('cod_semir' => 190, 'desc_semir' => 'MULTITRAILERS', 'ind_estado' => 1),
			677 => array('cod_semir' => 189, 'desc_semir' => 'COLTRAILER', 'ind_estado' => 1),
			678 => array('cod_semir' => 188, 'desc_semir' => 'IME', 'ind_estado' => 1),
			679 => array('cod_semir' => 187, 'desc_semir' => 'TMM', 'ind_estado' => 1),
			680 => array('cod_semir' => 186, 'desc_semir' => 'METALTECNICAS', 'ind_estado' => 1),
			681 => array('cod_semir' => 185, 'desc_semir' => 'PALOMINO', 'ind_estado' => 1),
			682 => array('cod_semir' => 184, 'desc_semir' => 'TRANSLICOL', 'ind_estado' => 1),
			683 => array('cod_semir' => 183, 'desc_semir' => 'FAMERS', 'ind_estado' => 1),
			684 => array('cod_semir' => 182, 'desc_semir' => 'TRAILERS Y REMOLQUES', 'ind_estado' => 1),
			685 => array('cod_semir' => 181, 'desc_semir' => 'SERVIVOLCOS', 'ind_estado' => 1),
			686 => array('cod_semir' => 180, 'desc_semir' => 'ASH DOWN-MFG-CORT', 'ind_estado' => 1),
			687 => array('cod_semir' => 179, 'desc_semir' => 'CHANCEY', 'ind_estado' => 1),
			688 => array('cod_semir' => 177, 'desc_semir' => 'SUPERIOR', 'ind_estado' => 1),
			689 => array('cod_semir' => 176, 'desc_semir' => 'C. TRANSTANQUES', 'ind_estado' => 1),
			690 => array('cod_semir' => 175, 'desc_semir' => 'IND. LA SABANA', 'ind_estado' => 1),
			691 => array('cod_semir' => 174, 'desc_semir' => 'HOBBS', 'ind_estado' => 1),
			692 => array('cod_semir' => 173, 'desc_semir' => 'C. TANQUES', 'ind_estado' => 1),
			693 => array('cod_semir' => 172, 'desc_semir' => 'BAYONA TRAILER', 'ind_estado' => 1),
			694 => array('cod_semir' => 171, 'desc_semir' => 'GOMEZ GUERRERO', 'ind_estado' => 1),
			695 => array('cod_semir' => 170, 'desc_semir' => 'INMETALAROS', 'ind_estado' => 1),
			696 => array('cod_semir' => 169, 'desc_semir' => 'AMERICA', 'ind_estado' => 1),
			697 => array('cod_semir' => 168, 'desc_semir' => 'IND EL TRAILER', 'ind_estado' => 1),
			698 => array('cod_semir' => 167, 'desc_semir' => 'TALLERES ALVARO PACHON', 'ind_estado' => 1),
			699 => array('cod_semir' => 166, 'desc_semir' => 'ARANGO Y CIA.', 'ind_estado' => 1),
			700 => array('cod_semir' => 165, 'desc_semir' => 'DISTRAL', 'ind_estado' => 1),
			701 => array('cod_semir' => 164, 'desc_semir' => 'BIRMINGHAM', 'ind_estado' => 1),
			702 => array('cod_semir' => 163, 'desc_semir' => 'AUTOCARROF', 'ind_estado' => 1),
			703 => array('cod_semir' => 162, 'desc_semir' => 'HAWAIT', 'ind_estado' => 1),
			704 => array('cod_semir' => 161, 'desc_semir' => 'SCHEUERLE', 'ind_estado' => 1),
			705 => array('cod_semir' => 160, 'desc_semir' => 'BRIAB', 'ind_estado' => 1),
			706 => array('cod_semir' => 159, 'desc_semir' => 'INTRASECOL', 'ind_estado' => 1),
			707 => array('cod_semir' => 158, 'desc_semir' => 'STETTER', 'ind_estado' => 1),
			708 => array('cod_semir' => 157, 'desc_semir' => 'CARTANQUES', 'ind_estado' => 1),
			709 => array('cod_semir' => 156, 'desc_semir' => 'BUSSCAR DE COLOMBIA', 'ind_estado' => 1),
			710 => array('cod_semir' => 155, 'desc_semir' => 'CICOLGAS', 'ind_estado' => 1),
			711 => array('cod_semir' => 154, 'desc_semir' => 'PREMMIER', 'ind_estado' => 1),
			712 => array('cod_semir' => 153, 'desc_semir' => 'RH INDUSTRIAL', 'ind_estado' => 1),
			713 => array('cod_semir' => 152, 'desc_semir' => 'TRINITY - IMA', 'ind_estado' => 1),
			714 => array('cod_semir' => 151, 'desc_semir' => 'ASPEN  TRAILER', 'ind_estado' => 1),
			715 => array('cod_semir' => 150, 'desc_semir' => 'MUSTANG', 'ind_estado' => 1),
			716 => array('cod_semir' => 148, 'desc_semir' => 'ONEIDA', 'ind_estado' => 1),
			717 => array('cod_semir' => 147, 'desc_semir' => 'BETNA INTERNAL', 'ind_estado' => 1),
			718 => array('cod_semir' => 146, 'desc_semir' => 'INDUROMETAL', 'ind_estado' => 1),
			719 => array('cod_semir' => 145, 'desc_semir' => 'CONSTRUCTANQUES', 'ind_estado' => 1),
			720 => array('cod_semir' => 144, 'desc_semir' => 'CONTINENTAL', 'ind_estado' => 1),
			721 => array('cod_semir' => 143, 'desc_semir' => 'METALTANQUES', 'ind_estado' => 1),
			722 => array('cod_semir' => 142, 'desc_semir' => 'IND BERMEO', 'ind_estado' => 1),
			723 => array('cod_semir' => 141, 'desc_semir' => 'TRACTEC', 'ind_estado' => 1),
			724 => array('cod_semir' => 140, 'desc_semir' => 'LOADCRAFT', 'ind_estado' => 1),
			725 => array('cod_semir' => 139, 'desc_semir' => 'SAMDEL', 'ind_estado' => 1),
			726 => array('cod_semir' => 138, 'desc_semir' => 'IAS NECAR', 'ind_estado' => 1),
			727 => array('cod_semir' => 137, 'desc_semir' => 'INSAR', 'ind_estado' => 1),
			728 => array('cod_semir' => 136, 'desc_semir' => 'TECNISANTANDER', 'ind_estado' => 1),
			729 => array('cod_semir' => 135, 'desc_semir' => 'AUTOCHASIS', 'ind_estado' => 1),
			730 => array('cod_semir' => 134, 'desc_semir' => 'ANDITRAILERS', 'ind_estado' => 1),
			731 => array('cod_semir' => 133, 'desc_semir' => 'TRAILTEC', 'ind_estado' => 1),
			732 => array('cod_semir' => 132, 'desc_semir' => 'CHALLENGER', 'ind_estado' => 1),
			733 => array('cod_semir' => 131, 'desc_semir' => 'EQUINOX', 'ind_estado' => 1),
			734 => array('cod_semir' => 130, 'desc_semir' => 'FAJARDO', 'ind_estado' => 1),
			735 => array('cod_semir' => 129, 'desc_semir' => 'CYAN', 'ind_estado' => 1),
			736 => array('cod_semir' => 128, 'desc_semir' => 'FREEWAY', 'ind_estado' => 1),
			737 => array('cod_semir' => 127, 'desc_semir' => 'M.CARTER', 'ind_estado' => 1),
			738 => array('cod_semir' => 126, 'desc_semir' => 'CEDAL S.A', 'ind_estado' => 1),
			739 => array('cod_semir' => 125, 'desc_semir' => 'TALLERES NAVARRETE', 'ind_estado' => 1),
			740 => array('cod_semir' => 124, 'desc_semir' => 'METAL PRODUCTOS LTDA.', 'ind_estado' => 1),
			741 => array('cod_semir' => 123, 'desc_semir' => 'H.B. FERROSTAAI', 'ind_estado' => 1),
			742 => array('cod_semir' => 122, 'desc_semir' => 'TRACTEC LTDA.', 'ind_estado' => 1),
			743 => array('cod_semir' => 121, 'desc_semir' => 'GOLDHOFER', 'ind_estado' => 1),
			744 => array('cod_semir' => 120, 'desc_semir' => 'TALLERES LAVERDE', 'ind_estado' => 1),
			745 => array('cod_semir' => 119, 'desc_semir' => 'H.B. TRAYLERS', 'ind_estado' => 1),
			746 => array('cod_semir' => 118, 'desc_semir' => 'GAMEZA', 'ind_estado' => 1),
			747 => array('cod_semir' => 117, 'desc_semir' => 'FREE-WAYS', 'ind_estado' => 1),
			748 => array('cod_semir' => 116, 'desc_semir' => 'JAWAI', 'ind_estado' => 1),
			749 => array('cod_semir' => 115, 'desc_semir' => 'COLREMOLQUES', 'ind_estado' => 1),
			750 => array('cod_semir' => 114, 'desc_semir' => 'WHITE MARTINS', 'ind_estado' => 1),
			751 => array('cod_semir' => 113, 'desc_semir' => 'RUSSELL', 'ind_estado' => 1),
			752 => array('cod_semir' => 112, 'desc_semir' => 'DIEGO OTERO', 'ind_estado' => 1),
			753 => array('cod_semir' => 111, 'desc_semir' => 'IND. MUSTANG', 'ind_estado' => 1),
			754 => array('cod_semir' => 110, 'desc_semir' => 'TRACTOREMOLQUE', 'ind_estado' => 1),
			755 => array('cod_semir' => 109, 'desc_semir' => 'METALFABRIC', 'ind_estado' => 1),
			756 => array('cod_semir' => 108, 'desc_semir' => 'SER-REMOLQUES', 'ind_estado' => 1),
			757 => array('cod_semir' => 107, 'desc_semir' => 'COMESA', 'ind_estado' => 1),
			758 => array('cod_semir' => 106, 'desc_semir' => 'ECOLTANQUES', 'ind_estado' => 1),
			759 => array('cod_semir' => 105, 'desc_semir' => 'VICMAHER', 'ind_estado' => 1),
			760 => array('cod_semir' => 104, 'desc_semir' => 'TRAILERS Y TRAILERS', 'ind_estado' => 1),
			761 => array('cod_semir' => 103, 'desc_semir' => 'ACERAL', 'ind_estado' => 1),
			762 => array('cod_semir' => 102, 'desc_semir' => 'TALL. BOYACA', 'ind_estado' => 1),
			763 => array('cod_semir' => 101, 'desc_semir' => 'TECNICOTANQUES', 'ind_estado' => 1),
			764 => array('cod_semir' => 100, 'desc_semir' => 'HIGHWAY', 'ind_estado' => 1),
			765 => array('cod_semir' => 99, 'desc_semir' => 'CARREMOL', 'ind_estado' => 1),
			766 => array('cod_semir' => 98, 'desc_semir' => 'TALLERES UNIDOS', 'ind_estado' => 1),
			767 => array('cod_semir' => 97, 'desc_semir' => 'TRAILERSMAN', 'ind_estado' => 1),
			768 => array('cod_semir' => 96, 'desc_semir' => 'SNR', 'ind_estado' => 1),
			769 => array('cod_semir' => 95, 'desc_semir' => 'PROTRAIL', 'ind_estado' => 1),
			770 => array('cod_semir' => 94, 'desc_semir' => 'CARROCERIAS HERNANDEZ', 'ind_estado' => 1),
			771 => array('cod_semir' => 93, 'desc_semir' => 'INDUTANQUES', 'ind_estado' => 1),
			772 => array('cod_semir' => 92, 'desc_semir' => 'ORINOCO', 'ind_estado' => 1),
			773 => array('cod_semir' => 91, 'desc_semir' => 'IND HILER FONSECA', 'ind_estado' => 1),
			774 => array('cod_semir' => 90, 'desc_semir' => 'TALLERES CEPEDA', 'ind_estado' => 1),
			775 => array('cod_semir' => 89, 'desc_semir' => 'QUINTA RUEDA', 'ind_estado' => 1),
			776 => array('cod_semir' => 88, 'desc_semir' => 'SERVI-CHASIS', 'ind_estado' => 1),
			777 => array('cod_semir' => 87, 'desc_semir' => 'MARCAUTO', 'ind_estado' => 1),
			778 => array('cod_semir' => 86, 'desc_semir' => 'ALCICAR', 'ind_estado' => 1),
			779 => array('cod_semir' => 85, 'desc_semir' => 'TRA SABANA', 'ind_estado' => 1),
			780 => array('cod_semir' => 84, 'desc_semir' => 'TRAILERES Y TRACTOMULAS', 'ind_estado' => 1),
			781 => array('cod_semir' => 83, 'desc_semir' => 'OXITANQUES', 'ind_estado' => 1),
			782 => array('cod_semir' => 82, 'desc_semir' => 'VANEGAS', 'ind_estado' => 1),
			783 => array('cod_semir' => 81, 'desc_semir' => 'IMCAR', 'ind_estado' => 1),
			784 => array('cod_semir' => 80, 'desc_semir' => 'SIN MARCA', 'ind_estado' => 1),
			785 => array('cod_semir' => 79, 'desc_semir' => 'TALLERES BERNAL VALBUENA ', 'ind_estado' => 1),
			786 => array('cod_semir' => 78, 'desc_semir' => 'MECTEL', 'ind_estado' => 1),
			787 => array('cod_semir' => 77, 'desc_semir' => 'APOLO', 'ind_estado' => 1),
			788 => array('cod_semir' => 76, 'desc_semir' => 'WELDSHIP', 'ind_estado' => 1),
			789 => array('cod_semir' => 75, 'desc_semir' => 'METALINOX', 'ind_estado' => 1),
			790 => array('cod_semir' => 74, 'desc_semir' => 'KLEIN', 'ind_estado' => 1),
			791 => array('cod_semir' => 73, 'desc_semir' => 'IMECOL', 'ind_estado' => 1),
			792 => array('cod_semir' => 72, 'desc_semir' => 'INTRACO', 'ind_estado' => 1),
			793 => array('cod_semir' => 71, 'desc_semir' => 'METALCONT', 'ind_estado' => 1),
			794 => array('cod_semir' => 70, 'desc_semir' => 'CRYENCO', 'ind_estado' => 1),
			795 => array('cod_semir' => 69, 'desc_semir' => 'TECNICAR', 'ind_estado' => 1),
			796 => array('cod_semir' => 68, 'desc_semir' => 'JADEHEL', 'ind_estado' => 1),
			797 => array('cod_semir' => 67, 'desc_semir' => 'CAPRI', 'ind_estado' => 1),
			798 => array('cod_semir' => 66, 'desc_semir' => 'COM TRAYLER', 'ind_estado' => 1),
			799 => array('cod_semir' => 65, 'desc_semir' => 'WILLIAMSEN', 'ind_estado' => 1),
			800 => array('cod_semir' => 64, 'desc_semir' => 'WENGER ', 'ind_estado' => 1),
			801 => array('cod_semir' => 63, 'desc_semir' => 'WABASH', 'ind_estado' => 1),
			802 => array('cod_semir' => 62, 'desc_semir' => 'VIQUING', 'ind_estado' => 1),
			803 => array('cod_semir' => 61, 'desc_semir' => 'UTTILITY', 'ind_estado' => 1),
			804 => array('cod_semir' => 60, 'desc_semir' => 'TRAILMOVILE', 'ind_estado' => 1),
			805 => array('cod_semir' => 59, 'desc_semir' => 'TOP & HAT', 'ind_estado' => 1),
			806 => array('cod_semir' => 58, 'desc_semir' => 'TECNIPESADOS', 'ind_estado' => 1),
			807 => array('cod_semir' => 57, 'desc_semir' => 'TALLERES Y TALLERES', 'ind_estado' => 1),
			808 => array('cod_semir' => 56, 'desc_semir' => 'TALLERES Y REMOLQUES', 'ind_estado' => 1),
			809 => array('cod_semir' => 55, 'desc_semir' => 'TALLERES TRAILER TULUA', 'ind_estado' => 1),
			810 => array('cod_semir' => 54, 'desc_semir' => 'TALLER ABRAPOL', 'ind_estado' => 1),
			811 => array('cod_semir' => 53, 'desc_semir' => 'TALBERTxxxxxxx', 'ind_estado' => 1),
			812 => array('cod_semir' => 52, 'desc_semir' => 'SERVITRAILER', 'ind_estado' => 1),
			813 => array('cod_semir' => 51, 'desc_semir' => 'SERVIMECOL', 'ind_estado' => 1),
			814 => array('cod_semir' => 50, 'desc_semir' => 'SER LA QUINTA RUEDA', 'ind_estado' => 1),
			815 => array('cod_semir' => 49, 'desc_semir' => 'SCHIEN', 'ind_estado' => 1),
			816 => array('cod_semir' => 48, 'desc_semir' => 'ROMARCO', 'ind_estado' => 1),
			817 => array('cod_semir' => 47, 'desc_semir' => 'RICHMOND LOX EQUIP.', 'ind_estado' => 1),
			818 => array('cod_semir' => 46, 'desc_semir' => 'REMOLQUES DEL CARIBE', 'ind_estado' => 1),
			819 => array('cod_semir' => 45, 'desc_semir' => 'PUBLIFIBRA', 'ind_estado' => 1),
			820 => array('cod_semir' => 44, 'desc_semir' => 'PRODITANQUES', 'ind_estado' => 1),
			821 => array('cod_semir' => 43, 'desc_semir' => 'PROCEIN', 'ind_estado' => 1),
			822 => array('cod_semir' => 42, 'desc_semir' => 'PIONEER', 'ind_estado' => 1),
			823 => array('cod_semir' => 41, 'desc_semir' => 'NORGAS', 'ind_estado' => 1),
			824 => array('cod_semir' => 40, 'desc_semir' => 'NL CONTAPA S.A.', 'ind_estado' => 1),
			825 => array('cod_semir' => 39, 'desc_semir' => 'TISSOT', 'ind_estado' => 1),
			826 => array('cod_semir' => 38, 'desc_semir' => 'THE HEILCO', 'ind_estado' => 1),
			827 => array('cod_semir' => 37, 'desc_semir' => 'TEXAS BRAGG ENTER', 'ind_estado' => 1),
			828 => array('cod_semir' => 36, 'desc_semir' => 'LUFKIN', 'ind_estado' => 1),
			829 => array('cod_semir' => 35, 'desc_semir' => 'J.S SERVIPETROL LTDA', 'ind_estado' => 1),
			830 => array('cod_semir' => 33, 'desc_semir' => 'IND SAN MARCOS', 'ind_estado' => 1),
			831 => array('cod_semir' => 32, 'desc_semir' => 'IND METALMECAN P.B.A.', 'ind_estado' => 1),
			832 => array('cod_semir' => 31, 'desc_semir' => 'IND ACEVEDO Y CIA LTDA', 'ind_estado' => 1),
			833 => array('cod_semir' => 30, 'desc_semir' => 'INDUROC', 'ind_estado' => 1),
			834 => array('cod_semir' => 29, 'desc_semir' => 'INDUREMOLQUES', 'ind_estado' => 1),
			835 => array('cod_semir' => 28, 'desc_semir' => 'INDU TAN PAS', 'ind_estado' => 1),
			836 => array('cod_semir' => 27, 'desc_semir' => 'INCA FRUEHAUF', 'ind_estado' => 1),
			837 => array('cod_semir' => 26, 'desc_semir' => 'IMEVA', 'ind_estado' => 1),
			838 => array('cod_semir' => 24, 'desc_semir' => 'HIDROAMERICA', 'ind_estado' => 1),
			839 => array('cod_semir' => 23, 'desc_semir' => 'HEILL', 'ind_estado' => 1),
			840 => array('cod_semir' => 22, 'desc_semir' => 'HALLIBURTON', 'ind_estado' => 1),
			841 => array('cod_semir' => 21, 'desc_semir' => 'GUERREROS', 'ind_estado' => 1),
			842 => array('cod_semir' => 20, 'desc_semir' => 'GREAT DANE', 'ind_estado' => 1),
			843 => array('cod_semir' => 19, 'desc_semir' => 'GREAD DANE', 'ind_estado' => 1),
			844 => array('cod_semir' => 18, 'desc_semir' => 'GE  CAPITAL', 'ind_estado' => 1),
			845 => array('cod_semir' => 17, 'desc_semir' => 'FRUEHAUF', 'ind_estado' => 1),
			846 => array('cod_semir' => 16, 'desc_semir' => 'FORTALEZA', 'ind_estado' => 1),
			847 => array('cod_semir' => 15, 'desc_semir' => 'FONTAINE', 'ind_estado' => 1),
			848 => array('cod_semir' => 14, 'desc_semir' => 'FLEETWOOD', 'ind_estado' => 1),
			849 => array('cod_semir' => 12, 'desc_semir' => 'ESTEMCO', 'ind_estado' => 1),
			850 => array('cod_semir' => 11, 'desc_semir' => 'EL SOL', 'ind_estado' => 1),
			851 => array('cod_semir' => 10, 'desc_semir' => 'DUQUE Y CIA SCS', 'ind_estado' => 1),
			852 => array('cod_semir' => 9, 'desc_semir' => 'DITE S.A.', 'ind_estado' => 1),
			853 => array('cod_semir' => 8, 'desc_semir' => 'DISETRAN', 'ind_estado' => 1),
			854 => array('cod_semir' => 7, 'desc_semir' => 'DISALUM', 'ind_estado' => 1),
			855 => array('cod_semir' => 6, 'desc_semir' => 'DEUTZ', 'ind_estado' => 1),
			856 => array('cod_semir' => 5, 'desc_semir' => 'CLARK', 'ind_estado' => 1),
			857 => array('cod_semir' => 4, 'desc_semir' => 'ALCAR', 'ind_estado' => 1),
			858 => array('cod_semir' => 3, 'desc_semir' => 'ATOKA', 'ind_estado' => 1),
			859 => array('cod_semir' => 2, 'desc_semir' => 'ANDI ESTRUCTURAS MET', 'ind_estado' => 1),
			860 => array('cod_semir' => 1, 'desc_semir' => 'AGRO DEL FONCE', 'ind_estado' => 1),

		));
    }
}
