<?php

use Illuminate\Database\Seeder;

class MarcasVehiculosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {       
        \DB::table('marcas_vehiculos')->insert(array (
			0 => array('cod_marcax'  => 1078, 'nom_marcax' => 'T-KING', 'ind_estado' => 1),
			1 => array('cod_marcax'  => 1212, 'nom_marcax' => 'DONG-A', 'ind_estado' => 1),
			2 => array('cod_marcax'  => 1100, 'nom_marcax' => 'CNJ', 'ind_estado' => 1),
			3 => array('cod_marcax'  => 2337, 'nom_marcax' => 'BAIC', 'ind_estado' => 1),
			4 => array('cod_marcax'  => 1134, 'nom_marcax' => 'DFAC DONG FENG', 'ind_estado' => 1),
			5 => array('cod_marcax'  => 1076, 'nom_marcax' => 'GVMCO', 'ind_estado' => 1),
			6 => array('cod_marcax'  => 1075, 'nom_marcax' => 'GBMCO', 'ind_estado' => 1),
			7 => array('cod_marcax'  => 1074, 'nom_marcax' => 'INDUSTRY', 'ind_estado' => 1),
			8 => array('cod_marcax'  => 1073, 'nom_marcax' => 'FENIX', 'ind_estado' => 1),
			9 => array('cod_marcax'  => 1072, 'nom_marcax' => 'GAME', 'ind_estado' => 1),
			10 => array('cod_marcax'  => 1071, 'nom_marcax' => 'SANYOU', 'ind_estado' => 1),
			11 => array('cod_marcax'  => 1070, 'nom_marcax' => 'MIKILON', 'ind_estado' => 1),
			12 => array('cod_marcax'  => 1069, 'nom_marcax' => 'FASTER', 'ind_estado' => 1),
			13 => array('cod_marcax'  => 1068, 'nom_marcax' => 'MOFFETT', 'ind_estado' => 1),
			14 => array('cod_marcax'  => 1067, 'nom_marcax' => 'SELVAXTREMA', 'ind_estado' => 1),
			15 => array('cod_marcax'  => 1066, 'nom_marcax' => 'JUNCHI', 'ind_estado' => 1),
			16 => array('cod_marcax'  => 1065, 'nom_marcax' => 'UD TRUCKS', 'ind_estado' => 1),
			17 => array('cod_marcax'  => 1064, 'nom_marcax' => 'POLARSUN', 'ind_estado' => 1),
			18 => array('cod_marcax'  => 1063, 'nom_marcax' => 'SINOTRUK', 'ind_estado' => 1),
			19 => array('cod_marcax'  => 1062, 'nom_marcax' => 'ASIA HERO', 'ind_estado' => 1),
			20 => array('cod_marcax'  => 1061, 'nom_marcax' => 'ALFA', 'ind_estado' => 1),
			21 => array('cod_marcax'  => 1060, 'nom_marcax' => 'ZILI MOTORS', 'ind_estado' => 1),
			22 => array('cod_marcax'  => 1059, 'nom_marcax' => 'JAUNCE', 'ind_estado' => 1),
			23 => array('cod_marcax'  => 1058, 'nom_marcax' => 'HONOR', 'ind_estado' => 1),
			24 => array('cod_marcax'  => 1057, 'nom_marcax' => 'AWS', 'ind_estado' => 1),
			25 => array('cod_marcax'  => 1056, 'nom_marcax' => 'LANGQING', 'ind_estado' => 1),
			26 => array('cod_marcax'  => 1055, 'nom_marcax' => 'SENKE', 'ind_estado' => 1),
			27 => array('cod_marcax'  => 1054, 'nom_marcax' => 'XGJAO', 'ind_estado' => 1),
			28 => array('cod_marcax'  => 1053, 'nom_marcax' => 'BERA', 'ind_estado' => 1),
			29 => array('cod_marcax'  => 1052, 'nom_marcax' => 'GSMOON', 'ind_estado' => 1),
			30 => array('cod_marcax'  => 1051, 'nom_marcax' => 'OLIYA', 'ind_estado' => 1),
			31 => array('cod_marcax'  => 1050, 'nom_marcax' => 'DFSK', 'ind_estado' => 1),
			32 => array('cod_marcax'  => 1049, 'nom_marcax' => 'ESCORPIO', 'ind_estado' => 1),
			33 => array('cod_marcax'  => 1048, 'nom_marcax' => 'KING LONG', 'ind_estado' => 1),
			34 => array('cod_marcax'  => 1047, 'nom_marcax' => 'DADI', 'ind_estado' => 1),
			35 => array('cod_marcax'  => 1046, 'nom_marcax' => 'HUANGHAI', 'ind_estado' => 1),
			36 => array('cod_marcax'  => 1045, 'nom_marcax' => 'ZNA', 'ind_estado' => 1),
			37 => array('cod_marcax'  => 1044, 'nom_marcax' => 'HANLING', 'ind_estado' => 1),
			38 => array('cod_marcax'  => 1043, 'nom_marcax' => 'YAXING', 'ind_estado' => 1),
			39 => array('cod_marcax'  => 1042, 'nom_marcax' => 'OULING', 'ind_estado' => 1),
			40 => array('cod_marcax'  => 1041, 'nom_marcax' => 'BENLING', 'ind_estado' => 1),
			41 => array('cod_marcax'  => 1040, 'nom_marcax' => 'MAHINDRA DURO', 'ind_estado' => 1),
			42 => array('cod_marcax'  => 1039, 'nom_marcax' => 'CLC MOTOR', 'ind_estado' => 1),
			43 => array('cod_marcax'  => 1038, 'nom_marcax' => 'LUCKY LION', 'ind_estado' => 1),
			44 => array('cod_marcax'  => 1037, 'nom_marcax' => 'CARPATI', 'ind_estado' => 1),
			45 => array('cod_marcax'  => 1036, 'nom_marcax' => 'VMOTO', 'ind_estado' => 1),
			46 => array('cod_marcax'  => 1035, 'nom_marcax' => 'SHELBY', 'ind_estado' => 1),
			47 => array('cod_marcax'  => 1034, 'nom_marcax' => 'HAORI', 'ind_estado' => 1),
			48 => array('cod_marcax'  => 1033, 'nom_marcax' => 'TAYLOR DUNN', 'ind_estado' => 1),
			49 => array('cod_marcax'  => 1032, 'nom_marcax' => 'D LONG', 'ind_estado' => 1),
			50 => array('cod_marcax'  => 1031, 'nom_marcax' => 'LOVOL', 'ind_estado' => 1),
			51 => array('cod_marcax'  => 1030, 'nom_marcax' => 'THOMAS BUILT BUSES', 'ind_estado' => 1),
			52 => array('cod_marcax'  => 1029, 'nom_marcax' => 'HUNTER', 'ind_estado' => 1),
			53 => array('cod_marcax'  => 1028, 'nom_marcax' => 'KMO', 'ind_estado' => 1),
			54 => array('cod_marcax'  => 1027, 'nom_marcax' => 'DETROIT', 'ind_estado' => 1),
			55 => array('cod_marcax'  => 1026, 'nom_marcax' => 'E-ONE', 'ind_estado' => 1),
			56 => array('cod_marcax'  => 1025, 'nom_marcax' => 'DFA', 'ind_estado' => 1),
			57 => array('cod_marcax'  => 1024, 'nom_marcax' => 'JBC', 'ind_estado' => 1),
			58 => array('cod_marcax'  => 1023, 'nom_marcax' => 'ETX', 'ind_estado' => 1),
			59 => array('cod_marcax'  => 1022, 'nom_marcax' => 'JIAJUE', 'ind_estado' => 1),
			60 => array('cod_marcax'  => 1021, 'nom_marcax' => 'ADVANCE', 'ind_estado' => 1),
			61 => array('cod_marcax'  => 1020, 'nom_marcax' => 'JLC', 'ind_estado' => 1),
			62 => array('cod_marcax'  => 1019, 'nom_marcax' => 'YADEA', 'ind_estado' => 1),
			63 => array('cod_marcax'  => 1018, 'nom_marcax' => 'HPOWER', 'ind_estado' => 1),
			64 => array('cod_marcax'  => 1017, 'nom_marcax' => 'ENERGY MOTION', 'ind_estado' => 1),
			65 => array('cod_marcax'  => 1016, 'nom_marcax' => 'JIASHITE', 'ind_estado' => 1),
			66 => array('cod_marcax'  => 1015, 'nom_marcax' => 'BYVIN', 'ind_estado' => 1),
			67 => array('cod_marcax'  => 1014, 'nom_marcax' => 'PACIFIC', 'ind_estado' => 1),
			68 => array('cod_marcax'  => 1013, 'nom_marcax' => 'GALAXI', 'ind_estado' => 1),
			69 => array('cod_marcax'  => 1012, 'nom_marcax' => 'TAO TAO', 'ind_estado' => 1),
			70 => array('cod_marcax'  => 1011, 'nom_marcax' => 'WANCH', 'ind_estado' => 1),
			71 => array('cod_marcax'  => 1010, 'nom_marcax' => 'YGM', 'ind_estado' => 1),
			72 => array('cod_marcax'  => 1009, 'nom_marcax' => 'LINGKEN', 'ind_estado' => 1),
			73 => array('cod_marcax'  => 1008, 'nom_marcax' => 'JIANGSU SINSKI', 'ind_estado' => 1),
			74 => array('cod_marcax'  => 1007, 'nom_marcax' => 'AWS - ALIEN WORK SHOP', 'ind_estado' => 1),
			75 => array('cod_marcax'  => 1006, 'nom_marcax' => 'TRACTOCASA', 'ind_estado' => 1),
			76 => array('cod_marcax'  => 1004, 'nom_marcax' => 'HISUN TIGER', 'ind_estado' => 1),
			77 => array('cod_marcax'  => 1003, 'nom_marcax' => 'VOLDA', 'ind_estado' => 1),
			78 => array('cod_marcax'  => 1002, 'nom_marcax' => 'SMA', 'ind_estado' => 1),
			79 => array('cod_marcax'  => 1001, 'nom_marcax' => 'HAIMA', 'ind_estado' => 1),
			80 => array('cod_marcax'  => 1000, 'nom_marcax' => 'TORNADO', 'ind_estado' => 1),
			81 => array('cod_marcax'  => 999, 'nom_marcax' => 'GREENWHEEL', 'ind_estado' => 1),
			82 => array('cod_marcax'  => 998, 'nom_marcax' => 'YAKEY', 'ind_estado' => 1),
			83 => array('cod_marcax'  => 997, 'nom_marcax' => 'KHOOBRA', 'ind_estado' => 1),
			84 => array('cod_marcax'  => 996, 'nom_marcax' => 'ESSEX', 'ind_estado' => 1),
			85 => array('cod_marcax'  => 995, 'nom_marcax' => 'ASA', 'ind_estado' => 1),
			86 => array('cod_marcax'  => 994, 'nom_marcax' => 'ISHIMOTO', 'ind_estado' => 1),
			87 => array('cod_marcax'  => 993, 'nom_marcax' => 'MITSUBISHI FUSO', 'ind_estado' => 1),
			88 => array('cod_marcax'  => 992, 'nom_marcax' => 'YONGKANG EASY VEHICLE', 'ind_estado' => 1),
			89 => array('cod_marcax'  => 991, 'nom_marcax' => 'MANZINI', 'ind_estado' => 1),
			90 => array('cod_marcax'  => 990, 'nom_marcax' => 'MOTOKART', 'ind_estado' => 1),
			91 => array('cod_marcax'  => 989, 'nom_marcax' => 'BARHOG/DADYW', 'ind_estado' => 1),
			92 => array('cod_marcax'  => 988, 'nom_marcax' => 'SM', 'ind_estado' => 1),
			93 => array('cod_marcax'  => 987, 'nom_marcax' => 'SUMA', 'ind_estado' => 1),
			94 => array('cod_marcax'  => 986, 'nom_marcax' => 'AVA MOTORS', 'ind_estado' => 1),
			95 => array('cod_marcax'  => 985, 'nom_marcax' => 'BOUE', 'ind_estado' => 1),
			96 => array('cod_marcax'  => 984, 'nom_marcax' => 'SHACMAN', 'ind_estado' => 1),
			97 => array('cod_marcax'  => 983, 'nom_marcax' => 'HUALIN', 'ind_estado' => 1),
			98 => array('cod_marcax'  => 982, 'nom_marcax' => 'TEAM RYDER', 'ind_estado' => 1),
			99 => array('cod_marcax'  => 981, 'nom_marcax' => 'AUTECO VICTORY', 'ind_estado' => 1),
			100 => array('cod_marcax'  => 980, 'nom_marcax' => 'SANLEE', 'ind_estado' => 1),
			101 => array('cod_marcax'  => 979, 'nom_marcax' => 'HENSIM', 'ind_estado' => 1),
			102 => array('cod_marcax'  => 978, 'nom_marcax' => 'XRP SAIN', 'ind_estado' => 1),
			103 => array('cod_marcax'  => 977, 'nom_marcax' => 'FUXIN', 'ind_estado' => 1),
			104 => array('cod_marcax'  => 976, 'nom_marcax' => 'TEMPEST', 'ind_estado' => 1),
			105 => array('cod_marcax'  => 975, 'nom_marcax' => 'CFMOTO', 'ind_estado' => 1),
			106 => array('cod_marcax'  => 973, 'nom_marcax' => 'HIGER', 'ind_estado' => 1),
			107 => array('cod_marcax'  => 972, 'nom_marcax' => 'TOURING', 'ind_estado' => 1),
			108 => array('cod_marcax'  => 971, 'nom_marcax' => 'DCEC', 'ind_estado' => 1),
			109 => array('cod_marcax'  => 970, 'nom_marcax' => 'ARCTIC CAT', 'ind_estado' => 1),
			110 => array('cod_marcax'  => 969, 'nom_marcax' => 'MALAGUTI', 'ind_estado' => 1),
			111 => array('cod_marcax'  => 968, 'nom_marcax' => 'WANHU', 'ind_estado' => 1),
			112 => array('cod_marcax'  => 967, 'nom_marcax' => 'YUTONG', 'ind_estado' => 1),
			113 => array('cod_marcax'  => 966, 'nom_marcax' => 'FIVER', 'ind_estado' => 1),
			114 => array('cod_marcax'  => 965, 'nom_marcax' => 'LIEBHERR', 'ind_estado' => 1),
			115 => array('cod_marcax'  => 964, 'nom_marcax' => 'HOREX', 'ind_estado' => 1),
			116 => array('cod_marcax'  => 963, 'nom_marcax' => 'PERLINI', 'ind_estado' => 1),
			117 => array('cod_marcax'  => 962, 'nom_marcax' => 'MOXI', 'ind_estado' => 1),
			118 => array('cod_marcax'  => 961, 'nom_marcax' => 'MAZ', 'ind_estado' => 1),
			119 => array('cod_marcax'  => 960, 'nom_marcax' => 'DRESSER HAULPAK', 'ind_estado' => 1),
			120 => array('cod_marcax'  => 959, 'nom_marcax' => 'AUTECO KYMCO', 'ind_estado' => 1),
			121 => array('cod_marcax'  => 958, 'nom_marcax' => 'AUTECO BAJAJ', 'ind_estado' => 1),
			122 => array('cod_marcax'  => 957, 'nom_marcax' => 'SANY', 'ind_estado' => 1),
			123 => array('cod_marcax'  => 956, 'nom_marcax' => 'BOMAG', 'ind_estado' => 1),
			124 => array('cod_marcax'  => 955, 'nom_marcax' => 'THOMAS', 'ind_estado' => 1),
			125 => array('cod_marcax'  => 954, 'nom_marcax' => 'STERLING', 'ind_estado' => 1),
			126 => array('cod_marcax'  => 953, 'nom_marcax' => 'ZHONGHUA', 'ind_estado' => 1),
			127 => array('cod_marcax'  => 952, 'nom_marcax' => 'YITAKI', 'ind_estado' => 1),
			128 => array('cod_marcax'  => 951, 'nom_marcax' => 'VOSHUD', 'ind_estado' => 1),
			129 => array('cod_marcax'  => 950, 'nom_marcax' => 'VEDETTE', 'ind_estado' => 1),
			130 => array('cod_marcax'  => 949, 'nom_marcax' => 'UNDERBONE', 'ind_estado' => 1),
			131 => array('cod_marcax'  => 948, 'nom_marcax' => 'TRADER', 'ind_estado' => 1),
			132 => array('cod_marcax'  => 947, 'nom_marcax' => 'TONGBAO', 'ind_estado' => 1),
			133 => array('cod_marcax'  => 946, 'nom_marcax' => 'TANDEM', 'ind_estado' => 1),
			134 => array('cod_marcax'  => 945, 'nom_marcax' => 'T.J.C.', 'ind_estado' => 1),
			135 => array('cod_marcax'  => 944, 'nom_marcax' => 'STUTZ', 'ind_estado' => 1),
			136 => array('cod_marcax'  => 943, 'nom_marcax' => 'STAR', 'ind_estado' => 1),
			137 => array('cod_marcax'  => 942, 'nom_marcax' => 'SSANGYANG', 'ind_estado' => 1),
			138 => array('cod_marcax'  => 941, 'nom_marcax' => 'SKANIA VABIF', 'ind_estado' => 1),
			139 => array('cod_marcax'  => 940, 'nom_marcax' => 'SCOUTY', 'ind_estado' => 1),
			140 => array('cod_marcax'  => 939, 'nom_marcax' => 'ROMAN', 'ind_estado' => 1),
			141 => array('cod_marcax'  => 938, 'nom_marcax' => 'ROCAR', 'ind_estado' => 1),
			142 => array('cod_marcax'  => 937, 'nom_marcax' => 'PAZ', 'ind_estado' => 1),
			143 => array('cod_marcax'  => 936, 'nom_marcax' => 'PANDA CHUNZOHN', 'ind_estado' => 1),
			144 => array('cod_marcax'  => 935, 'nom_marcax' => 'LUAZ', 'ind_estado' => 1),
			145 => array('cod_marcax'  => 934, 'nom_marcax' => 'LLOYD', 'ind_estado' => 1),
			146 => array('cod_marcax'  => 933, 'nom_marcax' => 'JINLING', 'ind_estado' => 1),
			147 => array('cod_marcax'  => 932, 'nom_marcax' => 'IFG', 'ind_estado' => 1),
			148 => array('cod_marcax'  => 931, 'nom_marcax' => 'FODEN', 'ind_estado' => 1),
			149 => array('cod_marcax'  => 930, 'nom_marcax' => 'BAW ZHAN QI', 'ind_estado' => 1),
			150 => array('cod_marcax'  => 929, 'nom_marcax' => 'AUTO BIANCHI', 'ind_estado' => 1),
			151 => array('cod_marcax'  => 928, 'nom_marcax' => 'AEOLUS', 'ind_estado' => 1),
			152 => array('cod_marcax'  => 927, 'nom_marcax' => 'WEST WARRIOR', 'ind_estado' => 1),
			153 => array('cod_marcax'  => 926, 'nom_marcax' => 'REGAL RAPTOR', 'ind_estado' => 1),
			154 => array('cod_marcax'  => 925, 'nom_marcax' => 'PRATOO Y FORNE', 'ind_estado' => 1),
			155 => array('cod_marcax'  => 924, 'nom_marcax' => 'HAOJIANG', 'ind_estado' => 1),
			156 => array('cod_marcax'  => 923, 'nom_marcax' => 'CIXI KONCEO', 'ind_estado' => 1),
			157 => array('cod_marcax'  => 922, 'nom_marcax' => 'HONGXING NOBLE', 'ind_estado' => 1),
			158 => array('cod_marcax'  => 921, 'nom_marcax' => 'ALLARD', 'ind_estado' => 1),
			159 => array('cod_marcax'  => 920, 'nom_marcax' => 'ALL STATE', 'ind_estado' => 1),
			160 => array('cod_marcax'  => 919, 'nom_marcax' => 'ZUK NYSA', 'ind_estado' => 1),
			161 => array('cod_marcax'  => 918, 'nom_marcax' => 'ZUK', 'ind_estado' => 1),
			162 => array('cod_marcax'  => 917, 'nom_marcax' => 'ZQ MOTORS', 'ind_estado' => 1),
			163 => array('cod_marcax'  => 916, 'nom_marcax' => 'ZIU', 'ind_estado' => 1),
			164 => array('cod_marcax'  => 915, 'nom_marcax' => 'ZHONGYU', 'ind_estado' => 1),
			165 => array('cod_marcax'  => 914, 'nom_marcax' => 'ZHONGNENG', 'ind_estado' => 1),
			166 => array('cod_marcax'  => 913, 'nom_marcax' => 'ZHAN', 'ind_estado' => 1),
			167 => array('cod_marcax'  => 912, 'nom_marcax' => 'ZENA', 'ind_estado' => 1),
			168 => array('cod_marcax'  => 911, 'nom_marcax' => 'YLM', 'ind_estado' => 1),
			169 => array('cod_marcax'  => 910, 'nom_marcax' => 'XSG ING QIJITUA', 'ind_estado' => 1),
			170 => array('cod_marcax'  => 909, 'nom_marcax' => 'XINTIAN KINROAD', 'ind_estado' => 1),
			171 => array('cod_marcax'  => 908, 'nom_marcax' => 'XINLING', 'ind_estado' => 1),
			172 => array('cod_marcax'  => 907, 'nom_marcax' => 'XINGLING', 'ind_estado' => 1),
			173 => array('cod_marcax'  => 906, 'nom_marcax' => 'WSK', 'ind_estado' => 1),
			174 => array('cod_marcax'  => 905, 'nom_marcax' => 'WORLDSTAR', 'ind_estado' => 1),
			175 => array('cod_marcax'  => 904, 'nom_marcax' => 'WORD LA FRANCE', 'ind_estado' => 1),
			176 => array('cod_marcax'  => 903, 'nom_marcax' => 'WLLHELMSHAVEN', 'ind_estado' => 1),
			177 => array('cod_marcax'  => 902, 'nom_marcax' => 'WINCHEMG', 'ind_estado' => 1),
			178 => array('cod_marcax'  => 901, 'nom_marcax' => 'WAJAX', 'ind_estado' => 1),
			179 => array('cod_marcax'  => 900, 'nom_marcax' => 'WAGONNER', 'ind_estado' => 1),
			180 => array('cod_marcax'  => 899, 'nom_marcax' => 'VONROAD', 'ind_estado' => 1),
			181 => array('cod_marcax'  => 898, 'nom_marcax' => 'VOGUE', 'ind_estado' => 1),
			182 => array('cod_marcax'  => 897, 'nom_marcax' => 'VANGUARD', 'ind_estado' => 1),
			183 => array('cod_marcax'  => 896, 'nom_marcax' => 'VALKYRIE', 'ind_estado' => 1),
			184 => array('cod_marcax'  => 895, 'nom_marcax' => 'VALIANT', 'ind_estado' => 1),
			185 => array('cod_marcax'  => 894, 'nom_marcax' => 'UFO', 'ind_estado' => 1),
			186 => array('cod_marcax'  => 893, 'nom_marcax' => 'TULA', 'ind_estado' => 1),
			187 => array('cod_marcax'  => 892, 'nom_marcax' => 'TOYOPET', 'ind_estado' => 1),
			188 => array('cod_marcax'  => 891, 'nom_marcax' => 'TONGYU', 'ind_estado' => 1),
			189 => array('cod_marcax'  => 890, 'nom_marcax' => 'TMD', 'ind_estado' => 1),
			190 => array('cod_marcax'  => 889, 'nom_marcax' => 'TGA-200-G', 'ind_estado' => 1),
			191 => array('cod_marcax'  => 888, 'nom_marcax' => 'TEMPO', 'ind_estado' => 1),
			192 => array('cod_marcax'  => 887, 'nom_marcax' => 'TATRA', 'ind_estado' => 1),
			193 => array('cod_marcax'  => 886, 'nom_marcax' => 'TANTA', 'ind_estado' => 1),
			194 => array('cod_marcax'  => 885, 'nom_marcax' => 'TALBOT', 'ind_estado' => 1),
			195 => array('cod_marcax'  => 884, 'nom_marcax' => 'SUPERMOTO', 'ind_estado' => 1),
			196 => array('cod_marcax'  => 883, 'nom_marcax' => 'SUNASA QINGQI', 'ind_estado' => 1),
			197 => array('cod_marcax'  => 882, 'nom_marcax' => 'SUMO', 'ind_estado' => 1),
			198 => array('cod_marcax'  => 881, 'nom_marcax' => 'STIRES VM', 'ind_estado' => 1),
			199 => array('cod_marcax'  => 880, 'nom_marcax' => 'STEINBOCK', 'ind_estado' => 1),
			200 => array('cod_marcax'  => 879, 'nom_marcax' => 'SST', 'ind_estado' => 1),
			201 => array('cod_marcax'  => 878, 'nom_marcax' => 'SRFHUAIGE', 'ind_estado' => 1),
			202 => array('cod_marcax'  => 877, 'nom_marcax' => 'SP@ZZIO', 'ind_estado' => 1),
			203 => array('cod_marcax'  => 876, 'nom_marcax' => 'SOYAT', 'ind_estado' => 1),
			204 => array('cod_marcax'  => 875, 'nom_marcax' => 'SONZINI', 'ind_estado' => 1),
			205 => array('cod_marcax'  => 874, 'nom_marcax' => 'SONIKA', 'ind_estado' => 1),
			206 => array('cod_marcax'  => 873, 'nom_marcax' => 'SOLARI', 'ind_estado' => 1),
			207 => array('cod_marcax'  => 872, 'nom_marcax' => 'SKYTEAM', 'ind_estado' => 1),
			208 => array('cod_marcax'  => 871, 'nom_marcax' => 'SHUANGSHI', 'ind_estado' => 1),
			209 => array('cod_marcax'  => 870, 'nom_marcax' => 'SHUANGHUAN', 'ind_estado' => 1),
			210 => array('cod_marcax'  => 869, 'nom_marcax' => 'SHERPA', 'ind_estado' => 1),
			211 => array('cod_marcax'  => 868, 'nom_marcax' => 'SHANYANG', 'ind_estado' => 1),
			212 => array('cod_marcax'  => 867, 'nom_marcax' => 'SHANGLI', 'ind_estado' => 1),
			213 => array('cod_marcax'  => 866, 'nom_marcax' => 'SERVAL', 'ind_estado' => 1),
			214 => array('cod_marcax'  => 865, 'nom_marcax' => 'SEAGRAVE', 'ind_estado' => 1),
			215 => array('cod_marcax'  => 864, 'nom_marcax' => 'SCAMMELL', 'ind_estado' => 1),
			216 => array('cod_marcax'  => 863, 'nom_marcax' => 'SAURER', 'ind_estado' => 1),
			217 => array('cod_marcax'  => 862, 'nom_marcax' => 'SANGLIN', 'ind_estado' => 1),
			218 => array('cod_marcax'  => 861, 'nom_marcax' => 'SANDI', 'ind_estado' => 1),
			219 => array('cod_marcax'  => 860, 'nom_marcax' => 'SAAB', 'ind_estado' => 1),
			220 => array('cod_marcax'  => 859, 'nom_marcax' => 'ROSENBAUER', 'ind_estado' => 1),
			221 => array('cod_marcax'  => 858, 'nom_marcax' => 'REVA', 'ind_estado' => 1),
			222 => array('cod_marcax'  => 857, 'nom_marcax' => 'RABBIT', 'ind_estado' => 1),
			223 => array('cod_marcax'  => 856, 'nom_marcax' => 'PREFECT', 'ind_estado' => 1),
			224 => array('cod_marcax'  => 855, 'nom_marcax' => 'POWER WAGON', 'ind_estado' => 1),
			225 => array('cod_marcax'  => 854, 'nom_marcax' => 'PLANETA', 'ind_estado' => 1),
			226 => array('cod_marcax'  => 853, 'nom_marcax' => 'PEXMA', 'ind_estado' => 1),
			227 => array('cod_marcax'  => 852, 'nom_marcax' => 'PASSO', 'ind_estado' => 1),
			228 => array('cod_marcax'  => 851, 'nom_marcax' => 'ORION', 'ind_estado' => 1),
			229 => array('cod_marcax'  => 850, 'nom_marcax' => 'ORANGE COUNTY CHOPPERS', 'ind_estado' => 1),
			230 => array('cod_marcax'  => 849, 'nom_marcax' => 'NYK', 'ind_estado' => 1),
			231 => array('cod_marcax'  => 848, 'nom_marcax' => 'NEW HYSTER', 'ind_estado' => 1),
			232 => array('cod_marcax'  => 847, 'nom_marcax' => 'NEUTRAL', 'ind_estado' => 1),
			233 => array('cod_marcax'  => 846, 'nom_marcax' => 'N.S.U', 'ind_estado' => 1),
			234 => array('cod_marcax'  => 845, 'nom_marcax' => 'MUHCK', 'ind_estado' => 1),
			235 => array('cod_marcax'  => 844, 'nom_marcax' => 'MUDAN', 'ind_estado' => 1),
			236 => array('cod_marcax'  => 843, 'nom_marcax' => 'MOTOCARRIER', 'ind_estado' => 1),
			237 => array('cod_marcax'  => 842, 'nom_marcax' => 'MONIKA', 'ind_estado' => 1),
			238 => array('cod_marcax'  => 841, 'nom_marcax' => 'MOBYLESTTE', 'ind_estado' => 1),
			239 => array('cod_marcax'  => 840, 'nom_marcax' => 'MNHCK', 'ind_estado' => 1),
			240 => array('cod_marcax'  => 839, 'nom_marcax' => 'MG MIDGET', 'ind_estado' => 1),
			241 => array('cod_marcax'  => 838, 'nom_marcax' => 'MAZAKI', 'ind_estado' => 1),
			242 => array('cod_marcax'  => 837, 'nom_marcax' => 'MAYFLOWER', 'ind_estado' => 1),
			243 => array('cod_marcax'  => 836, 'nom_marcax' => 'MAXWELL', 'ind_estado' => 1),
			244 => array('cod_marcax'  => 835, 'nom_marcax' => 'MASTER CRAFT', 'ind_estado' => 1),
			245 => array('cod_marcax'  => 834, 'nom_marcax' => 'MARQUASS', 'ind_estado' => 1),
			246 => array('cod_marcax'  => 833, 'nom_marcax' => 'MARCHETTI', 'ind_estado' => 1),
			247 => array('cod_marcax'  => 832, 'nom_marcax' => 'M.G.U', 'ind_estado' => 1),
			248 => array('cod_marcax'  => 831, 'nom_marcax' => 'LINGBEN', 'ind_estado' => 1),
			249 => array('cod_marcax'  => 830, 'nom_marcax' => 'LINDE', 'ind_estado' => 1),
			250 => array('cod_marcax'  => 829, 'nom_marcax' => 'LIBA MOTOR', 'ind_estado' => 1),
			251 => array('cod_marcax'  => 828, 'nom_marcax' => 'LIANMEI MOTOR', 'ind_estado' => 1),
			252 => array('cod_marcax'  => 827, 'nom_marcax' => 'LEY LAND', 'ind_estado' => 1),
			253 => array('cod_marcax'  => 826, 'nom_marcax' => 'LEE SCUSTÓN COACHES', 'ind_estado' => 1),
			254 => array('cod_marcax'  => 825, 'nom_marcax' => 'L.A.I', 'ind_estado' => 1),
			255 => array('cod_marcax'  => 824, 'nom_marcax' => 'KROSON SOPORTES', 'ind_estado' => 1),
			256 => array('cod_marcax'  => 823, 'nom_marcax' => 'KONTIO SISO', 'ind_estado' => 1),
			257 => array('cod_marcax'  => 822, 'nom_marcax' => 'KOMAR', 'ind_estado' => 1),
			258 => array('cod_marcax'  => 821, 'nom_marcax' => 'KARPETAN', 'ind_estado' => 1),
			259 => array('cod_marcax'  => 820, 'nom_marcax' => 'KANABIS', 'ind_estado' => 1),
			260 => array('cod_marcax'  => 819, 'nom_marcax' => 'JUNGHEINRICH', 'ind_estado' => 1),
			261 => array('cod_marcax'  => 818, 'nom_marcax' => 'JUMBO DE LLANTAS', 'ind_estado' => 1),
			262 => array('cod_marcax'  => 817, 'nom_marcax' => 'JIN JIAN', 'ind_estado' => 1),
			263 => array('cod_marcax'  => 816, 'nom_marcax' => 'ISLO', 'ind_estado' => 1),
			264 => array('cod_marcax'  => 815, 'nom_marcax' => 'IKARUS', 'ind_estado' => 1),
			265 => array('cod_marcax'  => 814, 'nom_marcax' => 'I.M.V', 'ind_estado' => 1),
			266 => array('cod_marcax'  => 813, 'nom_marcax' => 'HUSABERG', 'ind_estado' => 1),
			267 => array('cod_marcax'  => 812, 'nom_marcax' => 'HUPMOBILE', 'ind_estado' => 1),
			268 => array('cod_marcax'  => 811, 'nom_marcax' => 'HUAWIN', 'ind_estado' => 1),
			269 => array('cod_marcax'  => 810, 'nom_marcax' => 'HOSIN SOPORTER', 'ind_estado' => 1),
			270 => array('cod_marcax'  => 809, 'nom_marcax' => 'HESTIA', 'ind_estado' => 1),
			271 => array('cod_marcax'  => 808, 'nom_marcax' => 'HAOJUE', 'ind_estado' => 1),
			272 => array('cod_marcax'  => 807, 'nom_marcax' => 'HALLA', 'ind_estado' => 1),
			273 => array('cod_marcax'  => 806, 'nom_marcax' => 'GRUBER', 'ind_estado' => 1),
			274 => array('cod_marcax'  => 805, 'nom_marcax' => 'GREMLIN', 'ind_estado' => 1),
			275 => array('cod_marcax'  => 804, 'nom_marcax' => 'GRANE CARRIER', 'ind_estado' => 1),
			276 => array('cod_marcax'  => 803, 'nom_marcax' => 'GRAHAN PAUGE', 'ind_estado' => 1),
			277 => array('cod_marcax'  => 802, 'nom_marcax' => 'GOGOMOVIL', 'ind_estado' => 1),
			278 => array('cod_marcax'  => 801, 'nom_marcax' => 'GERLING', 'ind_estado' => 1),
			279 => array('cod_marcax'  => 800, 'nom_marcax' => 'FULDAMOBIL', 'ind_estado' => 1),
			280 => array('cod_marcax'  => 799, 'nom_marcax' => 'FRAZER', 'ind_estado' => 1),
			281 => array('cod_marcax'  => 798, 'nom_marcax' => 'FLEXIBLE', 'ind_estado' => 1),
			282 => array('cod_marcax'  => 797, 'nom_marcax' => 'FIBRAVAN', 'ind_estado' => 1),
			283 => array('cod_marcax'  => 796, 'nom_marcax' => 'FARSPEED', 'ind_estado' => 1),
			284 => array('cod_marcax'  => 795, 'nom_marcax' => 'FANTIC', 'ind_estado' => 1),
			285 => array('cod_marcax'  => 794, 'nom_marcax' => 'F.N', 'ind_estado' => 1),
			286 => array('cod_marcax'  => 793, 'nom_marcax' => 'EZGO', 'ind_estado' => 1),
			287 => array('cod_marcax'  => 792, 'nom_marcax' => 'E-TON', 'ind_estado' => 1),
			288 => array('cod_marcax'  => 791, 'nom_marcax' => 'EP', 'ind_estado' => 1),
			289 => array('cod_marcax'  => 790, 'nom_marcax' => 'EM', 'ind_estado' => 1),
			290 => array('cod_marcax'  => 789, 'nom_marcax' => 'ELEPHANT POWER', 'ind_estado' => 1),
			291 => array('cod_marcax'  => 788, 'nom_marcax' => 'EL SOL', 'ind_estado' => 1),
			292 => array('cod_marcax'  => 787, 'nom_marcax' => 'ECO CITI', 'ind_estado' => 1),
			293 => array('cod_marcax'  => 786, 'nom_marcax' => 'DTV', 'ind_estado' => 1),
			294 => array('cod_marcax'  => 785, 'nom_marcax' => 'DIVICO', 'ind_estado' => 1),
			295 => array('cod_marcax'  => 784, 'nom_marcax' => 'DEMAG', 'ind_estado' => 1),
			296 => array('cod_marcax'  => 783, 'nom_marcax' => 'DE LA HAYE', 'ind_estado' => 1),
			297 => array('cod_marcax'  => 782, 'nom_marcax' => 'DASHA', 'ind_estado' => 1),
			298 => array('cod_marcax'  => 781, 'nom_marcax' => 'DAIMLER BENZ', 'ind_estado' => 1),
			299 => array('cod_marcax'  => 780, 'nom_marcax' => 'DAF', 'ind_estado' => 1),
			300 => array('cod_marcax'  => 779, 'nom_marcax' => 'DACC', 'ind_estado' => 1),
			301 => array('cod_marcax'  => 778, 'nom_marcax' => 'CRUISERN', 'ind_estado' => 1),
			302 => array('cod_marcax'  => 777, 'nom_marcax' => 'CROSLEY', 'ind_estado' => 1),
			303 => array('cod_marcax'  => 776, 'nom_marcax' => 'CONSUL', 'ind_estado' => 1),
			304 => array('cod_marcax'  => 775, 'nom_marcax' => 'COLT LANCER', 'ind_estado' => 1),
			305 => array('cod_marcax'  => 774, 'nom_marcax' => 'CLAUSSON', 'ind_estado' => 1),
			306 => array('cod_marcax'  => 773, 'nom_marcax' => 'CHITUMA', 'ind_estado' => 1),
			307 => array('cod_marcax'  => 772, 'nom_marcax' => 'CHINA MOTORCYCLES', 'ind_estado' => 1),
			308 => array('cod_marcax'  => 771, 'nom_marcax' => 'CENTAURS', 'ind_estado' => 1),
			309 => array('cod_marcax'  => 770, 'nom_marcax' => 'CAMC', 'ind_estado' => 1),
			310 => array('cod_marcax'  => 769, 'nom_marcax' => 'C.C.C.', 'ind_estado' => 1),
			311 => array('cod_marcax'  => 768, 'nom_marcax' => 'BRISA', 'ind_estado' => 1),
			312 => array('cod_marcax'  => 767, 'nom_marcax' => 'BRAND', 'ind_estado' => 1),
			313 => array('cod_marcax'  => 766, 'nom_marcax' => 'BOSA BOSHIE NIKE', 'ind_estado' => 1),
			314 => array('cod_marcax'  => 765, 'nom_marcax' => 'BENELLI', 'ind_estado' => 1),
			315 => array('cod_marcax'  => 764, 'nom_marcax' => 'BANTAM', 'ind_estado' => 1),
			316 => array('cod_marcax'  => 763, 'nom_marcax' => 'BAKER', 'ind_estado' => 1),
			317 => array('cod_marcax'  => 762, 'nom_marcax' => 'BAIKANCAR', 'ind_estado' => 1),
			318 => array('cod_marcax'  => 761, 'nom_marcax' => 'AYCO ZONGSHEN', 'ind_estado' => 1),
			319 => array('cod_marcax'  => 760, 'nom_marcax' => 'AUTOKRAFT', 'ind_estado' => 1),
			320 => array('cod_marcax'  => 759, 'nom_marcax' => 'ASPT', 'ind_estado' => 1),
			321 => array('cod_marcax'  => 758, 'nom_marcax' => 'ARABELLA', 'ind_estado' => 1),
			322 => array('cod_marcax'  => 757, 'nom_marcax' => 'APOLLO', 'ind_estado' => 1),
			323 => array('cod_marcax'  => 756, 'nom_marcax' => 'AMPLE', 'ind_estado' => 1),
			324 => array('cod_marcax'  => 755, 'nom_marcax' => 'AMPHICAR', 'ind_estado' => 1),
			325 => array('cod_marcax'  => 754, 'nom_marcax' => 'ALVIS', 'ind_estado' => 1),
			326 => array('cod_marcax'  => 753, 'nom_marcax' => 'ALFARO', 'ind_estado' => 1),
			327 => array('cod_marcax'  => 752, 'nom_marcax' => 'AG', 'ind_estado' => 1),
			328 => array('cod_marcax'  => 751, 'nom_marcax' => 'AC', 'ind_estado' => 1),
			329 => array('cod_marcax'  => 750, 'nom_marcax' => 'MASERATI', 'ind_estado' => 1),
			330 => array('cod_marcax'  => 749, 'nom_marcax' => 'GO KART', 'ind_estado' => 1),
			331 => array('cod_marcax'  => 748, 'nom_marcax' => 'CEZET', 'ind_estado' => 1),
			332 => array('cod_marcax'  => 747, 'nom_marcax' => 'DANUVIA', 'ind_estado' => 1),
			333 => array('cod_marcax'  => 746, 'nom_marcax' => 'CZ', 'ind_estado' => 1),
			334 => array('cod_marcax'  => 745, 'nom_marcax' => 'ZUNDAPP', 'ind_estado' => 1),
			335 => array('cod_marcax'  => 744, 'nom_marcax' => 'HORNET', 'ind_estado' => 1),
			336 => array('cod_marcax'  => 743, 'nom_marcax' => 'VOSJOB', 'ind_estado' => 1),
			337 => array('cod_marcax'  => 742, 'nom_marcax' => 'VERKHOVINA', 'ind_estado' => 1),
			338 => array('cod_marcax'  => 741, 'nom_marcax' => 'TOWMOTOR', 'ind_estado' => 1),
			339 => array('cod_marcax'  => 740, 'nom_marcax' => 'TENNAN', 'ind_estado' => 1),
			340 => array('cod_marcax'  => 739, 'nom_marcax' => 'TCUMSON', 'ind_estado' => 1),
			341 => array('cod_marcax'  => 738, 'nom_marcax' => 'STAVOSTROJ', 'ind_estado' => 1),
			342 => array('cod_marcax'  => 737, 'nom_marcax' => 'PHW', 'ind_estado' => 1),
			343 => array('cod_marcax'  => 736, 'nom_marcax' => 'OSSA', 'ind_estado' => 1),
			344 => array('cod_marcax'  => 735, 'nom_marcax' => 'MOBILIFT', 'ind_estado' => 1),
			345 => array('cod_marcax'  => 734, 'nom_marcax' => 'LIMA', 'ind_estado' => 1),
			346 => array('cod_marcax'  => 733, 'nom_marcax' => 'L.R.', 'ind_estado' => 1),
			347 => array('cod_marcax'  => 732, 'nom_marcax' => 'KAELBLE', 'ind_estado' => 1),
			348 => array('cod_marcax'  => 731, 'nom_marcax' => 'JINGPIN', 'ind_estado' => 1),
			349 => array('cod_marcax'  => 730, 'nom_marcax' => 'JINBEI', 'ind_estado' => 1),
			350 => array('cod_marcax'  => 729, 'nom_marcax' => 'DESTA', 'ind_estado' => 1),
			351 => array('cod_marcax'  => 728, 'nom_marcax' => 'DELKRON', 'ind_estado' => 1),
			352 => array('cod_marcax'  => 727, 'nom_marcax' => 'CCITTA REBEL', 'ind_estado' => 1),
			353 => array('cod_marcax'  => 726, 'nom_marcax' => 'TADANO', 'ind_estado' => 1),
			354 => array('cod_marcax'  => 725, 'nom_marcax' => 'PIQUERSA', 'ind_estado' => 1),
			355 => array('cod_marcax'  => 724, 'nom_marcax' => 'PINZ GAUER', 'ind_estado' => 1),
			356 => array('cod_marcax'  => 722, 'nom_marcax' => 'PANZER', 'ind_estado' => 1),
			357 => array('cod_marcax'  => 720, 'nom_marcax' => 'MATBRO', 'ind_estado' => 1),
			358 => array('cod_marcax'  => 719, 'nom_marcax' => 'MARINI', 'ind_estado' => 1),
			359 => array('cod_marcax'  => 718, 'nom_marcax' => 'LINK BELT', 'ind_estado' => 1),
			360 => array('cod_marcax'  => 717, 'nom_marcax' => 'LEE BOY', 'ind_estado' => 1),
			361 => array('cod_marcax'  => 716, 'nom_marcax' => 'KOBELCO', 'ind_estado' => 1),
			362 => array('cod_marcax'  => 715, 'nom_marcax' => 'KATO', 'ind_estado' => 1),
			363 => array('cod_marcax'  => 714, 'nom_marcax' => 'ISEKI', 'ind_estado' => 1),
			364 => array('cod_marcax'  => 713, 'nom_marcax' => 'FURUKAWA', 'ind_estado' => 1),
			365 => array('cod_marcax'  => 712, 'nom_marcax' => 'BELL', 'ind_estado' => 1),
			366 => array('cod_marcax'  => 711, 'nom_marcax' => 'RHINO', 'ind_estado' => 1),
			367 => array('cod_marcax'  => 709, 'nom_marcax' => 'BUGGY', 'ind_estado' => 1),
			368 => array('cod_marcax'  => 708, 'nom_marcax' => 'CARBONER', 'ind_estado' => 1),
			369 => array('cod_marcax'  => 705, 'nom_marcax' => 'ZUNK', 'ind_estado' => 1),
			370 => array('cod_marcax'  => 704, 'nom_marcax' => 'ZODIAC', 'ind_estado' => 1),
			371 => array('cod_marcax'  => 703, 'nom_marcax' => 'ZIP STAR', 'ind_estado' => 1),
			372 => array('cod_marcax'  => 702, 'nom_marcax' => 'ZIGMA', 'ind_estado' => 1),
			373 => array('cod_marcax'  => 701, 'nom_marcax' => 'ZID', 'ind_estado' => 1),
			374 => array('cod_marcax'  => 700, 'nom_marcax' => 'ZHENG LI', 'ind_estado' => 1),
			375 => array('cod_marcax'  => 699, 'nom_marcax' => 'ZHEJIANG HANGCHA', 'ind_estado' => 1),
			376 => array('cod_marcax'  => 698, 'nom_marcax' => 'ZETOR', 'ind_estado' => 1),
			377 => array('cod_marcax'  => 697, 'nom_marcax' => 'ZEPHYR', 'ind_estado' => 1),
			378 => array('cod_marcax'  => 696, 'nom_marcax' => 'YUMBO', 'ind_estado' => 1),
			379 => array('cod_marcax'  => 695, 'nom_marcax' => 'YUEJIN', 'ind_estado' => 1),
			380 => array('cod_marcax'  => 694, 'nom_marcax' => 'YUANDA', 'ind_estado' => 1),
			381 => array('cod_marcax'  => 693, 'nom_marcax' => 'YONKANG XINGYUE', 'ind_estado' => 1),
			382 => array('cod_marcax'  => 692, 'nom_marcax' => 'YIBEN', 'ind_estado' => 1),
			383 => array('cod_marcax'  => 691, 'nom_marcax' => 'YAMASAKY', 'ind_estado' => 1),
			384 => array('cod_marcax'  => 690, 'nom_marcax' => 'YALE', 'ind_estado' => 1),
			385 => array('cod_marcax'  => 689, 'nom_marcax' => 'XCMG', 'ind_estado' => 1),
			386 => array('cod_marcax'  => 688, 'nom_marcax' => 'WKT', 'ind_estado' => 1),
			387 => array('cod_marcax'  => 687, 'nom_marcax' => 'WESTERN STAR', 'ind_estado' => 1),
			388 => array('cod_marcax'  => 686, 'nom_marcax' => 'WARZAWA', 'ind_estado' => 1),
			389 => array('cod_marcax'  => 685, 'nom_marcax' => 'VOGELE', 'ind_estado' => 1),
			390 => array('cod_marcax'  => 684, 'nom_marcax' => 'VISAIL', 'ind_estado' => 1),
			391 => array('cod_marcax'  => 683, 'nom_marcax' => 'VALTRA', 'ind_estado' => 1),
			392 => array('cod_marcax'  => 682, 'nom_marcax' => 'VALMET', 'ind_estado' => 1),
			393 => array('cod_marcax'  => 681, 'nom_marcax' => 'USA MOTORS', 'ind_estado' => 1),
			394 => array('cod_marcax'  => 680, 'nom_marcax' => 'UNIVERSAL', 'ind_estado' => 1),
			395 => array('cod_marcax'  => 679, 'nom_marcax' => 'UNIMOG', 'ind_estado' => 1),
			396 => array('cod_marcax'  => 678, 'nom_marcax' => 'TRIWIL', 'ind_estado' => 1),
			397 => array('cod_marcax'  => 677, 'nom_marcax' => 'TONARO', 'ind_estado' => 1),
			398 => array('cod_marcax'  => 676, 'nom_marcax' => 'THUNDER CYCLE DESIGN', 'ind_estado' => 1),
			399 => array('cod_marcax'  => 675, 'nom_marcax' => 'TEREX', 'ind_estado' => 1),
			400 => array('cod_marcax'  => 674, 'nom_marcax' => 'TCM', 'ind_estado' => 1),
			401 => array('cod_marcax'  => 673, 'nom_marcax' => 'SUNDIRO', 'ind_estado' => 1),
			402 => array('cod_marcax'  => 672, 'nom_marcax' => 'SUM', 'ind_estado' => 1),
			403 => array('cod_marcax'  => 671, 'nom_marcax' => 'SUKIDA', 'ind_estado' => 1),
			404 => array('cod_marcax'  => 670, 'nom_marcax' => 'STEYR DAIMLER PUCH', 'ind_estado' => 1),
			405 => array('cod_marcax'  => 669, 'nom_marcax' => 'SMC', 'ind_estado' => 1),
			406 => array('cod_marcax'  => 668, 'nom_marcax' => 'SKYMAX', 'ind_estado' => 1),
			407 => array('cod_marcax'  => 667, 'nom_marcax' => 'SKINGO', 'ind_estado' => 1),
			408 => array('cod_marcax'  => 666, 'nom_marcax' => 'SINOTRUK HOWO', 'ind_estado' => 1),
			409 => array('cod_marcax'  => 665, 'nom_marcax' => 'SHINERAY', 'ind_estado' => 1),
			410 => array('cod_marcax'  => 664, 'nom_marcax' => 'SHANGHAI', 'ind_estado' => 1),
			411 => array('cod_marcax'  => 663, 'nom_marcax' => 'SAURON', 'ind_estado' => 1),
			412 => array('cod_marcax'  => 661, 'nom_marcax' => 'SANFENG', 'ind_estado' => 1),
			413 => array('cod_marcax'  => 660, 'nom_marcax' => 'SAME', 'ind_estado' => 1),
			414 => array('cod_marcax'  => 659, 'nom_marcax' => 'ROSCO', 'ind_estado' => 1),
			415 => array('cod_marcax'  => 658, 'nom_marcax' => 'ROBUR', 'ind_estado' => 1),
			416 => array('cod_marcax'  => 657, 'nom_marcax' => 'RLX', 'ind_estado' => 1),
			417 => array('cod_marcax'  => 656, 'nom_marcax' => 'REVTECH', 'ind_estado' => 1),
			418 => array('cod_marcax'  => 655, 'nom_marcax' => 'RANGE ROVER', 'ind_estado' => 1),
			419 => array('cod_marcax'  => 654, 'nom_marcax' => 'RAMIREZ', 'ind_estado' => 1),
			420 => array('cod_marcax'  => 653, 'nom_marcax' => 'QIANJIANG', 'ind_estado' => 1),
			421 => array('cod_marcax'  => 652, 'nom_marcax' => 'POWERMAX', 'ind_estado' => 1),
			422 => array('cod_marcax'  => 651, 'nom_marcax' => 'POCLAIN', 'ind_estado' => 1),
			423 => array('cod_marcax'  => 650, 'nom_marcax' => 'PIAGGIO ZONGSHEN', 'ind_estado' => 1),
			424 => array('cod_marcax'  => 649, 'nom_marcax' => 'PETTIBONE', 'ind_estado' => 1),
			425 => array('cod_marcax'  => 648, 'nom_marcax' => 'PARCE', 'ind_estado' => 1),
			426 => array('cod_marcax'  => 647, 'nom_marcax' => 'P Y H', 'ind_estado' => 1),
			427 => array('cod_marcax'  => 646, 'nom_marcax' => 'OSHKOSH', 'ind_estado' => 1),
			428 => array('cod_marcax'  => 645, 'nom_marcax' => 'OAKLAND', 'ind_estado' => 1),
			429 => array('cod_marcax'  => 644, 'nom_marcax' => 'NUFFIELD', 'ind_estado' => 1),
			430 => array('cod_marcax'  => 643, 'nom_marcax' => 'NON PLUS ULTRA', 'ind_estado' => 1),
			431 => array('cod_marcax'  => 642, 'nom_marcax' => 'NIMBUS', 'ind_estado' => 1),
			432 => array('cod_marcax'  => 641, 'nom_marcax' => 'NEW KING', 'ind_estado' => 1),
			433 => array('cod_marcax'  => 640, 'nom_marcax' => 'NEW HOLLAN', 'ind_estado' => 1),
			434 => array('cod_marcax'  => 639, 'nom_marcax' => 'MV AGUSTA', 'ind_estado' => 1),
			435 => array('cod_marcax'  => 638, 'nom_marcax' => 'MOTOBECAME', 'ind_estado' => 1),
			436 => array('cod_marcax'  => 637, 'nom_marcax' => 'MINI', 'ind_estado' => 1),
			437 => array('cod_marcax'  => 636, 'nom_marcax' => 'MGB', 'ind_estado' => 1),
			438 => array('cod_marcax'  => 635, 'nom_marcax' => 'META', 'ind_estado' => 1),
			439 => array('cod_marcax'  => 634, 'nom_marcax' => 'MERLO', 'ind_estado' => 1),
			440 => array('cod_marcax'  => 633, 'nom_marcax' => 'MC CORMICK', 'ind_estado' => 1),
			441 => array('cod_marcax'  => 631, 'nom_marcax' => 'MATCHELSS', 'ind_estado' => 1),
			442 => array('cod_marcax'  => 630, 'nom_marcax' => 'MASEY FERGUSON', 'ind_estado' => 1),
			443 => array('cod_marcax'  => 629, 'nom_marcax' => 'MARUTI', 'ind_estado' => 1),
			444 => array('cod_marcax'  => 628, 'nom_marcax' => 'MARMON', 'ind_estado' => 1),
			445 => array('cod_marcax'  => 627, 'nom_marcax' => 'MANCO', 'ind_estado' => 1),
			446 => array('cod_marcax'  => 626, 'nom_marcax' => 'MADVAC', 'ind_estado' => 1),
			447 => array('cod_marcax'  => 625, 'nom_marcax' => 'LORAIN', 'ind_estado' => 1),
			448 => array('cod_marcax'  => 624, 'nom_marcax' => 'LMX', 'ind_estado' => 1),
			449 => array('cod_marcax'  => 623, 'nom_marcax' => 'LIUGONG', 'ind_estado' => 1),
			450 => array('cod_marcax'  => 622, 'nom_marcax' => 'LITTLE GIANT', 'ind_estado' => 1),
			451 => array('cod_marcax'  => 621, 'nom_marcax' => 'LINCOLN', 'ind_estado' => 1),
			452 => array('cod_marcax'  => 620, 'nom_marcax' => 'KRUPP', 'ind_estado' => 1),
			453 => array('cod_marcax'  => 619, 'nom_marcax' => 'KRAZ', 'ind_estado' => 1),
			454 => array('cod_marcax'  => 618, 'nom_marcax' => 'KONCEO', 'ind_estado' => 1),
			455 => array('cod_marcax'  => 617, 'nom_marcax' => 'KOMATSU', 'ind_estado' => 1),
			456 => array('cod_marcax'  => 616, 'nom_marcax' => 'KITOMI', 'ind_estado' => 1),
			457 => array('cod_marcax'  => 614, 'nom_marcax' => 'KING LINFT', 'ind_estado' => 1),
			458 => array('cod_marcax'  => 613, 'nom_marcax' => 'KAZUMA', 'ind_estado' => 1),
			459 => array('cod_marcax'  => 612, 'nom_marcax' => 'KALMAR', 'ind_estado' => 1),
			460 => array('cod_marcax'  => 611, 'nom_marcax' => 'KAISER', 'ind_estado' => 1),
			461 => array('cod_marcax'  => 609, 'nom_marcax' => 'JIRY SISU', 'ind_estado' => 1),
			462 => array('cod_marcax'  => 608, 'nom_marcax' => 'JINGLONG', 'ind_estado' => 1),
			463 => array('cod_marcax'  => 607, 'nom_marcax' => 'JIANGXI CAMPELL CO.', 'ind_estado' => 1),
			464 => array('cod_marcax'  => 606, 'nom_marcax' => 'JIANGSU KINROAD XINTIAN', 'ind_estado' => 1),
			465 => array('cod_marcax'  => 605, 'nom_marcax' => 'JIANGNAN GLOW', 'ind_estado' => 1),
			466 => array('cod_marcax'  => 604, 'nom_marcax' => 'JIANGLING', 'ind_estado' => 1),
			467 => array('cod_marcax'  => 603, 'nom_marcax' => 'JIANG CHANGHE', 'ind_estado' => 1),
			468 => array('cod_marcax'  => 602, 'nom_marcax' => 'JHONSTON', 'ind_estado' => 1),
			469 => array('cod_marcax'  => 601, 'nom_marcax' => 'JHON DEERE', 'ind_estado' => 1),
			470 => array('cod_marcax'  => 600, 'nom_marcax' => 'JCB', 'ind_estado' => 1),
			471 => array('cod_marcax'  => 599, 'nom_marcax' => 'JAVELINI', 'ind_estado' => 1),
			472 => array('cod_marcax'  => 598, 'nom_marcax' => 'JAINSHE', 'ind_estado' => 1),
			473 => array('cod_marcax'  => 597, 'nom_marcax' => 'JACKEL', 'ind_estado' => 1),
			474 => array('cod_marcax'  => 596, 'nom_marcax' => 'INVICTUS MOTORS', 'ind_estado' => 1),
			475 => array('cod_marcax'  => 595, 'nom_marcax' => 'INGERSOLL RAND', 'ind_estado' => 1),
			476 => array('cod_marcax'  => 594, 'nom_marcax' => 'INDIAN CHIEF', 'ind_estado' => 1),
			477 => array('cod_marcax'  => 593, 'nom_marcax' => 'INCALCU', 'ind_estado' => 1),
			478 => array('cod_marcax'  => 592, 'nom_marcax' => 'HYSTER', 'ind_estado' => 1),
			479 => array('cod_marcax'  => 591, 'nom_marcax' => 'HUMMER ZONGSHEN', 'ind_estado' => 1),
			480 => array('cod_marcax'  => 590, 'nom_marcax' => 'HUBER', 'ind_estado' => 1),
			481 => array('cod_marcax'  => 589, 'nom_marcax' => 'HITACHI', 'ind_estado' => 1),
			482 => array('cod_marcax'  => 588, 'nom_marcax' => 'HISTER', 'ind_estado' => 1),
			483 => array('cod_marcax'  => 587, 'nom_marcax' => 'HILIGHT', 'ind_estado' => 1),
			484 => array('cod_marcax'  => 586, 'nom_marcax' => 'HERRAGRO', 'ind_estado' => 1),
			485 => array('cod_marcax'  => 585, 'nom_marcax' => 'HELI', 'ind_estado' => 1),
			486 => array('cod_marcax'  => 584, 'nom_marcax' => 'HARMON', 'ind_estado' => 1),
			487 => array('cod_marcax'  => 583, 'nom_marcax' => 'HARDLAND', 'ind_estado' => 1),
			488 => array('cod_marcax'  => 581, 'nom_marcax' => 'GROVE', 'ind_estado' => 1),
			489 => array('cod_marcax'  => 580, 'nom_marcax' => 'GRAM', 'ind_estado' => 1),
			490 => array('cod_marcax'  => 578, 'nom_marcax' => 'GOLDEN DRAGON', 'ind_estado' => 1),
			491 => array('cod_marcax'  => 577, 'nom_marcax' => 'GHA-2', 'ind_estado' => 1),
			492 => array('cod_marcax'  => 576, 'nom_marcax' => 'GENERAL', 'ind_estado' => 1),
			493 => array('cod_marcax'  => 575, 'nom_marcax' => 'GAZELLE', 'ind_estado' => 1),
			494 => array('cod_marcax'  => 574, 'nom_marcax' => 'GALION', 'ind_estado' => 1),
			495 => array('cod_marcax'  => 573, 'nom_marcax' => 'FYM', 'ind_estado' => 1),
			496 => array('cod_marcax'  => 572, 'nom_marcax' => 'FWD', 'ind_estado' => 1),
			497 => array('cod_marcax'  => 571, 'nom_marcax' => 'FUTURE', 'ind_estado' => 1),
			498 => array('cod_marcax'  => 570, 'nom_marcax' => 'FORMULA', 'ind_estado' => 1),
			499 => array('cod_marcax'  => 569, 'nom_marcax' => 'FONA', 'ind_estado' => 1),
			500 => array('cod_marcax'  => 568, 'nom_marcax' => 'FIORI', 'ind_estado' => 1),
			501 => array('cod_marcax'  => 567, 'nom_marcax' => 'FIAT ALLIS', 'ind_estado' => 1),
			502 => array('cod_marcax'  => 566, 'nom_marcax' => 'FENCHI', 'ind_estado' => 1),
			503 => array('cod_marcax'  => 564, 'nom_marcax' => 'FEDERAL', 'ind_estado' => 1),
			504 => array('cod_marcax'  => 563, 'nom_marcax' => 'FAMY', 'ind_estado' => 1),
			505 => array('cod_marcax'  => 562, 'nom_marcax' => 'FAILING', 'ind_estado' => 1),
			506 => array('cod_marcax'  => 561, 'nom_marcax' => 'EZLIFE', 'ind_estado' => 1),
			507 => array('cod_marcax'  => 560, 'nom_marcax' => 'EXPRESS', 'ind_estado' => 1),
			508 => array('cod_marcax'  => 559, 'nom_marcax' => 'EXCELSIOR', 'ind_estado' => 1),
			509 => array('cod_marcax'  => 558, 'nom_marcax' => 'EVO', 'ind_estado' => 1),
			510 => array('cod_marcax'  => 557, 'nom_marcax' => 'EUCLID', 'ind_estado' => 1),
			511 => array('cod_marcax'  => 556, 'nom_marcax' => 'ERNEST GRUBER', 'ind_estado' => 1),
			512 => array('cod_marcax'  => 555, 'nom_marcax' => 'ENERGY', 'ind_estado' => 1),
			513 => array('cod_marcax'  => 554, 'nom_marcax' => 'ENCAVA', 'ind_estado' => 1),
			514 => array('cod_marcax'  => 553, 'nom_marcax' => 'ELGIN', 'ind_estado' => 1),
			515 => array('cod_marcax'  => 552, 'nom_marcax' => 'ELECTRIC STAR ATV ENERGY', 'ind_estado' => 1),
			516 => array('cod_marcax'  => 551, 'nom_marcax' => 'EBTELECTRIC', 'ind_estado' => 1),
			517 => array('cod_marcax'  => 550, 'nom_marcax' => 'EASTMAN', 'ind_estado' => 1),
			518 => array('cod_marcax'  => 549, 'nom_marcax' => 'EAGLE AMC', 'ind_estado' => 1),
			519 => array('cod_marcax'  => 548, 'nom_marcax' => 'EAGLE', 'ind_estado' => 1),
			520 => array('cod_marcax'  => 547, 'nom_marcax' => 'E.D. ETNYRE', 'ind_estado' => 1),
			521 => array('cod_marcax'  => 546, 'nom_marcax' => 'DYNACOLT', 'ind_estado' => 1),
			522 => array('cod_marcax'  => 545, 'nom_marcax' => 'DUST', 'ind_estado' => 1),
			523 => array('cod_marcax'  => 544, 'nom_marcax' => 'DRESSER', 'ind_estado' => 1),
			524 => array('cod_marcax'  => 543, 'nom_marcax' => 'DOMINGUEZ', 'ind_estado' => 1),
			525 => array('cod_marcax'  => 542, 'nom_marcax' => 'DINAPAC', 'ind_estado' => 1),
			526 => array('cod_marcax'  => 541, 'nom_marcax' => 'DIECI', 'ind_estado' => 1),
			527 => array('cod_marcax'  => 540, 'nom_marcax' => 'DIAMOND', 'ind_estado' => 1),
			528 => array('cod_marcax'  => 539, 'nom_marcax' => 'DAYUN', 'ind_estado' => 1),
			529 => array('cod_marcax'  => 538, 'nom_marcax' => 'DAVID BROWN', 'ind_estado' => 1),
			530 => array('cod_marcax'  => 537, 'nom_marcax' => 'CUSTOM CHROME', 'ind_estado' => 1),
			531 => array('cod_marcax'  => 536, 'nom_marcax' => 'CSEPEL-CUMMINS', 'ind_estado' => 1),
			532 => array('cod_marcax'  => 535, 'nom_marcax' => 'CROWN', 'ind_estado' => 1),
			533 => array('cod_marcax'  => 534, 'nom_marcax' => 'CONCORD', 'ind_estado' => 1),
			534 => array('cod_marcax'  => 533, 'nom_marcax' => 'COMET', 'ind_estado' => 1),
			535 => array('cod_marcax'  => 532, 'nom_marcax' => 'COMANDO', 'ind_estado' => 1),
			536 => array('cod_marcax'  => 531, 'nom_marcax' => 'COLOMBIANA DE CHASISES', 'ind_estado' => 1),
			537 => array('cod_marcax'  => 530, 'nom_marcax' => 'CLUB CAR', 'ind_estado' => 1),
			538 => array('cod_marcax'  => 529, 'nom_marcax' => 'CLARCK', 'ind_estado' => 1),
			539 => array('cod_marcax'  => 528, 'nom_marcax' => 'CICLONE USA', 'ind_estado' => 1),
			540 => array('cod_marcax'  => 527, 'nom_marcax' => 'CHONGQUING YUAN', 'ind_estado' => 1),
			541 => array('cod_marcax'  => 526, 'nom_marcax' => 'CHONGQING ZONGSHEN', 'ind_estado' => 1),
			542 => array('cod_marcax'  => 525, 'nom_marcax' => 'CHINSU', 'ind_estado' => 1),
			543 => array('cod_marcax'  => 524, 'nom_marcax' => 'CHARMING', 'ind_estado' => 1),
			544 => array('cod_marcax'  => 523, 'nom_marcax' => 'CHARLY', 'ind_estado' => 1),
			545 => array('cod_marcax'  => 522, 'nom_marcax' => 'CHANGLIN', 'ind_estado' => 1),
			546 => array('cod_marcax'  => 521, 'nom_marcax' => 'CHAMPION', 'ind_estado' => 1),
			547 => array('cod_marcax'  => 520, 'nom_marcax' => 'CATFLYER', 'ind_estado' => 1),
			548 => array('cod_marcax'  => 519, 'nom_marcax' => 'CATERPILLAR', 'ind_estado' => 1),
			549 => array('cod_marcax'  => 518, 'nom_marcax' => 'CASE', 'ind_estado' => 1),
			550 => array('cod_marcax'  => 517, 'nom_marcax' => 'CARTER BROTHERS', 'ind_estado' => 1),
			551 => array('cod_marcax'  => 516, 'nom_marcax' => 'CARIBE', 'ind_estado' => 1),
			552 => array('cod_marcax'  => 515, 'nom_marcax' => 'CAPACITY', 'ind_estado' => 1),
			553 => array('cod_marcax'  => 513, 'nom_marcax' => 'CAMECO', 'ind_estado' => 1),
			554 => array('cod_marcax'  => 512, 'nom_marcax' => 'BUGENI', 'ind_estado' => 1),
			555 => array('cod_marcax'  => 511, 'nom_marcax' => 'BUCYRUS', 'ind_estado' => 1),
			556 => array('cod_marcax'  => 510, 'nom_marcax' => 'BRONTO', 'ind_estado' => 1),
			557 => array('cod_marcax'  => 509, 'nom_marcax' => 'BRIDGE', 'ind_estado' => 1),
			558 => array('cod_marcax'  => 508, 'nom_marcax' => 'BOUSER', 'ind_estado' => 1),
			559 => array('cod_marcax'  => 507, 'nom_marcax' => 'BONSER', 'ind_estado' => 1),
			560 => array('cod_marcax'  => 506, 'nom_marcax' => 'BODYWORK', 'ind_estado' => 1),
			561 => array('cod_marcax'  => 505, 'nom_marcax' => 'BOBCAT', 'ind_estado' => 1),
			562 => array('cod_marcax'  => 504, 'nom_marcax' => 'BLUE STONE', 'ind_estado' => 1),
			563 => array('cod_marcax'  => 503, 'nom_marcax' => 'BLAW KNOX', 'ind_estado' => 1),
			564 => array('cod_marcax'  => 502, 'nom_marcax' => 'BIMOTA', 'ind_estado' => 1),
			565 => array('cod_marcax'  => 501, 'nom_marcax' => 'BIANCHI', 'ind_estado' => 1),
			566 => array('cod_marcax'  => 500, 'nom_marcax' => 'BETTER', 'ind_estado' => 1),
			567 => array('cod_marcax'  => 499, 'nom_marcax' => 'BETA', 'ind_estado' => 1),
			568 => array('cod_marcax'  => 498, 'nom_marcax' => 'BAW', 'ind_estado' => 1),
			569 => array('cod_marcax'  => 497, 'nom_marcax' => 'BAUKEMA', 'ind_estado' => 1),
			570 => array('cod_marcax'  => 496, 'nom_marcax' => 'BASHAN', 'ind_estado' => 1),
			571 => array('cod_marcax'  => 495, 'nom_marcax' => 'BARBER GREENE', 'ind_estado' => 1),
			572 => array('cod_marcax'  => 494, 'nom_marcax' => 'BAODIAO', 'ind_estado' => 1),
			573 => array('cod_marcax'  => 493, 'nom_marcax' => 'BACCIO', 'ind_estado' => 1),
			574 => array('cod_marcax'  => 492, 'nom_marcax' => 'ASTRA', 'ind_estado' => 1),
			575 => array('cod_marcax'  => 491, 'nom_marcax' => 'APELCO GEN-MTO', 'ind_estado' => 1),
			576 => array('cod_marcax'  => 490, 'nom_marcax' => 'AP PIAGGIO', 'ind_estado' => 1),
			577 => array('cod_marcax'  => 489, 'nom_marcax' => 'AMW', 'ind_estado' => 1),
			578 => array('cod_marcax'  => 488, 'nom_marcax' => 'AMM', 'ind_estado' => 1),
			579 => array('cod_marcax'  => 487, 'nom_marcax' => 'ALPS', 'ind_estado' => 1),
			580 => array('cod_marcax'  => 486, 'nom_marcax' => 'ALLIS CHALMERS', 'ind_estado' => 1),
			581 => array('cod_marcax'  => 485, 'nom_marcax' => 'ALLAD', 'ind_estado' => 1),
			582 => array('cod_marcax'  => 484, 'nom_marcax' => 'ADDO', 'ind_estado' => 1),
			583 => array('cod_marcax'  => 483, 'nom_marcax' => 'ACM-ZHONG', 'ind_estado' => 1),
			584 => array('cod_marcax'  => 482, 'nom_marcax' => 'ACE MOTOR', 'ind_estado' => 1),
			585 => array('cod_marcax'  => 481, 'nom_marcax' => 'ACE', 'ind_estado' => 1),
			586 => array('cod_marcax'  => 480, 'nom_marcax' => 'ACCESS', 'ind_estado' => 1),
			587 => array('cod_marcax'  => 479, 'nom_marcax' => 'A.J.S', 'ind_estado' => 1),
			588 => array('cod_marcax'  => 478, 'nom_marcax' => 'XINKAI', 'ind_estado' => 1),
			589 => array('cod_marcax'  => 477, 'nom_marcax' => 'WUZHENG', 'ind_estado' => 1),
			590 => array('cod_marcax'  => 476, 'nom_marcax' => 'WORKMAN', 'ind_estado' => 1),
			591 => array('cod_marcax'  => 475, 'nom_marcax' => 'TX MOTORS', 'ind_estado' => 1),
			592 => array('cod_marcax'  => 474, 'nom_marcax' => 'TELCOLINE', 'ind_estado' => 1),
			593 => array('cod_marcax'  => 473, 'nom_marcax' => 'TALON', 'ind_estado' => 1),
			594 => array('cod_marcax'  => 472, 'nom_marcax' => 'SHIJIAZHUANG', 'ind_estado' => 1),
			595 => array('cod_marcax'  => 471, 'nom_marcax' => 'REBELLIN', 'ind_estado' => 1),
			596 => array('cod_marcax'  => 470, 'nom_marcax' => 'NIKITA', 'ind_estado' => 1),
			597 => array('cod_marcax'  => 469, 'nom_marcax' => 'MOTO MORINI', 'ind_estado' => 1),
			598 => array('cod_marcax'  => 468, 'nom_marcax' => 'KYNLON', 'ind_estado' => 1),
			599 => array('cod_marcax'  => 467, 'nom_marcax' => 'JIN JIN', 'ind_estado' => 1),
			600 => array('cod_marcax'  => 466, 'nom_marcax' => 'JIANG', 'ind_estado' => 1),
			601 => array('cod_marcax'  => 465, 'nom_marcax' => 'IOTA', 'ind_estado' => 1),
			602 => array('cod_marcax'  => 464, 'nom_marcax' => 'GUZZI', 'ind_estado' => 1),
			603 => array('cod_marcax'  => 463, 'nom_marcax' => 'GONOW', 'ind_estado' => 1),
			604 => array('cod_marcax'  => 462, 'nom_marcax' => 'FUDEPAI', 'ind_estado' => 1),
			605 => array('cod_marcax'  => 461, 'nom_marcax' => 'EAGLE CARGO', 'ind_estado' => 1),
			606 => array('cod_marcax'  => 460, 'nom_marcax' => 'DAIFO', 'ind_estado' => 1),
			607 => array('cod_marcax'  => 459, 'nom_marcax' => 'BIG', 'ind_estado' => 1),
			608 => array('cod_marcax'  => 458, 'nom_marcax' => 'AKITA', 'ind_estado' => 1),
			609 => array('cod_marcax'  => 457, 'nom_marcax' => 'ITALIKA', 'ind_estado' => 1),
			610 => array('cod_marcax'  => 456, 'nom_marcax' => 'YIBEN-YBFALCON', 'ind_estado' => 1),
			611 => array('cod_marcax'  => 455, 'nom_marcax' => 'ZAHAV', 'ind_estado' => 1),
			612 => array('cod_marcax'  => 454, 'nom_marcax' => 'SQ RACING', 'ind_estado' => 1),
			613 => array('cod_marcax'  => 453, 'nom_marcax' => 'FAW', 'ind_estado' => 1),
			614 => array('cod_marcax'  => 452, 'nom_marcax' => 'OROMOTO', 'ind_estado' => 1),
			615 => array('cod_marcax'  => 451, 'nom_marcax' => 'EKA MOTORS', 'ind_estado' => 1),
			616 => array('cod_marcax'  => 450, 'nom_marcax' => 'ZNEN', 'ind_estado' => 1),
			617 => array('cod_marcax'  => 449, 'nom_marcax' => 'TIXXON', 'ind_estado' => 1),
			618 => array('cod_marcax'  => 448, 'nom_marcax' => 'DONG FENG', 'ind_estado' => 1),
			619 => array('cod_marcax'  => 447, 'nom_marcax' => 'ROSSETTI', 'ind_estado' => 1),
			620 => array('cod_marcax'  => 446, 'nom_marcax' => 'RIDER', 'ind_estado' => 1),
			621 => array('cod_marcax'  => 445, 'nom_marcax' => 'GWM', 'ind_estado' => 1),
			622 => array('cod_marcax'  => 444, 'nom_marcax' => 'FUXIANDA', 'ind_estado' => 1),
			623 => array('cod_marcax'  => 443, 'nom_marcax' => 'KANCHAO', 'ind_estado' => 1),
			624 => array('cod_marcax'  => 442, 'nom_marcax' => 'WCR', 'ind_estado' => 1),
			625 => array('cod_marcax'  => 441, 'nom_marcax' => 'TERRA JET', 'ind_estado' => 1),
			626 => array('cod_marcax'  => 440, 'nom_marcax' => 'PANTERA', 'ind_estado' => 1),
			627 => array('cod_marcax'  => 439, 'nom_marcax' => 'JINFENG', 'ind_estado' => 1),
			628 => array('cod_marcax'  => 438, 'nom_marcax' => 'WUYANG', 'ind_estado' => 1),
			629 => array('cod_marcax'  => 437, 'nom_marcax' => 'MD BIKES', 'ind_estado' => 1),
			630 => array('cod_marcax'  => 436, 'nom_marcax' => 'ATM', 'ind_estado' => 1),
			631 => array('cod_marcax'  => 435, 'nom_marcax' => 'BMA', 'ind_estado' => 1),
			632 => array('cod_marcax'  => 434, 'nom_marcax' => 'KANDI', 'ind_estado' => 1),
			633 => array('cod_marcax'  => 433, 'nom_marcax' => 'KINGLONG HIGER', 'ind_estado' => 1),
			634 => array('cod_marcax'  => 432, 'nom_marcax' => 'XINGUE', 'ind_estado' => 1),
			635 => array('cod_marcax'  => 431, 'nom_marcax' => 'CHANGFENG', 'ind_estado' => 1),
			636 => array('cod_marcax'  => 430, 'nom_marcax' => 'SUKYAMA', 'ind_estado' => 1),
			637 => array('cod_marcax'  => 429, 'nom_marcax' => 'ZOTYE', 'ind_estado' => 1),
			638 => array('cod_marcax'  => 428, 'nom_marcax' => 'ZHEJIANG LINGTIAN', 'ind_estado' => 1),
			639 => array('cod_marcax'  => 427, 'nom_marcax' => 'HAOMEN', 'ind_estado' => 1),
			640 => array('cod_marcax'  => 426, 'nom_marcax' => 'TVS', 'ind_estado' => 1),
			641 => array('cod_marcax'  => 425, 'nom_marcax' => 'HY MOTOR', 'ind_estado' => 1),
			642 => array('cod_marcax'  => 424, 'nom_marcax' => 'REX MOTO', 'ind_estado' => 1),
			643 => array('cod_marcax'  => 423, 'nom_marcax' => 'BOURGET', 'ind_estado' => 1),
			644 => array('cod_marcax'  => 422, 'nom_marcax' => 'FASTER 301 CHOIPERS', 'ind_estado' => 1),
			645 => array('cod_marcax'  => 421, 'nom_marcax' => 'MTK', 'ind_estado' => 1),
			646 => array('cod_marcax'  => 420, 'nom_marcax' => 'YAKIMA', 'ind_estado' => 1),
			647 => array('cod_marcax'  => 419, 'nom_marcax' => 'DFM', 'ind_estado' => 1),
			648 => array('cod_marcax'  => 418, 'nom_marcax' => 'SCOOTER', 'ind_estado' => 1),
			649 => array('cod_marcax'  => 417, 'nom_marcax' => 'POLARIS', 'ind_estado' => 1),
			650 => array('cod_marcax'  => 416, 'nom_marcax' => 'ZHUJIANG', 'ind_estado' => 1),
			651 => array('cod_marcax'  => 415, 'nom_marcax' => 'ZHEJIANG QIANJIANG', 'ind_estado' => 1),
			652 => array('cod_marcax'  => 414, 'nom_marcax' => 'HAMMER HEAD', 'ind_estado' => 1),
			653 => array('cod_marcax'  => 413, 'nom_marcax' => 'ACB', 'ind_estado' => 1),
			654 => array('cod_marcax'  => 412, 'nom_marcax' => 'YUAN', 'ind_estado' => 1),
			655 => array('cod_marcax'  => 411, 'nom_marcax' => 'XL XINLING', 'ind_estado' => 1),
			656 => array('cod_marcax'  => 410, 'nom_marcax' => 'VENTIE', 'ind_estado' => 1),
			657 => array('cod_marcax'  => 409, 'nom_marcax' => 'XINGYUE', 'ind_estado' => 1),
			658 => array('cod_marcax'  => 408, 'nom_marcax' => 'WEST', 'ind_estado' => 1),
			659 => array('cod_marcax'  => 407, 'nom_marcax' => 'BRP/CAN AM', 'ind_estado' => 1),
			660 => array('cod_marcax'  => 406, 'nom_marcax' => 'NEW ERA', 'ind_estado' => 1),
			661 => array('cod_marcax'  => 405, 'nom_marcax' => 'FRIBEST', 'ind_estado' => 1),
			662 => array('cod_marcax'  => 404, 'nom_marcax' => 'TONGKO', 'ind_estado' => 1),
			663 => array('cod_marcax'  => 403, 'nom_marcax' => 'SAEHAN', 'ind_estado' => 1),
			664 => array('cod_marcax'  => 402, 'nom_marcax' => 'HAILI', 'ind_estado' => 1),
			665 => array('cod_marcax'  => 401, 'nom_marcax' => 'NITRO', 'ind_estado' => 1),
			666 => array('cod_marcax'  => 400, 'nom_marcax' => 'WULING', 'ind_estado' => 1),
			667 => array('cod_marcax'  => 399, 'nom_marcax' => 'SATURN', 'ind_estado' => 1),
			668 => array('cod_marcax'  => 398, 'nom_marcax' => 'PUMA', 'ind_estado' => 1),
			669 => array('cod_marcax'  => 397, 'nom_marcax' => 'PIERCE ARROW', 'ind_estado' => 1),
			670 => array('cod_marcax'  => 396, 'nom_marcax' => 'LA SALLE', 'ind_estado' => 1),
			671 => array('cod_marcax'  => 395, 'nom_marcax' => 'HUMBERT', 'ind_estado' => 1),
			672 => array('cod_marcax'  => 394, 'nom_marcax' => 'GURGEL', 'ind_estado' => 1),
			673 => array('cod_marcax'  => 393, 'nom_marcax' => 'BUYANG', 'ind_estado' => 1),
			674 => array('cod_marcax'  => 392, 'nom_marcax' => 'CUSHMA', 'ind_estado' => 1),
			675 => array('cod_marcax'  => 391, 'nom_marcax' => 'COBRA', 'ind_estado' => 1),
			676 => array('cod_marcax'  => 390, 'nom_marcax' => 'BRITISH', 'ind_estado' => 1),
			677 => array('cod_marcax'  => 389, 'nom_marcax' => 'VERUCCI', 'ind_estado' => 1),
			678 => array('cod_marcax'  => 388, 'nom_marcax' => 'JMC', 'ind_estado' => 1),
			679 => array('cod_marcax'  => 387, 'nom_marcax' => 'SONGSHENG', 'ind_estado' => 1),
			680 => array('cod_marcax'  => 386, 'nom_marcax' => 'JBWCO', 'ind_estado' => 1),
			681 => array('cod_marcax'  => 385, 'nom_marcax' => 'HAOJIN', 'ind_estado' => 1),
			682 => array('cod_marcax'  => 384, 'nom_marcax' => 'QJ', 'ind_estado' => 1),
			683 => array('cod_marcax'  => 383, 'nom_marcax' => 'TMEC', 'ind_estado' => 1),
			684 => array('cod_marcax'  => 382, 'nom_marcax' => 'VENOM MOTORS', 'ind_estado' => 1),
			685 => array('cod_marcax'  => 381, 'nom_marcax' => 'UNITED MOTORS', 'ind_estado' => 1),
			686 => array('cod_marcax'  => 380, 'nom_marcax' => 'SHINERAY MOTOS', 'ind_estado' => 1),
			687 => array('cod_marcax'  => 379, 'nom_marcax' => 'ACCURO', 'ind_estado' => 1),
			688 => array('cod_marcax'  => 378, 'nom_marcax' => 'ROKETA', 'ind_estado' => 1),
			689 => array('cod_marcax'  => 377, 'nom_marcax' => 'YAMATI', 'ind_estado' => 1),
			690 => array('cod_marcax'  => 376, 'nom_marcax' => 'CNENLON', 'ind_estado' => 1),
			691 => array('cod_marcax'  => 375, 'nom_marcax' => 'FOTON', 'ind_estado' => 1),
			692 => array('cod_marcax'  => 374, 'nom_marcax' => 'SANYA', 'ind_estado' => 1),
			693 => array('cod_marcax'  => 373, 'nom_marcax' => 'AVANTI', 'ind_estado' => 1),
			694 => array('cod_marcax'  => 372, 'nom_marcax' => 'JOYNER', 'ind_estado' => 1),
			695 => array('cod_marcax'  => 371, 'nom_marcax' => 'ROYAL ENFIELD', 'ind_estado' => 1),
			696 => array('cod_marcax'  => 370, 'nom_marcax' => 'SYM', 'ind_estado' => 1),
			697 => array('cod_marcax'  => 369, 'nom_marcax' => 'U.S.W.MOTORS', 'ind_estado' => 1),
			698 => array('cod_marcax'  => 368, 'nom_marcax' => 'ZHONGXING', 'ind_estado' => 1),
			699 => array('cod_marcax'  => 367, 'nom_marcax' => 'BORGO', 'ind_estado' => 1),
			700 => array('cod_marcax'  => 366, 'nom_marcax' => 'JAC', 'ind_estado' => 1),
			701 => array('cod_marcax'  => 365, 'nom_marcax' => 'JONWAY', 'ind_estado' => 1),
			702 => array('cod_marcax'  => 364, 'nom_marcax' => 'BUELL', 'ind_estado' => 1),
			703 => array('cod_marcax'  => 363, 'nom_marcax' => 'TYCO', 'ind_estado' => 1),
			704 => array('cod_marcax'  => 362, 'nom_marcax' => 'GALARDI', 'ind_estado' => 1),
			705 => array('cod_marcax'  => 361, 'nom_marcax' => 'RENNO', 'ind_estado' => 1),
			706 => array('cod_marcax'  => 360, 'nom_marcax' => 'APRILIA', 'ind_estado' => 1),
			707 => array('cod_marcax'  => 359, 'nom_marcax' => 'USW', 'ind_estado' => 1),
			708 => array('cod_marcax'  => 358, 'nom_marcax' => 'MOTOR UNO', 'ind_estado' => 1),
			709 => array('cod_marcax'  => 357, 'nom_marcax' => 'KINROAD XINTIAN', 'ind_estado' => 1),
			710 => array('cod_marcax'  => 356, 'nom_marcax' => 'AUTOCAR WHITE', 'ind_estado' => 1),
			711 => array('cod_marcax'  => 355, 'nom_marcax' => 'SUMOTO', 'ind_estado' => 1),
			712 => array('cod_marcax'  => 354, 'nom_marcax' => 'ZHEJIANG', 'ind_estado' => 1),
			713 => array('cod_marcax'  => 353, 'nom_marcax' => 'KEEWAY', 'ind_estado' => 1),
			714 => array('cod_marcax'  => 352, 'nom_marcax' => 'XISPA', 'ind_estado' => 1),
			715 => array('cod_marcax'  => 351, 'nom_marcax' => 'POLARIS ATV', 'ind_estado' => 1),
			716 => array('cod_marcax'  => 350, 'nom_marcax' => 'GENESIS', 'ind_estado' => 1),
			717 => array('cod_marcax'  => 349, 'nom_marcax' => 'GREAT WALL', 'ind_estado' => 1),
			718 => array('cod_marcax'  => 348, 'nom_marcax' => 'FIRENZE', 'ind_estado' => 1),
			719 => array('cod_marcax'  => 347, 'nom_marcax' => 'URAL', 'ind_estado' => 1),
			720 => array('cod_marcax'  => 346, 'nom_marcax' => 'CMC', 'ind_estado' => 1),
			721 => array('cod_marcax'  => 345, 'nom_marcax' => 'KYOTO', 'ind_estado' => 1),
			722 => array('cod_marcax'  => 344, 'nom_marcax' => 'HUONNIAO', 'ind_estado' => 1),
			723 => array('cod_marcax'  => 343, 'nom_marcax' => 'ARGO', 'ind_estado' => 1),
			724 => array('cod_marcax'  => 342, 'nom_marcax' => 'CHONGQING', 'ind_estado' => 1),
			725 => array('cod_marcax'  => 341, 'nom_marcax' => 'SKOOT MOTORCYCLES', 'ind_estado' => 1),
			726 => array('cod_marcax'  => 340, 'nom_marcax' => 'UNISON', 'ind_estado' => 1),
			727 => array('cod_marcax'  => 339, 'nom_marcax' => 'YINGANG', 'ind_estado' => 1),
			728 => array('cod_marcax'  => 338, 'nom_marcax' => 'FUTONG', 'ind_estado' => 1),
			729 => array('cod_marcax'  => 337, 'nom_marcax' => 'BEST', 'ind_estado' => 1),
			730 => array('cod_marcax'  => 336, 'nom_marcax' => 'ZONGSHEN', 'ind_estado' => 1),
			731 => array('cod_marcax'  => 335, 'nom_marcax' => 'JMSTAR', 'ind_estado' => 1),
			732 => array('cod_marcax'  => 334, 'nom_marcax' => 'WANXIN', 'ind_estado' => 1),
			733 => array('cod_marcax'  => 333, 'nom_marcax' => 'WONJAN', 'ind_estado' => 1),
			734 => array('cod_marcax'  => 332, 'nom_marcax' => 'ATV', 'ind_estado' => 1),
			735 => array('cod_marcax'  => 331, 'nom_marcax' => 'ARIEL', 'ind_estado' => 1),
			736 => array('cod_marcax'  => 330, 'nom_marcax' => 'UKM', 'ind_estado' => 1),
			737 => array('cod_marcax'  => 329, 'nom_marcax' => 'HALLEY', 'ind_estado' => 1),
			738 => array('cod_marcax'  => 328, 'nom_marcax' => 'MORGAN', 'ind_estado' => 1),
			739 => array('cod_marcax'  => 327, 'nom_marcax' => 'KINROAD', 'ind_estado' => 1),
			740 => array('cod_marcax'  => 326, 'nom_marcax' => 'WALTER', 'ind_estado' => 1),
			741 => array('cod_marcax'  => 325, 'nom_marcax' => 'REAR', 'ind_estado' => 1),
			742 => array('cod_marcax'  => 324, 'nom_marcax' => 'JUNESUN', 'ind_estado' => 1),
			743 => array('cod_marcax'  => 323, 'nom_marcax' => 'MZ', 'ind_estado' => 1),
			744 => array('cod_marcax'  => 322, 'nom_marcax' => 'KYMCO', 'ind_estado' => 1),
			745 => array('cod_marcax'  => 321, 'nom_marcax' => 'SACHS BIKES', 'ind_estado' => 1),
			746 => array('cod_marcax'  => 320, 'nom_marcax' => 'JIANGSU', 'ind_estado' => 1),
			747 => array('cod_marcax'  => 319, 'nom_marcax' => 'MC MOTOR', 'ind_estado' => 1),
			748 => array('cod_marcax'  => 318, 'nom_marcax' => 'AUPACO', 'ind_estado' => 1),
			749 => array('cod_marcax'  => 317, 'nom_marcax' => 'KAYAK', 'ind_estado' => 1),
			750 => array('cod_marcax'  => 316, 'nom_marcax' => 'PASAGGIO', 'ind_estado' => 1),
			751 => array('cod_marcax'  => 315, 'nom_marcax' => 'SKYGO', 'ind_estado' => 1),
			752 => array('cod_marcax'  => 314, 'nom_marcax' => 'DUKAR', 'ind_estado' => 1),
			753 => array('cod_marcax'  => 313, 'nom_marcax' => 'BYD', 'ind_estado' => 1),
			754 => array('cod_marcax'  => 312, 'nom_marcax' => 'CPI', 'ind_estado' => 1),
			755 => array('cod_marcax'  => 311, 'nom_marcax' => 'HONLEI', 'ind_estado' => 1),
			756 => array('cod_marcax'  => 310, 'nom_marcax' => 'ACCURA', 'ind_estado' => 1),
			757 => array('cod_marcax'  => 309, 'nom_marcax' => 'JINAN', 'ind_estado' => 1),
			758 => array('cod_marcax'  => 308, 'nom_marcax' => 'TITANIA', 'ind_estado' => 1),
			759 => array('cod_marcax'  => 307, 'nom_marcax' => 'XIALI', 'ind_estado' => 1),
			760 => array('cod_marcax'  => 306, 'nom_marcax' => 'GOMOTOR', 'ind_estado' => 1),
			761 => array('cod_marcax'  => 305, 'nom_marcax' => 'VENTO', 'ind_estado' => 1),
			762 => array('cod_marcax'  => 304, 'nom_marcax' => 'KAZUKI', 'ind_estado' => 1),
			763 => array('cod_marcax'  => 303, 'nom_marcax' => 'LONCIN', 'ind_estado' => 1),
			764 => array('cod_marcax'  => 302, 'nom_marcax' => 'CHANGHE', 'ind_estado' => 1),
			765 => array('cod_marcax'  => 301, 'nom_marcax' => 'VICTORY', 'ind_estado' => 1),
			766 => array('cod_marcax'  => 300, 'nom_marcax' => 'MINI POCKET BIKE', 'ind_estado' => 1),
			767 => array('cod_marcax'  => 299, 'nom_marcax' => 'SIGMA', 'ind_estado' => 1),
			768 => array('cod_marcax'  => 298, 'nom_marcax' => 'AMC', 'ind_estado' => 1),
			769 => array('cod_marcax'  => 297, 'nom_marcax' => 'JET UKM', 'ind_estado' => 1),
			770 => array('cod_marcax'  => 296, 'nom_marcax' => 'CHANGJIANG', 'ind_estado' => 1),
			771 => array('cod_marcax'  => 295, 'nom_marcax' => 'KINLON', 'ind_estado' => 1),
			772 => array('cod_marcax'  => 294, 'nom_marcax' => 'SAIC WULING', 'ind_estado' => 1),
			773 => array('cod_marcax'  => 293, 'nom_marcax' => 'PIONEER', 'ind_estado' => 1),
			774 => array('cod_marcax'  => 292, 'nom_marcax' => 'AYCO', 'ind_estado' => 1),
			775 => array('cod_marcax'  => 291, 'nom_marcax' => 'JEZHANG', 'ind_estado' => 1),
			776 => array('cod_marcax'  => 290, 'nom_marcax' => 'SHENGQIBAO', 'ind_estado' => 1),
			777 => array('cod_marcax'  => 289, 'nom_marcax' => 'CHERY', 'ind_estado' => 1),
			778 => array('cod_marcax'  => 288, 'nom_marcax' => 'CHANA', 'ind_estado' => 1),
			779 => array('cod_marcax'  => 287, 'nom_marcax' => 'GEELY', 'ind_estado' => 1),
			780 => array('cod_marcax'  => 286, 'nom_marcax' => 'QINGQI', 'ind_estado' => 1),
			781 => array('cod_marcax'  => 285, 'nom_marcax' => 'MAX MOTOR', 'ind_estado' => 1),
			782 => array('cod_marcax'  => 284, 'nom_marcax' => 'LINHAI', 'ind_estado' => 1),
			783 => array('cod_marcax'  => 283, 'nom_marcax' => 'HAFEI', 'ind_estado' => 1),
			784 => array('cod_marcax'  => 282, 'nom_marcax' => 'OKLAN', 'ind_estado' => 1),
			785 => array('cod_marcax'  => 281, 'nom_marcax' => 'CHANGAN', 'ind_estado' => 1),
			786 => array('cod_marcax'  => 280, 'nom_marcax' => 'GAS GAS', 'ind_estado' => 1),
			787 => array('cod_marcax'  => 279, 'nom_marcax' => 'DINLI', 'ind_estado' => 1),
			788 => array('cod_marcax'  => 278, 'nom_marcax' => 'SAIC CHERY', 'ind_estado' => 1),
			789 => array('cod_marcax'  => 277, 'nom_marcax' => 'AKT', 'ind_estado' => 1),
			790 => array('cod_marcax'  => 276, 'nom_marcax' => 'KOREMOTO', 'ind_estado' => 1),
			791 => array('cod_marcax'  => 275, 'nom_marcax' => 'LIFAN', 'ind_estado' => 1),
			792 => array('cod_marcax'  => 274, 'nom_marcax' => 'VARZI', 'ind_estado' => 1),
			793 => array('cod_marcax'  => 273, 'nom_marcax' => 'SMART', 'ind_estado' => 1),
			794 => array('cod_marcax'  => 272, 'nom_marcax' => 'TATA', 'ind_estado' => 1),
			795 => array('cod_marcax'  => 271, 'nom_marcax' => 'LML', 'ind_estado' => 1),
			796 => array('cod_marcax'  => 270, 'nom_marcax' => 'WHITE', 'ind_estado' => 1),
			797 => array('cod_marcax'  => 269, 'nom_marcax' => 'VOSJOD', 'ind_estado' => 1),
			798 => array('cod_marcax'  => 268, 'nom_marcax' => 'THAMES', 'ind_estado' => 1),
			799 => array('cod_marcax'  => 267, 'nom_marcax' => 'TRABANT', 'ind_estado' => 1),
			800 => array('cod_marcax'  => 266, 'nom_marcax' => 'SAVA', 'ind_estado' => 1),
			801 => array('cod_marcax'  => 265, 'nom_marcax' => 'SINGER', 'ind_estado' => 1),
			802 => array('cod_marcax'  => 264, 'nom_marcax' => 'SUMBEAM', 'ind_estado' => 1),
			803 => array('cod_marcax'  => 263, 'nom_marcax' => 'SANGLAS', 'ind_estado' => 1),
			804 => array('cod_marcax'  => 262, 'nom_marcax' => 'SAMSUNG', 'ind_estado' => 1),
			805 => array('cod_marcax'  => 261, 'nom_marcax' => 'RONART', 'ind_estado' => 1),
			806 => array('cod_marcax'  => 260, 'nom_marcax' => 'PANHARD', 'ind_estado' => 1),
			807 => array('cod_marcax'  => 259, 'nom_marcax' => 'PANNONIA', 'ind_estado' => 1),
			808 => array('cod_marcax'  => 258, 'nom_marcax' => 'PACER', 'ind_estado' => 1),
			809 => array('cod_marcax'  => 257, 'nom_marcax' => 'MOTOGUZZI', 'ind_estado' => 1),
			810 => array('cod_marcax'  => 256, 'nom_marcax' => 'CARABELLA', 'ind_estado' => 1),
			811 => array('cod_marcax'  => 255, 'nom_marcax' => 'BOCXOD', 'ind_estado' => 1),
			812 => array('cod_marcax'  => 254, 'nom_marcax' => 'BULTACO', 'ind_estado' => 1),
			813 => array('cod_marcax'  => 253, 'nom_marcax' => 'BABETA', 'ind_estado' => 1),
			814 => array('cod_marcax'  => 252, 'nom_marcax' => 'MAHINDRA', 'ind_estado' => 1),
			815 => array('cod_marcax'  => 251, 'nom_marcax' => 'GILERA', 'ind_estado' => 1),
			816 => array('cod_marcax'  => 250, 'nom_marcax' => 'INDIAN', 'ind_estado' => 1),
			817 => array('cod_marcax'  => 249, 'nom_marcax' => 'VOSKHOD', 'ind_estado' => 1),
			818 => array('cod_marcax'  => 248, 'nom_marcax' => 'ITALJET', 'ind_estado' => 1),
			819 => array('cod_marcax'  => 247, 'nom_marcax' => 'NORTON', 'ind_estado' => 1),
			820 => array('cod_marcax'  => 246, 'nom_marcax' => 'B.S.A', 'ind_estado' => 1),
			821 => array('cod_marcax'  => 245, 'nom_marcax' => 'VESPA', 'ind_estado' => 1),
			822 => array('cod_marcax'  => 244, 'nom_marcax' => 'VAUSHALL', 'ind_estado' => 1),
			823 => array('cod_marcax'  => 243, 'nom_marcax' => 'ZUMY', 'ind_estado' => 1),
			824 => array('cod_marcax'  => 242, 'nom_marcax' => 'DAYANG', 'ind_estado' => 1),
			825 => array('cod_marcax'  => 241, 'nom_marcax' => 'INFINITI', 'ind_estado' => 1),
			826 => array('cod_marcax'  => 240, 'nom_marcax' => 'BOMBARDIER', 'ind_estado' => 1),
			827 => array('cod_marcax'  => 239, 'nom_marcax' => 'KINETIC', 'ind_estado' => 1),
			828 => array('cod_marcax'  => 238, 'nom_marcax' => 'PRINCE', 'ind_estado' => 1),
			829 => array('cod_marcax'  => 237, 'nom_marcax' => 'SPARTAN', 'ind_estado' => 1),
			830 => array('cod_marcax'  => 236, 'nom_marcax' => 'RAF', 'ind_estado' => 1),
			831 => array('cod_marcax'  => 235, 'nom_marcax' => 'MG', 'ind_estado' => 1),
			832 => array('cod_marcax'  => 234, 'nom_marcax' => 'DUCATI', 'ind_estado' => 1),
			833 => array('cod_marcax'  => 233, 'nom_marcax' => 'PETERBILT', 'ind_estado' => 1),
			834 => array('cod_marcax'  => 232, 'nom_marcax' => 'AGRALE', 'ind_estado' => 1),
			835 => array('cod_marcax'  => 231, 'nom_marcax' => 'XINGFU', 'ind_estado' => 1),
			836 => array('cod_marcax'  => 230, 'nom_marcax' => 'BEISUTE', 'ind_estado' => 1),
			837 => array('cod_marcax'  => 229, 'nom_marcax' => 'POLONEZ', 'ind_estado' => 1),
			838 => array('cod_marcax'  => 228, 'nom_marcax' => 'BAJAJ', 'ind_estado' => 1),
			839 => array('cod_marcax'  => 227, 'nom_marcax' => 'KTM', 'ind_estado' => 1),
			840 => array('cod_marcax'  => 226, 'nom_marcax' => 'HUMMER', 'ind_estado' => 1),
			841 => array('cod_marcax'  => 225, 'nom_marcax' => 'YUGO', 'ind_estado' => 1),
			842 => array('cod_marcax'  => 224, 'nom_marcax' => 'JIANSHE', 'ind_estado' => 1),
			843 => array('cod_marcax'  => 223, 'nom_marcax' => 'DAELIM', 'ind_estado' => 1),
			844 => array('cod_marcax'  => 222, 'nom_marcax' => 'COLMOVE', 'ind_estado' => 1),
			845 => array('cod_marcax'  => 221, 'nom_marcax' => 'PIAGGIO', 'ind_estado' => 1),
			846 => array('cod_marcax'  => 220, 'nom_marcax' => 'WARZAMA', 'ind_estado' => 1),
			847 => array('cod_marcax'  => 219, 'nom_marcax' => 'TRIUMPH', 'ind_estado' => 1),
			848 => array('cod_marcax'  => 218, 'nom_marcax' => 'STUDEBAKER', 'ind_estado' => 1),
			849 => array('cod_marcax'  => 217, 'nom_marcax' => 'SSANGYONG', 'ind_estado' => 1),
			850 => array('cod_marcax'  => 216, 'nom_marcax' => 'SCANIA', 'ind_estado' => 1),
			851 => array('cod_marcax'  => 215, 'nom_marcax' => 'REO', 'ind_estado' => 1),
			852 => array('cod_marcax'  => 214, 'nom_marcax' => 'PORSCHE', 'ind_estado' => 1),
			853 => array('cod_marcax'  => 213, 'nom_marcax' => 'PEGASSO', 'ind_estado' => 1),
			854 => array('cod_marcax'  => 212, 'nom_marcax' => 'MINICORD', 'ind_estado' => 1),
			855 => array('cod_marcax'  => 210, 'nom_marcax' => 'LEXUS', 'ind_estado' => 1),
			856 => array('cod_marcax'  => 209, 'nom_marcax' => 'JAWA', 'ind_estado' => 1),
			857 => array('cod_marcax'  => 208, 'nom_marcax' => 'HYUNDAI', 'ind_estado' => 1),
			858 => array('cod_marcax'  => 207, 'nom_marcax' => 'HENRY J', 'ind_estado' => 1),
			859 => array('cod_marcax'  => 206, 'nom_marcax' => 'DERBY', 'ind_estado' => 1),
			860 => array('cod_marcax'  => 205, 'nom_marcax' => 'BEIJING', 'ind_estado' => 1),
			861 => array('cod_marcax'  => 204, 'nom_marcax' => 'ROA', 'ind_estado' => 1),
			862 => array('cod_marcax'  => 202, 'nom_marcax' => 'AMERICAN MOTOR', 'ind_estado' => 1),
			863 => array('cod_marcax'  => 201, 'nom_marcax' => 'ALEKO', 'ind_estado' => 1),
			864 => array('cod_marcax'  => 200, 'nom_marcax' => 'F.S.O.', 'ind_estado' => 1),
			865 => array('cod_marcax'  => 198, 'nom_marcax' => 'PACKARD', 'ind_estado' => 1),
			866 => array('cod_marcax'  => 196, 'nom_marcax' => 'NECKAR', 'ind_estado' => 1),
			867 => array('cod_marcax'  => 195, 'nom_marcax' => 'MURAVEY', 'ind_estado' => 1),
			868 => array('cod_marcax'  => 192, 'nom_marcax' => 'MOSKOVICH', 'ind_estado' => 1),
			869 => array('cod_marcax'  => 191, 'nom_marcax' => 'MAGIRUS DEUTZ', 'ind_estado' => 1),
			870 => array('cod_marcax'  => 190, 'nom_marcax' => 'MAN', 'ind_estado' => 1),
			871 => array('cod_marcax'  => 188, 'nom_marcax' => 'LOTUS', 'ind_estado' => 1),
			872 => array('cod_marcax'  => 185, 'nom_marcax' => 'LAMBORGHINI', 'ind_estado' => 1),
			873 => array('cod_marcax'  => 184, 'nom_marcax' => 'KIAMASTER', 'ind_estado' => 1),
			874 => array('cod_marcax'  => 181, 'nom_marcax' => 'ISO', 'ind_estado' => 1),
			875 => array('cod_marcax'  => 179, 'nom_marcax' => 'IFA', 'ind_estado' => 1),
			876 => array('cod_marcax'  => 178, 'nom_marcax' => 'HUDSON', 'ind_estado' => 1),
			877 => array('cod_marcax'  => 176, 'nom_marcax' => 'HILLMAN', 'ind_estado' => 1),
			878 => array('cod_marcax'  => 175, 'nom_marcax' => 'HOHOLDEN', 'ind_estado' => 1),
			879 => array('cod_marcax'  => 171, 'nom_marcax' => 'FAUN', 'ind_estado' => 1),
			880 => array('cod_marcax'  => 169, 'nom_marcax' => 'FREIGHTLINER', 'ind_estado' => 1),
			881 => array('cod_marcax'  => 167, 'nom_marcax' => 'FORDSON', 'ind_estado' => 1),
			882 => array('cod_marcax'  => 165, 'nom_marcax' => 'EDSEL', 'ind_estado' => 1),
			883 => array('cod_marcax'  => 163, 'nom_marcax' => 'DKW', 'ind_estado' => 1),
			884 => array('cod_marcax'  => 158, 'nom_marcax' => 'COMMER', 'ind_estado' => 1),
			885 => array('cod_marcax'  => 156, 'nom_marcax' => 'BARREIROS', 'ind_estado' => 1),
			886 => array('cod_marcax'  => 154, 'nom_marcax' => 'BERLIET', 'ind_estado' => 1),
			887 => array('cod_marcax'  => 153, 'nom_marcax' => 'BEDFORD', 'ind_estado' => 1),
			888 => array('cod_marcax'  => 151, 'nom_marcax' => 'BUSSING', 'ind_estado' => 1),
			889 => array('cod_marcax'  => 150, 'nom_marcax' => 'BENTLEY', 'ind_estado' => 1),
			890 => array('cod_marcax'  => 149, 'nom_marcax' => 'BORG WARD', 'ind_estado' => 1),
			891 => array('cod_marcax'  => 148, 'nom_marcax' => 'BROCK WAY', 'ind_estado' => 1),
			892 => array('cod_marcax'  => 146, 'nom_marcax' => 'CHECKER', 'ind_estado' => 1),
			893 => array('cod_marcax'  => 144, 'nom_marcax' => 'AVIA', 'ind_estado' => 1),
			894 => array('cod_marcax'  => 143, 'nom_marcax' => 'AUTO UNION', 'ind_estado' => 1),
			895 => array('cod_marcax'  => 142, 'nom_marcax' => 'ASTON MARTIN', 'ind_estado' => 1),
			896 => array('cod_marcax'  => 139, 'nom_marcax' => 'AUDI', 'ind_estado' => 1),
			897 => array('cod_marcax'  => 138, 'nom_marcax' => 'ABARTH', 'ind_estado' => 1),
			898 => array('cod_marcax'  => 136, 'nom_marcax' => 'SEAT', 'ind_estado' => 1),
			899 => array('cod_marcax'  => 135, 'nom_marcax' => 'SISU', 'ind_estado' => 1),
			900 => array('cod_marcax'  => 130, 'nom_marcax' => 'QJIANG', 'ind_estado' => 1),
			901 => array('cod_marcax'  => 129, 'nom_marcax' => 'WILLCO', 'ind_estado' => 1),
			902 => array('cod_marcax'  => 128, 'nom_marcax' => 'RAMBLER', 'ind_estado' => 1),
			903 => array('cod_marcax'  => 127, 'nom_marcax' => 'MORRIS', 'ind_estado' => 1),
			904 => array('cod_marcax'  => 126, 'nom_marcax' => 'WARTBURG', 'ind_estado' => 1),
			905 => array('cod_marcax'  => 125, 'nom_marcax' => 'NASH', 'ind_estado' => 1),
			906 => array('cod_marcax'  => 123, 'nom_marcax' => 'JINCHENG', 'ind_estado' => 1),
			907 => array('cod_marcax'  => 121, 'nom_marcax' => 'EBRO', 'ind_estado' => 1),
			908 => array('cod_marcax'  => 120, 'nom_marcax' => 'PUCH', 'ind_estado' => 1),
			909 => array('cod_marcax'  => 119, 'nom_marcax' => 'KAMAZ', 'ind_estado' => 1),
			910 => array('cod_marcax'  => 118, 'nom_marcax' => 'CORCEL', 'ind_estado' => 1),
			911 => array('cod_marcax'  => 115, 'nom_marcax' => 'ROVER', 'ind_estado' => 1),
			912 => array('cod_marcax'  => 114, 'nom_marcax' => 'FARGO', 'ind_estado' => 1),
			913 => array('cod_marcax'  => 113, 'nom_marcax' => 'MONTESA', 'ind_estado' => 1),
			914 => array('cod_marcax'  => 112, 'nom_marcax' => 'HUALI', 'ind_estado' => 1),
			915 => array('cod_marcax'  => 110, 'nom_marcax' => 'ZASTAVA', 'ind_estado' => 1),
			916 => array('cod_marcax'  => 108, 'nom_marcax' => 'JIALING', 'ind_estado' => 1),
			917 => array('cod_marcax'  => 104, 'nom_marcax' => 'BELARUS', 'ind_estado' => 1),
			918 => array('cod_marcax'  => 101, 'nom_marcax' => 'TAM', 'ind_estado' => 1),
			919 => array('cod_marcax'  => 97, 'nom_marcax' => 'KUBOTA', 'ind_estado' => 1),
			920 => array('cod_marcax'  => 95, 'nom_marcax' => 'VIASA', 'ind_estado' => 1),
			921 => array('cod_marcax'  => 91, 'nom_marcax' => 'GMC', 'ind_estado' => 1),
			922 => array('cod_marcax'  => 89, 'nom_marcax' => 'HUSQVARNA', 'ind_estado' => 1),
			923 => array('cod_marcax'  => 86, 'nom_marcax' => 'HYOSUNG', 'ind_estado' => 1),
			924 => array('cod_marcax'  => 85, 'nom_marcax' => 'DELTA', 'ind_estado' => 1),
			925 => array('cod_marcax'  => 84, 'nom_marcax' => 'GEO', 'ind_estado' => 1),
			926 => array('cod_marcax'  => 83, 'nom_marcax' => 'DINA', 'ind_estado' => 1),
			927 => array('cod_marcax'  => 76, 'nom_marcax' => 'HINO', 'ind_estado' => 1),
			928 => array('cod_marcax'  => 75, 'nom_marcax' => 'DESOTO', 'ind_estado' => 1),
			929 => array('cod_marcax'  => 74, 'nom_marcax' => 'AUTOCAR', 'ind_estado' => 1),
			930 => array('cod_marcax'  => 73, 'nom_marcax' => 'AUSTIN', 'ind_estado' => 1),
			931 => array('cod_marcax'  => 72, 'nom_marcax' => 'HERO', 'ind_estado' => 1),
			932 => array('cod_marcax'  => 71, 'nom_marcax' => 'MINSK', 'ind_estado' => 1),
			933 => array('cod_marcax'  => 69, 'nom_marcax' => 'LAMBRETA', 'ind_estado' => 1),
			934 => array('cod_marcax'  => 68, 'nom_marcax' => 'IVECO', 'ind_estado' => 1),
			935 => array('cod_marcax'  => 67, 'nom_marcax' => 'KENWORTH', 'ind_estado' => 1),
			936 => array('cod_marcax'  => 66, 'nom_marcax' => 'WILLYS', 'ind_estado' => 1),
			937 => array('cod_marcax'  => 65, 'nom_marcax' => 'CAGIVA', 'ind_estado' => 1),
			938 => array('cod_marcax'  => 64, 'nom_marcax' => 'MACK', 'ind_estado' => 1),
			939 => array('cod_marcax'  => 63, 'nom_marcax' => 'ASIA MOTOR', 'ind_estado' => 1),
			940 => array('cod_marcax'  => 62, 'nom_marcax' => 'INTERNATIONAL', 'ind_estado' => 1),
			941 => array('cod_marcax'  => 61, 'nom_marcax' => 'AUTECO', 'ind_estado' => 1),
			942 => array('cod_marcax'  => 60, 'nom_marcax' => 'HARLEY DAVIDSON', 'ind_estado' => 1),
			943 => array('cod_marcax'  => 57, 'nom_marcax' => 'KAWASAKI', 'ind_estado' => 1),
			944 => array('cod_marcax'  => 56, 'nom_marcax' => 'YAMAHA', 'ind_estado' => 1),
			945 => array('cod_marcax'  => 54, 'nom_marcax' => 'FORD', 'ind_estado' => 1),
			946 => array('cod_marcax'  => 53, 'nom_marcax' => 'CHRYSLER', 'ind_estado' => 1),
			947 => array('cod_marcax'  => 52, 'nom_marcax' => 'SUZUKI', 'ind_estado' => 1),
			948 => array('cod_marcax'  => 51, 'nom_marcax' => 'LAND ROVER', 'ind_estado' => 1),
			949 => array('cod_marcax'  => 50, 'nom_marcax' => 'JEEP', 'ind_estado' => 1),
			950 => array('cod_marcax'  => 49, 'nom_marcax' => 'ISUZU', 'ind_estado' => 1),
			951 => array('cod_marcax'  => 48, 'nom_marcax' => 'OPEL', 'ind_estado' => 1),
			952 => array('cod_marcax'  => 47, 'nom_marcax' => 'MERCURY', 'ind_estado' => 1),
			953 => array('cod_marcax'  => 46, 'nom_marcax' => 'ARO', 'ind_estado' => 1),
			954 => array('cod_marcax'  => 45, 'nom_marcax' => 'UAZ', 'ind_estado' => 1),
			955 => array('cod_marcax'  => 44, 'nom_marcax' => 'GAZ', 'ind_estado' => 1),
			956 => array('cod_marcax'  => 42, 'nom_marcax' => 'DAIHATSU', 'ind_estado' => 1),
			957 => array('cod_marcax'  => 41, 'nom_marcax' => 'CITROEN', 'ind_estado' => 1),
			958 => array('cod_marcax'  => 40, 'nom_marcax' => 'SKODA', 'ind_estado' => 1),
			959 => array('cod_marcax'  => 39, 'nom_marcax' => 'VOLGA', 'ind_estado' => 1),
			960 => array('cod_marcax'  => 37, 'nom_marcax' => 'TAVRIA', 'ind_estado' => 1),
			961 => array('cod_marcax'  => 36, 'nom_marcax' => 'OLTCIT', 'ind_estado' => 1),
			962 => array('cod_marcax'  => 35, 'nom_marcax' => 'LADA', 'ind_estado' => 1),
			963 => array('cod_marcax'  => 34, 'nom_marcax' => 'DACIA', 'ind_estado' => 1),
			964 => array('cod_marcax'  => 33, 'nom_marcax' => 'JAGUAR', 'ind_estado' => 1),
			965 => array('cod_marcax'  => 32, 'nom_marcax' => 'ROLLS ROYCE', 'ind_estado' => 1),
			966 => array('cod_marcax'  => 30, 'nom_marcax' => 'MERCEDES BENZ', 'ind_estado' => 1),
			967 => array('cod_marcax'  => 29, 'nom_marcax' => 'FERRARI', 'ind_estado' => 1),
			968 => array('cod_marcax'  => 28, 'nom_marcax' => 'BMW', 'ind_estado' => 1),
			969 => array('cod_marcax'  => 27, 'nom_marcax' => 'ALFA ROMEO', 'ind_estado' => 1),
			970 => array('cod_marcax'  => 26, 'nom_marcax' => 'VOLVO', 'ind_estado' => 1),
			971 => array('cod_marcax'  => 25, 'nom_marcax' => 'TOYOTA', 'ind_estado' => 1),
			972 => array('cod_marcax'  => 24, 'nom_marcax' => 'PONTIAC', 'ind_estado' => 1),
			973 => array('cod_marcax'  => 23, 'nom_marcax' => 'MITSUBISHI', 'ind_estado' => 1),
			974 => array('cod_marcax'  => 22, 'nom_marcax' => 'BRONCO', 'ind_estado' => 1),
			975 => array('cod_marcax'  => 21, 'nom_marcax' => 'HONDA', 'ind_estado' => 1),
			976 => array('cod_marcax'  => 20, 'nom_marcax' => 'CADILLAC', 'ind_estado' => 1),
			977 => array('cod_marcax'  => 19, 'nom_marcax' => 'BUICK', 'ind_estado' => 1),
			978 => array('cod_marcax'  => 18, 'nom_marcax' => 'DATSUN', 'ind_estado' => 1),
			979 => array('cod_marcax'  => 17, 'nom_marcax' => 'SUBARU', 'ind_estado' => 1),
			980 => array('cod_marcax'  => 16, 'nom_marcax' => 'PEUGEOT', 'ind_estado' => 1),
			981 => array('cod_marcax'  => 15, 'nom_marcax' => 'NISSAN', 'ind_estado' => 1),
			982 => array('cod_marcax'  => 14, 'nom_marcax' => 'LANCIA', 'ind_estado' => 1),
			983 => array('cod_marcax'  => 13, 'nom_marcax' => 'OLDSMOBILE', 'ind_estado' => 1),
			984 => array('cod_marcax'  => 12, 'nom_marcax' => 'PLYMOUTH', 'ind_estado' => 1),
			985 => array('cod_marcax'  => 11, 'nom_marcax' => 'SIMCA', 'ind_estado' => 1),
			986 => array('cod_marcax'  => 10, 'nom_marcax' => 'DODGE', 'ind_estado' => 1),
			987 => array('cod_marcax'  => 9, 'nom_marcax' => 'VOLKSWAGEN', 'ind_estado' => 1),
			988 => array('cod_marcax'  => 8, 'nom_marcax' => 'RENAULT', 'ind_estado' => 1),
			989 => array('cod_marcax'  => 6, 'nom_marcax' => 'MAZDA', 'ind_estado' => 1),
			990 => array('cod_marcax'  => 5, 'nom_marcax' => 'KIA', 'ind_estado' => 1),
			991 => array('cod_marcax'  => 3, 'nom_marcax' => 'FIAT', 'ind_estado' => 1),
			992 => array('cod_marcax'  => 2, 'nom_marcax' => 'DAEWOO', 'ind_estado' => 1),
			993 => array('cod_marcax'  => 1, 'nom_marcax' => 'CHEVROLET', 'ind_estado' => 1),
			994 => array('cod_marcax'  => 0, 'nom_marcax' => 'SIN MARCA', 'ind_estado' => 1),
		));
    }
}
