<?php

use Illuminate\Database\Seeder;

class PaisesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        set_time_limit(0);

		$array_records = array (
            array('cod_paisxx' => 1, 'nom_paisxx' => 'Afganistán', 'abr_paisxx' => 'AF', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 2, 'nom_paisxx' => 'Islas de Åland', 'abr_paisxx' => 'AX', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 3, 'nom_paisxx' => 'Albania', 'abr_paisxx' => 'AL', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 4, 'nom_paisxx' => 'Argelia', 'abr_paisxx' => 'DZ', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 5, 'nom_paisxx' => 'Samoa Americana', 'abr_paisxx' => 'AS', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 6, 'nom_paisxx' => 'Andorra', 'abr_paisxx' => 'AD', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 7, 'nom_paisxx' => 'Angola', 'abr_paisxx' => 'AO', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 8, 'nom_paisxx' => 'Anguila', 'abr_paisxx' => 'AI', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 9, 'nom_paisxx' => 'Antártida', 'abr_paisxx' => 'AQ', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 10, 'nom_paisxx' => 'Antigua y Barbuda', 'abr_paisxx' => 'AG', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 11, 'nom_paisxx' => 'Argentina', 'abr_paisxx' => 'AR', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 12, 'nom_paisxx' => 'Armenia', 'abr_paisxx' => 'AM', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 13, 'nom_paisxx' => 'Aruba', 'abr_paisxx' => 'AW', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 14, 'nom_paisxx' => 'Australia', 'abr_paisxx' => 'AU', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 15, 'nom_paisxx' => 'Austria', 'abr_paisxx' => 'AT', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 16, 'nom_paisxx' => 'Azerbaiyán', 'abr_paisxx' => 'AZ', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 17, 'nom_paisxx' => 'Bahamas', 'abr_paisxx' => 'BS', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 18, 'nom_paisxx' => 'Baréin', 'abr_paisxx' => 'BH', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 19, 'nom_paisxx' => 'Bangladesh', 'abr_paisxx' => 'BD', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 20, 'nom_paisxx' => 'Barbados', 'abr_paisxx' => 'BB', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 21, 'nom_paisxx' => 'Bielorrusia', 'abr_paisxx' => 'BY', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 22, 'nom_paisxx' => 'Bélgica', 'abr_paisxx' => 'BE', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 23, 'nom_paisxx' => 'Belice', 'abr_paisxx' => 'BZ', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 24, 'nom_paisxx' => 'Benín', 'abr_paisxx' => 'BJ', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 25, 'nom_paisxx' => 'Bermuda', 'abr_paisxx' => 'BM', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 26, 'nom_paisxx' => 'Bután', 'abr_paisxx' => 'BT', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 27, 'nom_paisxx' => 'Bolivia', 'abr_paisxx' => 'BO', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 28, 'nom_paisxx' => 'Bonaire, San Eustaquio y Saba', 'abr_paisxx' => 'BQ', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 29, 'nom_paisxx' => 'Bosnia y Herzegovina', 'abr_paisxx' => 'BA', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 30, 'nom_paisxx' => 'Botsuana', 'abr_paisxx' => 'BW', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 31, 'nom_paisxx' => 'Isla Bouvet', 'abr_paisxx' => 'BV', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 32, 'nom_paisxx' => 'Brasil', 'abr_paisxx' => 'BR', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 33, 'nom_paisxx' => 'Territorio Británico del Océano Índico', 'abr_paisxx' => 'IO', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 34, 'nom_paisxx' => 'Islas Vírgenes Británicas', 'abr_paisxx' => 'VG', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 35, 'nom_paisxx' => 'Brunei', 'abr_paisxx' => 'BN', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 36, 'nom_paisxx' => 'Bulgaria', 'abr_paisxx' => 'BG', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 37, 'nom_paisxx' => 'Burkina Faso', 'abr_paisxx' => 'BF', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 38, 'nom_paisxx' => 'Burundi', 'abr_paisxx' => 'BI', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 39, 'nom_paisxx' => 'Camboya', 'abr_paisxx' => 'KH', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 40, 'nom_paisxx' => 'Camerún', 'abr_paisxx' => 'CM', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 41, 'nom_paisxx' => 'Canadá', 'abr_paisxx' => 'CA', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 42, 'nom_paisxx' => 'Cabo Verde', 'abr_paisxx' => 'CV', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 43, 'nom_paisxx' => 'Islas Caimán', 'abr_paisxx' => 'KY', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 44, 'nom_paisxx' => 'República de África Central', 'abr_paisxx' => 'CF', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 45, 'nom_paisxx' => 'Chad', 'abr_paisxx' => 'TD', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 46, 'nom_paisxx' => 'Chile', 'abr_paisxx' => 'CL', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 47, 'nom_paisxx' => 'China', 'abr_paisxx' => 'CN', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 48, 'nom_paisxx' => 'Isla de Pascua', 'abr_paisxx' => 'CX', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 49, 'nom_paisxx' => 'Islas Cocos', 'abr_paisxx' => 'CC', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 50, 'nom_paisxx' => 'Colombia', 'abr_paisxx' => 'CO', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 51, 'nom_paisxx' => 'Comoras', 'abr_paisxx' => 'KM', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 52, 'nom_paisxx' => 'Islas Cook', 'abr_paisxx' => 'CK', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 53, 'nom_paisxx' => 'Costa Rica', 'abr_paisxx' => 'CR', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 54, 'nom_paisxx' => 'Croacia', 'abr_paisxx' => 'HR', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 55, 'nom_paisxx' => 'Cuba', 'abr_paisxx' => 'CU', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 56, 'nom_paisxx' => 'Curazao', 'abr_paisxx' => 'CW', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 57, 'nom_paisxx' => 'Chipre', 'abr_paisxx' => 'CY', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 58, 'nom_paisxx' => 'República Checa', 'abr_paisxx' => 'CZ', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 59, 'nom_paisxx' => 'República Democrática del Congo', 'abr_paisxx' => 'CD', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 60, 'nom_paisxx' => 'Dinamarca', 'abr_paisxx' => 'DK', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 61, 'nom_paisxx' => 'Yibuti', 'abr_paisxx' => 'DJ', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 62, 'nom_paisxx' => 'Dominica', 'abr_paisxx' => 'DM', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 63, 'nom_paisxx' => 'República Dominicana', 'abr_paisxx' => 'DO', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 64, 'nom_paisxx' => 'Timor Oriental', 'abr_paisxx' => 'TL', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 65, 'nom_paisxx' => 'Ecuador', 'abr_paisxx' => 'EC', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 66, 'nom_paisxx' => 'Egipto', 'abr_paisxx' => 'EG', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 67, 'nom_paisxx' => 'El Salvador', 'abr_paisxx' => 'SV', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 68, 'nom_paisxx' => 'Guinea Ecuatorial', 'abr_paisxx' => 'GQ', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 69, 'nom_paisxx' => 'Eritrea', 'abr_paisxx' => 'ER', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 70, 'nom_paisxx' => 'Estonia', 'abr_paisxx' => 'EE', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 71, 'nom_paisxx' => 'Etiopía', 'abr_paisxx' => 'ET', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 72, 'nom_paisxx' => 'Islas Malvinas', 'abr_paisxx' => 'FK', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 73, 'nom_paisxx' => 'Islas Faroe', 'abr_paisxx' => 'FO', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 74, 'nom_paisxx' => 'Fiji', 'abr_paisxx' => 'FJ', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 75, 'nom_paisxx' => 'Finlandia', 'abr_paisxx' => 'FI', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 76, 'nom_paisxx' => 'Francia', 'abr_paisxx' => 'FR', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 77, 'nom_paisxx' => 'Guayana Francesa', 'abr_paisxx' => 'GF', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 78, 'nom_paisxx' => 'Polinesia Francesa', 'abr_paisxx' => 'PF', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 79, 'nom_paisxx' => 'Territorios del sur Franceses', 'abr_paisxx' => 'TF', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 80, 'nom_paisxx' => 'Gabón', 'abr_paisxx' => 'GA', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 81, 'nom_paisxx' => 'Gambia', 'abr_paisxx' => 'GM', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 82, 'nom_paisxx' => 'Georgia', 'abr_paisxx' => 'GE', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 83, 'nom_paisxx' => 'Alemania', 'abr_paisxx' => 'DE', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 84, 'nom_paisxx' => 'Ghana', 'abr_paisxx' => 'GH', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 85, 'nom_paisxx' => 'Gibraltar', 'abr_paisxx' => 'GI', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 86, 'nom_paisxx' => 'Grecia', 'abr_paisxx' => 'GR', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 87, 'nom_paisxx' => 'Groenlandia', 'abr_paisxx' => 'GL', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 88, 'nom_paisxx' => 'Granada', 'abr_paisxx' => 'GD', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 89, 'nom_paisxx' => 'Guadalupe', 'abr_paisxx' => 'GP', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 90, 'nom_paisxx' => 'Guam', 'abr_paisxx' => 'GU', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 91, 'nom_paisxx' => 'Guatemala', 'abr_paisxx' => 'GT', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 92, 'nom_paisxx' => 'Guernsey', 'abr_paisxx' => 'GG', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 93, 'nom_paisxx' => 'Guinea', 'abr_paisxx' => 'GN', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 94, 'nom_paisxx' => 'Guinea Bissau', 'abr_paisxx' => 'GW', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 95, 'nom_paisxx' => 'Guyana', 'abr_paisxx' => 'GY', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 96, 'nom_paisxx' => 'Haití', 'abr_paisxx' => 'HT', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 97, 'nom_paisxx' => 'Islas Heard y McDonald', 'abr_paisxx' => 'HM', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 98, 'nom_paisxx' => 'Honduras', 'abr_paisxx' => 'HN', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 99, 'nom_paisxx' => 'Hong Kong', 'abr_paisxx' => 'HK', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 100, 'nom_paisxx' => 'Hungría', 'abr_paisxx' => 'HU', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 101, 'nom_paisxx' => 'Islandia', 'abr_paisxx' => 'IS', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 102, 'nom_paisxx' => 'India', 'abr_paisxx' => 'IN', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 103, 'nom_paisxx' => 'Indonesia', 'abr_paisxx' => 'ID', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 104, 'nom_paisxx' => 'Irán', 'abr_paisxx' => 'IR', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 105, 'nom_paisxx' => 'Irak', 'abr_paisxx' => 'IQ', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 106, 'nom_paisxx' => 'Irlanda', 'abr_paisxx' => 'IE', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 107, 'nom_paisxx' => 'Isla de Man', 'abr_paisxx' => 'IM', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 108, 'nom_paisxx' => 'Israel', 'abr_paisxx' => 'IL', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 109, 'nom_paisxx' => 'Italia', 'abr_paisxx' => 'IT', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 110, 'nom_paisxx' => 'Costa de Marfil', 'abr_paisxx' => 'CI', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 111, 'nom_paisxx' => 'Jamaica', 'abr_paisxx' => 'JM', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 112, 'nom_paisxx' => 'Japón', 'abr_paisxx' => 'JP', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 113, 'nom_paisxx' => 'Jersey', 'abr_paisxx' => 'JE', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 114, 'nom_paisxx' => 'Jordania', 'abr_paisxx' => 'JO', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 115, 'nom_paisxx' => 'Kazajistán', 'abr_paisxx' => 'KZ', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 116, 'nom_paisxx' => 'Kenia', 'abr_paisxx' => 'KE', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 117, 'nom_paisxx' => 'Kiribati', 'abr_paisxx' => 'KI', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 118, 'nom_paisxx' => 'Kosovo', 'abr_paisxx' => 'XK', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 119, 'nom_paisxx' => 'Kuwait', 'abr_paisxx' => 'KW', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 120, 'nom_paisxx' => 'Kirguistán', 'abr_paisxx' => 'KG', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 121, 'nom_paisxx' => 'Laos', 'abr_paisxx' => 'LA', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 122, 'nom_paisxx' => 'Letonia', 'abr_paisxx' => 'LV', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 123, 'nom_paisxx' => 'Líbano', 'abr_paisxx' => 'LB', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 124, 'nom_paisxx' => 'Lesoto', 'abr_paisxx' => 'LS', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 125, 'nom_paisxx' => 'Liberia', 'abr_paisxx' => 'LR', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 126, 'nom_paisxx' => 'Libia', 'abr_paisxx' => 'LY', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 127, 'nom_paisxx' => 'Liechtenstein', 'abr_paisxx' => 'LI', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 128, 'nom_paisxx' => 'Lituania', 'abr_paisxx' => 'LT', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 129, 'nom_paisxx' => 'Luxemburgo', 'abr_paisxx' => 'LU', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 130, 'nom_paisxx' => 'Macao', 'abr_paisxx' => 'MO', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 131, 'nom_paisxx' => 'Macedonia', 'abr_paisxx' => 'MK', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 132, 'nom_paisxx' => 'Madagascar', 'abr_paisxx' => 'MG', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 133, 'nom_paisxx' => 'Malaui', 'abr_paisxx' => 'MW', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 134, 'nom_paisxx' => 'Malasia', 'abr_paisxx' => 'MY', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 135, 'nom_paisxx' => 'Maldivas', 'abr_paisxx' => 'MV', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 136, 'nom_paisxx' => 'Malí', 'abr_paisxx' => 'ML', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 137, 'nom_paisxx' => 'Malta', 'abr_paisxx' => 'MT', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 138, 'nom_paisxx' => 'Islas Marshall', 'abr_paisxx' => 'MH', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 139, 'nom_paisxx' => 'Martinica', 'abr_paisxx' => 'MQ', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 140, 'nom_paisxx' => 'Mauritania', 'abr_paisxx' => 'MR', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 141, 'nom_paisxx' => 'Mauricio', 'abr_paisxx' => 'MU', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 142, 'nom_paisxx' => 'Mayotte', 'abr_paisxx' => 'YT', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 143, 'nom_paisxx' => 'México', 'abr_paisxx' => 'MX', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 144, 'nom_paisxx' => 'Micronesia', 'abr_paisxx' => 'FM', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 145, 'nom_paisxx' => 'Moldavia', 'abr_paisxx' => 'MD', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 146, 'nom_paisxx' => 'Mónaco', 'abr_paisxx' => 'MC', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 147, 'nom_paisxx' => 'Mongolia', 'abr_paisxx' => 'MN', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 148, 'nom_paisxx' => 'Montenegro', 'abr_paisxx' => 'ME', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 149, 'nom_paisxx' => 'Montserrat', 'abr_paisxx' => 'MS', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 150, 'nom_paisxx' => 'Marruecos', 'abr_paisxx' => 'MA', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 151, 'nom_paisxx' => 'Mozambique', 'abr_paisxx' => 'MZ', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 152, 'nom_paisxx' => 'Myanmar', 'abr_paisxx' => 'MM', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 153, 'nom_paisxx' => 'Namibia', 'abr_paisxx' => 'NA', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 154, 'nom_paisxx' => 'Nauru', 'abr_paisxx' => 'NR', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 155, 'nom_paisxx' => 'Nepal', 'abr_paisxx' => 'NP', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 156, 'nom_paisxx' => 'Países Bajos', 'abr_paisxx' => 'NL', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 157, 'nom_paisxx' => 'Antillas Holandesas', 'abr_paisxx' => 'AN', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 158, 'nom_paisxx' => 'Nueva Caledonia', 'abr_paisxx' => 'NC', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 159, 'nom_paisxx' => 'Nueva Zelanda', 'abr_paisxx' => 'NZ', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 160, 'nom_paisxx' => 'Nicaragua', 'abr_paisxx' => 'NI', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 161, 'nom_paisxx' => 'Níger', 'abr_paisxx' => 'NE', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 162, 'nom_paisxx' => 'Nigeria', 'abr_paisxx' => 'NG', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 163, 'nom_paisxx' => 'Niue', 'abr_paisxx' => 'NU', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 164, 'nom_paisxx' => 'Isla Norfolk', 'abr_paisxx' => 'NF', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 165, 'nom_paisxx' => 'Corea del Norte', 'abr_paisxx' => 'KP', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 166, 'nom_paisxx' => 'Islas Marianas del Norte', 'abr_paisxx' => 'MP', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 167, 'nom_paisxx' => 'Noruega', 'abr_paisxx' => 'NO', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 168, 'nom_paisxx' => 'Omán', 'abr_paisxx' => 'OM', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 169, 'nom_paisxx' => 'Pakistán', 'abr_paisxx' => 'PK', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 170, 'nom_paisxx' => 'Palaos', 'abr_paisxx' => 'PW', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 171, 'nom_paisxx' => 'Territorios Palestinos', 'abr_paisxx' => 'PS', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 172, 'nom_paisxx' => 'Panamá', 'abr_paisxx' => 'PA', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 173, 'nom_paisxx' => 'Papúa Nueva Guinea', 'abr_paisxx' => 'PG', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 174, 'nom_paisxx' => 'Paraguay', 'abr_paisxx' => 'PY', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 175, 'nom_paisxx' => 'Perú', 'abr_paisxx' => 'PE', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 176, 'nom_paisxx' => 'Filipinas', 'abr_paisxx' => 'PH', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 177, 'nom_paisxx' => 'Islas Pitcairn', 'abr_paisxx' => 'PN', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 178, 'nom_paisxx' => 'Polonia', 'abr_paisxx' => 'PL', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 179, 'nom_paisxx' => 'Portugal', 'abr_paisxx' => 'PT', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 180, 'nom_paisxx' => 'Puerto Rico', 'abr_paisxx' => 'PR', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 181, 'nom_paisxx' => 'Catar', 'abr_paisxx' => 'QA', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 182, 'nom_paisxx' => 'República del Congo', 'abr_paisxx' => 'CG', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 183, 'nom_paisxx' => 'Reunión', 'abr_paisxx' => 'RE', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 184, 'nom_paisxx' => 'Rumanía', 'abr_paisxx' => 'RO', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 185, 'nom_paisxx' => 'Rusia', 'abr_paisxx' => 'RU', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 186, 'nom_paisxx' => 'Ruanda', 'abr_paisxx' => 'RW', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 187, 'nom_paisxx' => 'San Bartolomé', 'abr_paisxx' => 'BL', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 188, 'nom_paisxx' => 'Santa Elena', 'abr_paisxx' => 'SH', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 189, 'nom_paisxx' => 'San Cristóbal y Nieves', 'abr_paisxx' => 'KN', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 190, 'nom_paisxx' => 'Santa Lucía', 'abr_paisxx' => 'LC', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 191, 'nom_paisxx' => 'San Martín', 'abr_paisxx' => 'MF', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 192, 'nom_paisxx' => 'San Pedro y Miguelón', 'abr_paisxx' => 'PM', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 193, 'nom_paisxx' => 'San Vicente y las Granadinas', 'abr_paisxx' => 'VC', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 194, 'nom_paisxx' => 'Samoa Occidental', 'abr_paisxx' => 'WS', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 195, 'nom_paisxx' => 'San Marino', 'abr_paisxx' => 'SM', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 196, 'nom_paisxx' => 'Santo Tomé y Príncipe', 'abr_paisxx' => 'ST', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 197, 'nom_paisxx' => 'Arabia Saudita', 'abr_paisxx' => 'SA', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 198, 'nom_paisxx' => 'Senegal', 'abr_paisxx' => 'SN', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 199, 'nom_paisxx' => 'Serbia', 'abr_paisxx' => 'RS', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 200, 'nom_paisxx' => 'Serbia y Montenegro', 'abr_paisxx' => 'CS', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 201, 'nom_paisxx' => 'Seychelles', 'abr_paisxx' => 'SC', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 202, 'nom_paisxx' => 'Sierra Leona', 'abr_paisxx' => 'SL', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 203, 'nom_paisxx' => 'Singapur', 'abr_paisxx' => 'SG', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 204, 'nom_paisxx' => 'San Martín', 'abr_paisxx' => 'SX', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 205, 'nom_paisxx' => 'Eslovaquia', 'abr_paisxx' => 'SK', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 206, 'nom_paisxx' => 'Eslovenia', 'abr_paisxx' => 'SI', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 207, 'nom_paisxx' => 'Islas Salomón', 'abr_paisxx' => 'SB', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 208, 'nom_paisxx' => 'Somalia', 'abr_paisxx' => 'SO', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 209, 'nom_paisxx' => 'Sudáfrica', 'abr_paisxx' => 'ZA', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 210, 'nom_paisxx' => 'Islas Georgia del Sur y Sandwich del Sur', 'abr_paisxx' => 'GS', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 211, 'nom_paisxx' => 'Corea del Sur', 'abr_paisxx' => 'KR', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 212, 'nom_paisxx' => 'Sudán del Sur', 'abr_paisxx' => 'SS', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 213, 'nom_paisxx' => 'España', 'abr_paisxx' => 'ES', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 214, 'nom_paisxx' => 'Sri Lanka', 'abr_paisxx' => 'LK', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 215, 'nom_paisxx' => 'Sudán', 'abr_paisxx' => 'SD', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 216, 'nom_paisxx' => 'Surinam', 'abr_paisxx' => 'SR', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 217, 'nom_paisxx' => 'Islas Svalbard y Jan Mayen', 'abr_paisxx' => 'SJ', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 218, 'nom_paisxx' => 'Suazilandia', 'abr_paisxx' => 'SZ', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 219, 'nom_paisxx' => 'Suecia', 'abr_paisxx' => 'SE', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 220, 'nom_paisxx' => 'Suiza', 'abr_paisxx' => 'CH', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 221, 'nom_paisxx' => 'Siria', 'abr_paisxx' => 'SY', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 222, 'nom_paisxx' => 'Taiwán', 'abr_paisxx' => 'TW', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 223, 'nom_paisxx' => 'Tayikistán', 'abr_paisxx' => 'TJ', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 224, 'nom_paisxx' => 'Tanzania', 'abr_paisxx' => 'TZ', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 225, 'nom_paisxx' => 'Tailandia', 'abr_paisxx' => 'TH', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 226, 'nom_paisxx' => 'República Togolesa', 'abr_paisxx' => 'TG', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 227, 'nom_paisxx' => 'Islas Tokelau', 'abr_paisxx' => 'TK', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 228, 'nom_paisxx' => 'Tonga', 'abr_paisxx' => 'TO', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 229, 'nom_paisxx' => 'Trinidad y Tobago', 'abr_paisxx' => 'TT', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 230, 'nom_paisxx' => 'Túnez', 'abr_paisxx' => 'TN', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 231, 'nom_paisxx' => 'Turquía', 'abr_paisxx' => 'TR', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 232, 'nom_paisxx' => 'Turkmenistán', 'abr_paisxx' => 'TM', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 233, 'nom_paisxx' => 'Islas Turcos y Caicos', 'abr_paisxx' => 'TC', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 234, 'nom_paisxx' => 'Tuvalu', 'abr_paisxx' => 'TV', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 235, 'nom_paisxx' => 'Islas Vírgenes de los EE.UU.', 'abr_paisxx' => 'VI', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 236, 'nom_paisxx' => 'Uganda', 'abr_paisxx' => 'UG', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 237, 'nom_paisxx' => 'Ucrania', 'abr_paisxx' => 'UA', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 238, 'nom_paisxx' => 'Emiratos Árabes Unidos', 'abr_paisxx' => 'AE', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 239, 'nom_paisxx' => 'Reino Unido', 'abr_paisxx' => 'GB', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 240, 'nom_paisxx' => 'Estados Unidos (USA)', 'abr_paisxx' => 'US', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 241, 'nom_paisxx' => 'Islas menores alejadas de los Estados Unidos', 'abr_paisxx' => 'UM', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 242, 'nom_paisxx' => 'Uruguay', 'abr_paisxx' => 'UY', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 243, 'nom_paisxx' => 'Uzbekistán', 'abr_paisxx' => 'UZ', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 244, 'nom_paisxx' => 'Vanuatu', 'abr_paisxx' => 'VU', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 245, 'nom_paisxx' => 'Vaticano', 'abr_paisxx' => 'VA', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 246, 'nom_paisxx' => 'Venezuela', 'abr_paisxx' => 'VE', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 247, 'nom_paisxx' => 'Vietnam', 'abr_paisxx' => 'VN', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 248, 'nom_paisxx' => 'Wallis y Futuna', 'abr_paisxx' => 'WF', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 249, 'nom_paisxx' => 'Sahara Occidental', 'abr_paisxx' => 'EH', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 250, 'nom_paisxx' => 'Yemen', 'abr_paisxx' => 'YE', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 251, 'nom_paisxx' => 'Zambia', 'abr_paisxx' => 'ZM', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
            array('cod_paisxx' => 252, 'nom_paisxx' => 'Zimbabue', 'abr_paisxx' => 'ZW', 'usr_creaci' => 'SYSTEM', 'usr_modifi' => NULL, 'ind_estado' => 1),
        );

		foreach (array_chunk($array_records, 1000) as $records) {
			\DB::table('paises')->insert($records);
		}
    }
}
